// Coordinator is the internal RPC surface between shards and the global
// coordinator. The coordinator does not make provisioning decisions; it
// owns shard membership, the cluster→shard map, the topology-domain→shard
// map, quota allocations, and the provider registry, and it issues
// rebalancing / cross-shard preemption instructions.
//
// Every coordinator-issued instruction carries (coordinator_term, sequence_number).
// Shards reject instructions with stale terms (zombie-leader protection).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: bigfleet/v1alpha1/coordinator.proto

package bigfleetv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_ReportShard_FullMethodName = "/bigfleet.v1alpha1.Coordinator/ReportShard"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClient interface {
	// Shards push periodic reports. Idempotent per (shard_id, cycle).
	// The response carries any pending CoordinatorInstruction messages
	// the shard should execute, plus the coordinator's current term.
	// The shard piggybacks acks for previously-received instructions on
	// its next ReportShard call (ShardReport.instruction_acks). This
	// keeps the v1 wire surface to one unary RPC; a streaming
	// Instructions RPC may land in a future revision.
	ReportShard(ctx context.Context, in *ShardReport, opts ...grpc.CallOption) (*ReportAck, error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) ReportShard(ctx context.Context, in *ShardReport, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, Coordinator_ReportShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
type CoordinatorServer interface {
	// Shards push periodic reports. Idempotent per (shard_id, cycle).
	// The response carries any pending CoordinatorInstruction messages
	// the shard should execute, plus the coordinator's current term.
	// The shard piggybacks acks for previously-received instructions on
	// its next ReportShard call (ShardReport.instruction_acks). This
	// keeps the v1 wire surface to one unary RPC; a streaming
	// Instructions RPC may land in a future revision.
	ReportShard(context.Context, *ShardReport) (*ReportAck, error)
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) ReportShard(context.Context, *ShardReport) (*ReportAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportShard not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_ReportShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportShard(ctx, req.(*ShardReport))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigfleet.v1alpha1.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportShard",
			Handler:    _Coordinator_ReportShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bigfleet/v1alpha1/coordinator.proto",
}
