// Coordinator is the internal RPC surface between shards and the global
// coordinator. The coordinator does not make provisioning decisions; it
// owns shard membership, the cluster→shard map, the topology-domain→shard
// map, quota allocations, and the provider registry, and it issues
// rebalancing / cross-shard preemption instructions.
//
// Every coordinator-issued instruction carries (coordinator_term, sequence_number).
// Shards reject instructions with stale terms (zombie-leader protection).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: bigfleet/v1alpha1/coordinator.proto

package bigfleetv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_ReportShard_FullMethodName           = "/bigfleet.v1alpha1.Coordinator/ReportShard"
	Coordinator_AssignDomain_FullMethodName          = "/bigfleet.v1alpha1.Coordinator/AssignDomain"
	Coordinator_UnassignDomain_FullMethodName        = "/bigfleet.v1alpha1.Coordinator/UnassignDomain"
	Coordinator_RemoveShard_FullMethodName           = "/bigfleet.v1alpha1.Coordinator/RemoveShard"
	Coordinator_ListShards_FullMethodName            = "/bigfleet.v1alpha1.Coordinator/ListShards"
	Coordinator_ListDomainAssignments_FullMethodName = "/bigfleet.v1alpha1.Coordinator/ListDomainAssignments"
	Coordinator_ListQuotas_FullMethodName            = "/bigfleet.v1alpha1.Coordinator/ListQuotas"
	Coordinator_JoinRaftCluster_FullMethodName       = "/bigfleet.v1alpha1.Coordinator/JoinRaftCluster"
	Coordinator_SnapshotSave_FullMethodName          = "/bigfleet.v1alpha1.Coordinator/SnapshotSave"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClient interface {
	// Shards push periodic reports. Idempotent per (shard_id, cycle).
	// The response carries any pending CoordinatorInstruction messages
	// the shard should execute, plus the coordinator's current term.
	// The shard piggybacks acks for previously-received instructions on
	// its next ReportShard call (ShardReport.instruction_acks). This
	// keeps the v1 wire surface to one unary RPC; a streaming
	// Instructions RPC may land in a future revision.
	ReportShard(ctx context.Context, in *ShardReport, opts ...grpc.CallOption) (*ReportAck, error)
	// M15 admin surface. Each RPC is leader-only and returns
	// FailedPrecondition on followers (the same redirect contract as
	// ReportShard). v1 ships unauthenticated — the coordinator's gRPC
	// service is a cluster-internal endpoint; exposing it externally
	// requires a sidecar (mTLS / OIDC). cmd/bigfleetctl is the
	// intended client.
	AssignDomain(ctx context.Context, in *AssignDomainRequest, opts ...grpc.CallOption) (*AssignDomainResponse, error)
	UnassignDomain(ctx context.Context, in *UnassignDomainRequest, opts ...grpc.CallOption) (*UnassignDomainResponse, error)
	RemoveShard(ctx context.Context, in *RemoveShardRequest, opts ...grpc.CallOption) (*RemoveShardResponse, error)
	ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error)
	ListDomainAssignments(ctx context.Context, in *ListDomainAssignmentsRequest, opts ...grpc.CallOption) (*ListDomainAssignmentsResponse, error)
	// M24 quota inspection. Lets on-call surface "the coordinator's
	// quota assignments for this shard" from the user-stories runbook
	// without going into Raft state directly. SetQuota writes through
	// the FSM (idempotent overwrite of the per-shard slice for a
	// (provider, region) key); ListQuotas is a read.
	ListQuotas(ctx context.Context, in *ListQuotasRequest, opts ...grpc.CallOption) (*ListQuotasResponse, error)
	// M75 Raft membership (ADR-0047). A coordinator replica with no
	// existing Raft state asks the leader to AddVoter it into the
	// cluster. Leader-only (FailedPrecondition on followers / on
	// unbootstrapped replicas); the joiner retries with backoff until
	// the call lands on the leader. AddVoter of an existing voter is
	// idempotent in hashicorp/raft (the configuration change updates
	// the address in place), so re-joins after a restart are safe.
	// Same ADR-0008 open-trust posture as the rest of this surface;
	// M74 authenticates it.
	JoinRaftCluster(ctx context.Context, in *JoinRaftClusterRequest, opts ...grpc.CallOption) (*JoinRaftClusterResponse, error)
	// M75 DR (ADR-0047). Streams the leader's freshest Raft snapshot
	// (meta first, then state chunks) so `bigfleetctl snapshot save`
	// can capture a restorable backup from a running coordinator.
	// Leader-only — followers may not have a complete snapshot.
	SnapshotSave(ctx context.Context, in *SnapshotSaveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotSaveChunk], error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) ReportShard(ctx context.Context, in *ShardReport, opts ...grpc.CallOption) (*ReportAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAck)
	err := c.cc.Invoke(ctx, Coordinator_ReportShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) AssignDomain(ctx context.Context, in *AssignDomainRequest, opts ...grpc.CallOption) (*AssignDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignDomainResponse)
	err := c.cc.Invoke(ctx, Coordinator_AssignDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) UnassignDomain(ctx context.Context, in *UnassignDomainRequest, opts ...grpc.CallOption) (*UnassignDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnassignDomainResponse)
	err := c.cc.Invoke(ctx, Coordinator_UnassignDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) RemoveShard(ctx context.Context, in *RemoveShardRequest, opts ...grpc.CallOption) (*RemoveShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveShardResponse)
	err := c.cc.Invoke(ctx, Coordinator_RemoveShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListShards(ctx context.Context, in *ListShardsRequest, opts ...grpc.CallOption) (*ListShardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShardsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListShards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListDomainAssignments(ctx context.Context, in *ListDomainAssignmentsRequest, opts ...grpc.CallOption) (*ListDomainAssignmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDomainAssignmentsResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListDomainAssignments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ListQuotas(ctx context.Context, in *ListQuotasRequest, opts ...grpc.CallOption) (*ListQuotasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuotasResponse)
	err := c.cc.Invoke(ctx, Coordinator_ListQuotas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) JoinRaftCluster(ctx context.Context, in *JoinRaftClusterRequest, opts ...grpc.CallOption) (*JoinRaftClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRaftClusterResponse)
	err := c.cc.Invoke(ctx, Coordinator_JoinRaftCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) SnapshotSave(ctx context.Context, in *SnapshotSaveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotSaveChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[0], Coordinator_SnapshotSave_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotSaveRequest, SnapshotSaveChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_SnapshotSaveClient = grpc.ServerStreamingClient[SnapshotSaveChunk]

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
type CoordinatorServer interface {
	// Shards push periodic reports. Idempotent per (shard_id, cycle).
	// The response carries any pending CoordinatorInstruction messages
	// the shard should execute, plus the coordinator's current term.
	// The shard piggybacks acks for previously-received instructions on
	// its next ReportShard call (ShardReport.instruction_acks). This
	// keeps the v1 wire surface to one unary RPC; a streaming
	// Instructions RPC may land in a future revision.
	ReportShard(context.Context, *ShardReport) (*ReportAck, error)
	// M15 admin surface. Each RPC is leader-only and returns
	// FailedPrecondition on followers (the same redirect contract as
	// ReportShard). v1 ships unauthenticated — the coordinator's gRPC
	// service is a cluster-internal endpoint; exposing it externally
	// requires a sidecar (mTLS / OIDC). cmd/bigfleetctl is the
	// intended client.
	AssignDomain(context.Context, *AssignDomainRequest) (*AssignDomainResponse, error)
	UnassignDomain(context.Context, *UnassignDomainRequest) (*UnassignDomainResponse, error)
	RemoveShard(context.Context, *RemoveShardRequest) (*RemoveShardResponse, error)
	ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error)
	ListDomainAssignments(context.Context, *ListDomainAssignmentsRequest) (*ListDomainAssignmentsResponse, error)
	// M24 quota inspection. Lets on-call surface "the coordinator's
	// quota assignments for this shard" from the user-stories runbook
	// without going into Raft state directly. SetQuota writes through
	// the FSM (idempotent overwrite of the per-shard slice for a
	// (provider, region) key); ListQuotas is a read.
	ListQuotas(context.Context, *ListQuotasRequest) (*ListQuotasResponse, error)
	// M75 Raft membership (ADR-0047). A coordinator replica with no
	// existing Raft state asks the leader to AddVoter it into the
	// cluster. Leader-only (FailedPrecondition on followers / on
	// unbootstrapped replicas); the joiner retries with backoff until
	// the call lands on the leader. AddVoter of an existing voter is
	// idempotent in hashicorp/raft (the configuration change updates
	// the address in place), so re-joins after a restart are safe.
	// Same ADR-0008 open-trust posture as the rest of this surface;
	// M74 authenticates it.
	JoinRaftCluster(context.Context, *JoinRaftClusterRequest) (*JoinRaftClusterResponse, error)
	// M75 DR (ADR-0047). Streams the leader's freshest Raft snapshot
	// (meta first, then state chunks) so `bigfleetctl snapshot save`
	// can capture a restorable backup from a running coordinator.
	// Leader-only — followers may not have a complete snapshot.
	SnapshotSave(*SnapshotSaveRequest, grpc.ServerStreamingServer[SnapshotSaveChunk]) error
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) ReportShard(context.Context, *ShardReport) (*ReportAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportShard not implemented")
}
func (UnimplementedCoordinatorServer) AssignDomain(context.Context, *AssignDomainRequest) (*AssignDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDomain not implemented")
}
func (UnimplementedCoordinatorServer) UnassignDomain(context.Context, *UnassignDomainRequest) (*UnassignDomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnassignDomain not implemented")
}
func (UnimplementedCoordinatorServer) RemoveShard(context.Context, *RemoveShardRequest) (*RemoveShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveShard not implemented")
}
func (UnimplementedCoordinatorServer) ListShards(context.Context, *ListShardsRequest) (*ListShardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListShards not implemented")
}
func (UnimplementedCoordinatorServer) ListDomainAssignments(context.Context, *ListDomainAssignmentsRequest) (*ListDomainAssignmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomainAssignments not implemented")
}
func (UnimplementedCoordinatorServer) ListQuotas(context.Context, *ListQuotasRequest) (*ListQuotasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQuotas not implemented")
}
func (UnimplementedCoordinatorServer) JoinRaftCluster(context.Context, *JoinRaftClusterRequest) (*JoinRaftClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRaftCluster not implemented")
}
func (UnimplementedCoordinatorServer) SnapshotSave(*SnapshotSaveRequest, grpc.ServerStreamingServer[SnapshotSaveChunk]) error {
	return status.Errorf(codes.Unimplemented, "method SnapshotSave not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_ReportShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShardReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ReportShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportShard(ctx, req.(*ShardReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_AssignDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).AssignDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_AssignDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).AssignDomain(ctx, req.(*AssignDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_UnassignDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnassignDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).UnassignDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_UnassignDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).UnassignDomain(ctx, req.(*UnassignDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_RemoveShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).RemoveShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_RemoveShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).RemoveShard(ctx, req.(*RemoveShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListShards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListShards(ctx, req.(*ListShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListDomainAssignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainAssignmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListDomainAssignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListDomainAssignments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListDomainAssignments(ctx, req.(*ListDomainAssignmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ListQuotas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuotasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ListQuotas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_ListQuotas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ListQuotas(ctx, req.(*ListQuotasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_JoinRaftCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRaftClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).JoinRaftCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_JoinRaftCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).JoinRaftCluster(ctx, req.(*JoinRaftClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_SnapshotSave_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SnapshotSaveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinatorServer).SnapshotSave(m, &grpc.GenericServerStream[SnapshotSaveRequest, SnapshotSaveChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_SnapshotSaveServer = grpc.ServerStreamingServer[SnapshotSaveChunk]

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigfleet.v1alpha1.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportShard",
			Handler:    _Coordinator_ReportShard_Handler,
		},
		{
			MethodName: "AssignDomain",
			Handler:    _Coordinator_AssignDomain_Handler,
		},
		{
			MethodName: "UnassignDomain",
			Handler:    _Coordinator_UnassignDomain_Handler,
		},
		{
			MethodName: "RemoveShard",
			Handler:    _Coordinator_RemoveShard_Handler,
		},
		{
			MethodName: "ListShards",
			Handler:    _Coordinator_ListShards_Handler,
		},
		{
			MethodName: "ListDomainAssignments",
			Handler:    _Coordinator_ListDomainAssignments_Handler,
		},
		{
			MethodName: "ListQuotas",
			Handler:    _Coordinator_ListQuotas_Handler,
		},
		{
			MethodName: "JoinRaftCluster",
			Handler:    _Coordinator_JoinRaftCluster_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SnapshotSave",
			Handler:       _Coordinator_SnapshotSave_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bigfleet/v1alpha1/coordinator.proto",
}
