// Coordinator is the internal RPC surface between shards and the global
// coordinator. The coordinator does not make provisioning decisions; it
// owns shard membership, the cluster→shard map, the topology-domain→shard
// map, quota allocations, and the provider registry, and it issues
// rebalancing / cross-shard preemption instructions.
//
// Every coordinator-issued instruction carries (coordinator_term, sequence_number).
// Shards reject instructions with stale terms (zombie-leader protection).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bigfleet/v1alpha1/coordinator.proto

package bigfleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstructAck_Outcome int32

const (
	InstructAck_OUTCOME_UNSPECIFIED      InstructAck_Outcome = 0
	InstructAck_OUTCOME_ACCEPTED         InstructAck_Outcome = 1
	InstructAck_OUTCOME_REJECTED_STALE   InstructAck_Outcome = 2 // term older than shard's high-water mark
	InstructAck_OUTCOME_REJECTED_INVALID InstructAck_Outcome = 3 // semantically not applicable
	InstructAck_OUTCOME_FAILED           InstructAck_Outcome = 4
)

// Enum value maps for InstructAck_Outcome.
var (
	InstructAck_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_REJECTED_STALE",
		3: "OUTCOME_REJECTED_INVALID",
		4: "OUTCOME_FAILED",
	}
	InstructAck_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":      0,
		"OUTCOME_ACCEPTED":         1,
		"OUTCOME_REJECTED_STALE":   2,
		"OUTCOME_REJECTED_INVALID": 3,
		"OUTCOME_FAILED":           4,
	}
)

func (x InstructAck_Outcome) Enum() *InstructAck_Outcome {
	p := new(InstructAck_Outcome)
	*p = x
	return p
}

func (x InstructAck_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstructAck_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_coordinator_proto_enumTypes[0].Descriptor()
}

func (InstructAck_Outcome) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_coordinator_proto_enumTypes[0]
}

func (x InstructAck_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstructAck_Outcome.Descriptor instead.
func (InstructAck_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{10, 0}
}

// ShardReport is what each shard sends every ~30s. Stateless: the
// coordinator builds its fleet picture from the latest report per shard.
type ShardReport struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Monotonic counter for this shard's reports. Used by the coordinator
	// to discard out-of-order delivery.
	Cycle int64 `protobuf:"varint,2,opt,name=cycle,proto3" json:"cycle,omitempty"`
	// Wall-clock time of report generation.
	TimestampUnixNanos int64 `protobuf:"varint,3,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	// Shard's epoch. Increments on shard restart. Carried so coordinator
	// logs can correlate with shard-side fencing.
	ShardEpoch int64 `protobuf:"varint,4,opt,name=shard_epoch,json=shardEpoch,proto3" json:"shard_epoch,omitempty"`
	// Aggregate inventory and demand summaries. Bounded in size; not the
	// per-machine inventory.
	Summary *ShardSummary `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	// Top-N unresolved needs, ranked by priority. Bounded to 100 per
	// §3.5 / shortfall protocol.
	Shortfalls    []*Shortfall `protobuf:"bytes,6,rep,name=shortfalls,proto3" json:"shortfalls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardReport) Reset() {
	*x = ShardReport{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReport) ProtoMessage() {}

func (x *ShardReport) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReport.ProtoReflect.Descriptor instead.
func (*ShardReport) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *ShardReport) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardReport) GetCycle() int64 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *ShardReport) GetTimestampUnixNanos() int64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *ShardReport) GetShardEpoch() int64 {
	if x != nil {
		return x.ShardEpoch
	}
	return 0
}

func (x *ShardReport) GetSummary() *ShardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ShardReport) GetShortfalls() []*Shortfall {
	if x != nil {
		return x.Shortfalls
	}
	return nil
}

// ShardSummary is a coarse-grained snapshot of a shard's inventory and
// demand. Sized to fit alongside 200 other shard summaries in the
// coordinator's L1/L2-resident state.
type ShardSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total machines owned by the shard, in any state.
	TotalMachines int32 `protobuf:"varint,1,opt,name=total_machines,json=totalMachines,proto3" json:"total_machines,omitempty"`
	// Machines available for assignment (state == IDLE or SPECULATIVE).
	FreeMachines int32 `protobuf:"varint,2,opt,name=free_machines,json=freeMachines,proto3" json:"free_machines,omitempty"`
	// Per-instance-type counts for whichever instance types the shard
	// currently owns. Bounded by the shard's catalog (small).
	PerInstanceTypeCounts map[string]int32 `protobuf:"bytes,3,rep,name=per_instance_type_counts,json=perInstanceTypeCounts,proto3" json:"per_instance_type_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Per-zone counts. Bounded by zones the shard touches.
	PerZoneCounts map[string]int32 `protobuf:"bytes,4,rep,name=per_zone_counts,json=perZoneCounts,proto3" json:"per_zone_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Aggregate utilisation hints. Defined by the operator's reporting
	// policy; the coordinator does not interpret precise values.
	UtilisationCpuFraction    float64 `protobuf:"fixed64,5,opt,name=utilisation_cpu_fraction,json=utilisationCpuFraction,proto3" json:"utilisation_cpu_fraction,omitempty"`
	UtilisationMemoryFraction float64 `protobuf:"fixed64,6,opt,name=utilisation_memory_fraction,json=utilisationMemoryFraction,proto3" json:"utilisation_memory_fraction,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ShardSummary) Reset() {
	*x = ShardSummary{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSummary) ProtoMessage() {}

func (x *ShardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSummary.ProtoReflect.Descriptor instead.
func (*ShardSummary) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ShardSummary) GetTotalMachines() int32 {
	if x != nil {
		return x.TotalMachines
	}
	return 0
}

func (x *ShardSummary) GetFreeMachines() int32 {
	if x != nil {
		return x.FreeMachines
	}
	return 0
}

func (x *ShardSummary) GetPerInstanceTypeCounts() map[string]int32 {
	if x != nil {
		return x.PerInstanceTypeCounts
	}
	return nil
}

func (x *ShardSummary) GetPerZoneCounts() map[string]int32 {
	if x != nil {
		return x.PerZoneCounts
	}
	return nil
}

func (x *ShardSummary) GetUtilisationCpuFraction() float64 {
	if x != nil {
		return x.UtilisationCpuFraction
	}
	return 0
}

func (x *ShardSummary) GetUtilisationMemoryFraction() float64 {
	if x != nil {
		return x.UtilisationMemoryFraction
	}
	return 0
}

// Shortfall describes a need the shard could not satisfy from its own
// inventory and could not resolve via in-shard preemption. The coordinator
// uses these to drive cross-shard rebalancing and preemption.
type Shortfall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unsatisfied profile.
	Requirements []*NodeSelectorRequirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Resources    *Resources                 `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Priority     int32                      `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Count        int32                      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Cycles this shortfall has been unresolved. >5 escalates to fleet
	// telemetry per the shortfall protocol.
	AgeCycles int32 `protobuf:"varint,5,opt,name=age_cycles,json=ageCycles,proto3" json:"age_cycles,omitempty"`
	// Bucketed interruption penalty of the originating CapacityNeed.
	// Lets the coordinator price cross-shard preemption.
	InterruptionPenaltyBucket PenaltyBucket `protobuf:"varint,6,opt,name=interruption_penalty_bucket,json=interruptionPenaltyBucket,proto3,enum=bigfleet.v1alpha1.PenaltyBucket" json:"interruption_penalty_bucket,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Shortfall) Reset() {
	*x = Shortfall{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shortfall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortfall) ProtoMessage() {}

func (x *Shortfall) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortfall.ProtoReflect.Descriptor instead.
func (*Shortfall) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *Shortfall) GetRequirements() []*NodeSelectorRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Shortfall) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Shortfall) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Shortfall) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Shortfall) GetAgeCycles() int32 {
	if x != nil {
		return x.AgeCycles
	}
	return 0
}

func (x *Shortfall) GetInterruptionPenaltyBucket() PenaltyBucket {
	if x != nil {
		return x.InterruptionPenaltyBucket
	}
	return PenaltyBucket_PENALTY_BUCKET_UNSPECIFIED
}

type ReportAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coordinator's current term as observed at report time. The shard
	// updates its high-water mark from this so subsequent Instruct frames
	// can be checked against a known-good term.
	CoordinatorTerm int64 `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	Acknowledged    bool  `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *ReportAck) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *ReportAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

// CoordinatorInstruction is the shard-bound action the coordinator wants
// taken. Each instruction is fenced by (term, sequence) — shards reject
// any instruction whose term is older than the highest observed.
type CoordinatorInstruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fencing token. The shard rejects instructions whose term is less
	// than its high-water mark.
	CoordinatorTerm int64 `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	SequenceNumber  int64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Stable id for the instruction; reused across retries by the
	// coordinator so shards can deduplicate.
	InstructionId string `protobuf:"bytes,3,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorInstruction_AssignDomain
	//	*CoordinatorInstruction_UnassignDomain
	//	*CoordinatorInstruction_ReassignSpeculative
	//	*CoordinatorInstruction_CrossShardDrain
	//	*CoordinatorInstruction_TransferOwnership
	Payload       isCoordinatorInstruction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorInstruction) Reset() {
	*x = CoordinatorInstruction{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorInstruction) ProtoMessage() {}

func (x *CoordinatorInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorInstruction.ProtoReflect.Descriptor instead.
func (*CoordinatorInstruction) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorInstruction) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *CoordinatorInstruction) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CoordinatorInstruction) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *CoordinatorInstruction) GetPayload() isCoordinatorInstruction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorInstruction) GetAssignDomain() *AssignDomain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_AssignDomain); ok {
			return x.AssignDomain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetUnassignDomain() *UnassignDomain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_UnassignDomain); ok {
			return x.UnassignDomain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetReassignSpeculative() *ReassignSpeculative {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_ReassignSpeculative); ok {
			return x.ReassignSpeculative
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetCrossShardDrain() *CrossShardDrain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_CrossShardDrain); ok {
			return x.CrossShardDrain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetTransferOwnership() *TransferOwnership {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_TransferOwnership); ok {
			return x.TransferOwnership
		}
	}
	return nil
}

type isCoordinatorInstruction_Payload interface {
	isCoordinatorInstruction_Payload()
}

type CoordinatorInstruction_AssignDomain struct {
	AssignDomain *AssignDomain `protobuf:"bytes,4,opt,name=assign_domain,json=assignDomain,proto3,oneof"`
}

type CoordinatorInstruction_UnassignDomain struct {
	UnassignDomain *UnassignDomain `protobuf:"bytes,5,opt,name=unassign_domain,json=unassignDomain,proto3,oneof"`
}

type CoordinatorInstruction_ReassignSpeculative struct {
	ReassignSpeculative *ReassignSpeculative `protobuf:"bytes,6,opt,name=reassign_speculative,json=reassignSpeculative,proto3,oneof"`
}

type CoordinatorInstruction_CrossShardDrain struct {
	CrossShardDrain *CrossShardDrain `protobuf:"bytes,7,opt,name=cross_shard_drain,json=crossShardDrain,proto3,oneof"`
}

type CoordinatorInstruction_TransferOwnership struct {
	TransferOwnership *TransferOwnership `protobuf:"bytes,8,opt,name=transfer_ownership,json=transferOwnership,proto3,oneof"`
}

func (*CoordinatorInstruction_AssignDomain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_UnassignDomain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_ReassignSpeculative) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_CrossShardDrain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_TransferOwnership) isCoordinatorInstruction_Payload() {}

// AssignDomain hands a topology domain to this shard. Per plan §10.1 we
// assign at topology-domain granularity (rack, zone-slice), not machine.
type AssignDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDomain) Reset() {
	*x = AssignDomain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDomain) ProtoMessage() {}

func (x *AssignDomain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDomain.ProtoReflect.Descriptor instead.
func (*AssignDomain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *AssignDomain) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *AssignDomain) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

// UnassignDomain releases a topology domain previously assigned. Used
// during shard splits / merges.
type UnassignDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignDomain) Reset() {
	*x = UnassignDomain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignDomain) ProtoMessage() {}

func (x *UnassignDomain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignDomain.ProtoReflect.Descriptor instead.
func (*UnassignDomain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *UnassignDomain) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *UnassignDomain) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

// ReassignSpeculative moves quota slices between shards. Pure bookkeeping
// — no real machines exist yet.
type ReassignSpeculative struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The speculative machine ids being transferred. The receiving shard
	// takes ownership; the donating shard releases.
	MachineIds    []string `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignSpeculative) Reset() {
	*x = ReassignSpeculative{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignSpeculative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignSpeculative) ProtoMessage() {}

func (x *ReassignSpeculative) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignSpeculative.ProtoReflect.Descriptor instead.
func (*ReassignSpeculative) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *ReassignSpeculative) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

// CrossShardDrain instructs a donor shard to drain configured machines so
// they can become idle and be transferred. The donor shard scores victims
// and emits ReclaimInstruction frames to the affected cluster operators.
type CrossShardDrain struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MachineIds []string               `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	// Priority of the preemptor on the requesting shard. The donor uses
	// this to compute the appropriate drain grace period.
	PreemptorPriority int32 `protobuf:"varint,2,opt,name=preemptor_priority,json=preemptorPriority,proto3" json:"preemptor_priority,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrossShardDrain) Reset() {
	*x = CrossShardDrain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossShardDrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossShardDrain) ProtoMessage() {}

func (x *CrossShardDrain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossShardDrain.ProtoReflect.Descriptor instead.
func (*CrossShardDrain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *CrossShardDrain) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

func (x *CrossShardDrain) GetPreemptorPriority() int32 {
	if x != nil {
		return x.PreemptorPriority
	}
	return 0
}

// TransferOwnership reassigns a now-idle machine from one shard to another.
// The receiving shard takes responsibility for the next Configure.
type TransferOwnership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineIds    []string               `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	FromShardId   string                 `protobuf:"bytes,2,opt,name=from_shard_id,json=fromShardId,proto3" json:"from_shard_id,omitempty"`
	ToShardId     string                 `protobuf:"bytes,3,opt,name=to_shard_id,json=toShardId,proto3" json:"to_shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnership) Reset() {
	*x = TransferOwnership{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnership) ProtoMessage() {}

func (x *TransferOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnership.ProtoReflect.Descriptor instead.
func (*TransferOwnership) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *TransferOwnership) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

func (x *TransferOwnership) GetFromShardId() string {
	if x != nil {
		return x.FromShardId
	}
	return ""
}

func (x *TransferOwnership) GetToShardId() string {
	if x != nil {
		return x.ToShardId
	}
	return ""
}

type InstructAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	Outcome       InstructAck_Outcome    `protobuf:"varint,2,opt,name=outcome,proto3,enum=bigfleet.v1alpha1.InstructAck_Outcome" json:"outcome,omitempty"`
	// Populated when outcome != ACCEPTED.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructAck) Reset() {
	*x = InstructAck{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructAck) ProtoMessage() {}

func (x *InstructAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructAck.ProtoReflect.Descriptor instead.
func (*InstructAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *InstructAck) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *InstructAck) GetOutcome() InstructAck_Outcome {
	if x != nil {
		return x.Outcome
	}
	return InstructAck_OUTCOME_UNSPECIFIED
}

func (x *InstructAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_bigfleet_v1alpha1_coordinator_proto protoreflect.FileDescriptor

const file_bigfleet_v1alpha1_coordinator_proto_rawDesc = "" +
	"\n" +
	"#bigfleet/v1alpha1/coordinator.proto\x12\x11bigfleet.v1alpha1\x1a bigfleet/v1alpha1/capacity.proto\x1a bigfleet/v1alpha1/provider.proto\"\x8a\x02\n" +
	"\vShardReport\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x14\n" +
	"\x05cycle\x18\x02 \x01(\x03R\x05cycle\x120\n" +
	"\x14timestamp_unix_nanos\x18\x03 \x01(\x03R\x12timestampUnixNanos\x12\x1f\n" +
	"\vshard_epoch\x18\x04 \x01(\x03R\n" +
	"shardEpoch\x129\n" +
	"\asummary\x18\x05 \x01(\v2\x1f.bigfleet.v1alpha1.ShardSummaryR\asummary\x12<\n" +
	"\n" +
	"shortfalls\x18\x06 \x03(\v2\x1c.bigfleet.v1alpha1.ShortfallR\n" +
	"shortfalls\"\xb1\x04\n" +
	"\fShardSummary\x12%\n" +
	"\x0etotal_machines\x18\x01 \x01(\x05R\rtotalMachines\x12#\n" +
	"\rfree_machines\x18\x02 \x01(\x05R\ffreeMachines\x12s\n" +
	"\x18per_instance_type_counts\x18\x03 \x03(\v2:.bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntryR\x15perInstanceTypeCounts\x12Z\n" +
	"\x0fper_zone_counts\x18\x04 \x03(\v22.bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntryR\rperZoneCounts\x128\n" +
	"\x18utilisation_cpu_fraction\x18\x05 \x01(\x01R\x16utilisationCpuFraction\x12>\n" +
	"\x1butilisation_memory_fraction\x18\x06 \x01(\x01R\x19utilisationMemoryFraction\x1aH\n" +
	"\x1aPerInstanceTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12PerZoneCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xca\x02\n" +
	"\tShortfall\x12N\n" +
	"\frequirements\x18\x01 \x03(\v2*.bigfleet.v1alpha1.NodeSelectorRequirementR\frequirements\x12:\n" +
	"\tresources\x18\x02 \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\tresources\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"age_cycles\x18\x05 \x01(\x05R\tageCycles\x12`\n" +
	"\x1binterruption_penalty_bucket\x18\x06 \x01(\x0e2 .bigfleet.v1alpha1.PenaltyBucketR\x19interruptionPenaltyBucket\"Z\n" +
	"\tReportAck\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\"\xba\x04\n" +
	"\x16CoordinatorInstruction\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12%\n" +
	"\x0einstruction_id\x18\x03 \x01(\tR\rinstructionId\x12F\n" +
	"\rassign_domain\x18\x04 \x01(\v2\x1f.bigfleet.v1alpha1.AssignDomainH\x00R\fassignDomain\x12L\n" +
	"\x0funassign_domain\x18\x05 \x01(\v2!.bigfleet.v1alpha1.UnassignDomainH\x00R\x0eunassignDomain\x12[\n" +
	"\x14reassign_speculative\x18\x06 \x01(\v2&.bigfleet.v1alpha1.ReassignSpeculativeH\x00R\x13reassignSpeculative\x12P\n" +
	"\x11cross_shard_drain\x18\a \x01(\v2\".bigfleet.v1alpha1.CrossShardDrainH\x00R\x0fcrossShardDrain\x12U\n" +
	"\x12transfer_ownership\x18\b \x01(\v2$.bigfleet.v1alpha1.TransferOwnershipH\x00R\x11transferOwnershipB\t\n" +
	"\apayload\"X\n" +
	"\fAssignDomain\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\"Z\n" +
	"\x0eUnassignDomain\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\"6\n" +
	"\x13ReassignSpeculative\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\"a\n" +
	"\x0fCrossShardDrain\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\x12-\n" +
	"\x12preemptor_priority\x18\x02 \x01(\x05R\x11preemptorPriority\"x\n" +
	"\x11TransferOwnership\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\x12\"\n" +
	"\rfrom_shard_id\x18\x02 \x01(\tR\vfromShardId\x12\x1e\n" +
	"\vto_shard_id\x18\x03 \x01(\tR\ttoShardId\"\x97\x02\n" +
	"\vInstructAck\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12@\n" +
	"\aoutcome\x18\x02 \x01(\x0e2&.bigfleet.v1alpha1.InstructAck.OutcomeR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x86\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16OUTCOME_REJECTED_STALE\x10\x02\x12\x1c\n" +
	"\x18OUTCOME_REJECTED_INVALID\x10\x03\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x042\xb1\x01\n" +
	"\vCoordinator\x12K\n" +
	"\vReportShard\x12\x1e.bigfleet.v1alpha1.ShardReport\x1a\x1c.bigfleet.v1alpha1.ReportAck\x12U\n" +
	"\bInstruct\x12).bigfleet.v1alpha1.CoordinatorInstruction\x1a\x1e.bigfleet.v1alpha1.InstructAckB\xdd\x01\n" +
	"\x15com.bigfleet.v1alpha1B\x10CoordinatorProtoP\x01ZMgithub.com/intUnderflow/bigfleet/pkg/proto/bigfleet/v1alpha1;bigfleetv1alpha1\xa2\x02\x03BXX\xaa\x02\x11Bigfleet.V1alpha1\xca\x02\x11Bigfleet\\V1alpha1\xe2\x02\x1dBigfleet\\V1alpha1\\GPBMetadata\xea\x02\x12Bigfleet::V1alpha1b\x06proto3"

var (
	file_bigfleet_v1alpha1_coordinator_proto_rawDescOnce sync.Once
	file_bigfleet_v1alpha1_coordinator_proto_rawDescData []byte
)

func file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP() []byte {
	file_bigfleet_v1alpha1_coordinator_proto_rawDescOnce.Do(func() {
		file_bigfleet_v1alpha1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_coordinator_proto_rawDesc), len(file_bigfleet_v1alpha1_coordinator_proto_rawDesc)))
	})
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescData
}

var file_bigfleet_v1alpha1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bigfleet_v1alpha1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bigfleet_v1alpha1_coordinator_proto_goTypes = []any{
	(InstructAck_Outcome)(0),        // 0: bigfleet.v1alpha1.InstructAck.Outcome
	(*ShardReport)(nil),             // 1: bigfleet.v1alpha1.ShardReport
	(*ShardSummary)(nil),            // 2: bigfleet.v1alpha1.ShardSummary
	(*Shortfall)(nil),               // 3: bigfleet.v1alpha1.Shortfall
	(*ReportAck)(nil),               // 4: bigfleet.v1alpha1.ReportAck
	(*CoordinatorInstruction)(nil),  // 5: bigfleet.v1alpha1.CoordinatorInstruction
	(*AssignDomain)(nil),            // 6: bigfleet.v1alpha1.AssignDomain
	(*UnassignDomain)(nil),          // 7: bigfleet.v1alpha1.UnassignDomain
	(*ReassignSpeculative)(nil),     // 8: bigfleet.v1alpha1.ReassignSpeculative
	(*CrossShardDrain)(nil),         // 9: bigfleet.v1alpha1.CrossShardDrain
	(*TransferOwnership)(nil),       // 10: bigfleet.v1alpha1.TransferOwnership
	(*InstructAck)(nil),             // 11: bigfleet.v1alpha1.InstructAck
	nil,                             // 12: bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntry
	nil,                             // 13: bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntry
	(*NodeSelectorRequirement)(nil), // 14: bigfleet.v1alpha1.NodeSelectorRequirement
	(*Resources)(nil),               // 15: bigfleet.v1alpha1.Resources
	(PenaltyBucket)(0),              // 16: bigfleet.v1alpha1.PenaltyBucket
}
var file_bigfleet_v1alpha1_coordinator_proto_depIdxs = []int32{
	2,  // 0: bigfleet.v1alpha1.ShardReport.summary:type_name -> bigfleet.v1alpha1.ShardSummary
	3,  // 1: bigfleet.v1alpha1.ShardReport.shortfalls:type_name -> bigfleet.v1alpha1.Shortfall
	12, // 2: bigfleet.v1alpha1.ShardSummary.per_instance_type_counts:type_name -> bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntry
	13, // 3: bigfleet.v1alpha1.ShardSummary.per_zone_counts:type_name -> bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntry
	14, // 4: bigfleet.v1alpha1.Shortfall.requirements:type_name -> bigfleet.v1alpha1.NodeSelectorRequirement
	15, // 5: bigfleet.v1alpha1.Shortfall.resources:type_name -> bigfleet.v1alpha1.Resources
	16, // 6: bigfleet.v1alpha1.Shortfall.interruption_penalty_bucket:type_name -> bigfleet.v1alpha1.PenaltyBucket
	6,  // 7: bigfleet.v1alpha1.CoordinatorInstruction.assign_domain:type_name -> bigfleet.v1alpha1.AssignDomain
	7,  // 8: bigfleet.v1alpha1.CoordinatorInstruction.unassign_domain:type_name -> bigfleet.v1alpha1.UnassignDomain
	8,  // 9: bigfleet.v1alpha1.CoordinatorInstruction.reassign_speculative:type_name -> bigfleet.v1alpha1.ReassignSpeculative
	9,  // 10: bigfleet.v1alpha1.CoordinatorInstruction.cross_shard_drain:type_name -> bigfleet.v1alpha1.CrossShardDrain
	10, // 11: bigfleet.v1alpha1.CoordinatorInstruction.transfer_ownership:type_name -> bigfleet.v1alpha1.TransferOwnership
	0,  // 12: bigfleet.v1alpha1.InstructAck.outcome:type_name -> bigfleet.v1alpha1.InstructAck.Outcome
	1,  // 13: bigfleet.v1alpha1.Coordinator.ReportShard:input_type -> bigfleet.v1alpha1.ShardReport
	5,  // 14: bigfleet.v1alpha1.Coordinator.Instruct:input_type -> bigfleet.v1alpha1.CoordinatorInstruction
	4,  // 15: bigfleet.v1alpha1.Coordinator.ReportShard:output_type -> bigfleet.v1alpha1.ReportAck
	11, // 16: bigfleet.v1alpha1.Coordinator.Instruct:output_type -> bigfleet.v1alpha1.InstructAck
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_bigfleet_v1alpha1_coordinator_proto_init() }
func file_bigfleet_v1alpha1_coordinator_proto_init() {
	if File_bigfleet_v1alpha1_coordinator_proto != nil {
		return
	}
	file_bigfleet_v1alpha1_capacity_proto_init()
	file_bigfleet_v1alpha1_provider_proto_init()
	file_bigfleet_v1alpha1_coordinator_proto_msgTypes[4].OneofWrappers = []any{
		(*CoordinatorInstruction_AssignDomain)(nil),
		(*CoordinatorInstruction_UnassignDomain)(nil),
		(*CoordinatorInstruction_ReassignSpeculative)(nil),
		(*CoordinatorInstruction_CrossShardDrain)(nil),
		(*CoordinatorInstruction_TransferOwnership)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_coordinator_proto_rawDesc), len(file_bigfleet_v1alpha1_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigfleet_v1alpha1_coordinator_proto_goTypes,
		DependencyIndexes: file_bigfleet_v1alpha1_coordinator_proto_depIdxs,
		EnumInfos:         file_bigfleet_v1alpha1_coordinator_proto_enumTypes,
		MessageInfos:      file_bigfleet_v1alpha1_coordinator_proto_msgTypes,
	}.Build()
	File_bigfleet_v1alpha1_coordinator_proto = out.File
	file_bigfleet_v1alpha1_coordinator_proto_goTypes = nil
	file_bigfleet_v1alpha1_coordinator_proto_depIdxs = nil
}
