// Coordinator is the internal RPC surface between shards and the global
// coordinator. The coordinator does not make provisioning decisions; it
// owns shard membership, the cluster→shard map, the topology-domain→shard
// map, quota allocations, and the provider registry, and it issues
// rebalancing / cross-shard preemption instructions.
//
// Every coordinator-issued instruction carries (coordinator_term, sequence_number).
// Shards reject instructions with stale terms (zombie-leader protection).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bigfleet/v1alpha1/coordinator.proto

package bigfleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstructAck_Outcome int32

const (
	InstructAck_OUTCOME_UNSPECIFIED      InstructAck_Outcome = 0
	InstructAck_OUTCOME_ACCEPTED         InstructAck_Outcome = 1
	InstructAck_OUTCOME_REJECTED_STALE   InstructAck_Outcome = 2 // term older than shard's high-water mark
	InstructAck_OUTCOME_REJECTED_INVALID InstructAck_Outcome = 3 // semantically not applicable
	InstructAck_OUTCOME_FAILED           InstructAck_Outcome = 4
)

// Enum value maps for InstructAck_Outcome.
var (
	InstructAck_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_REJECTED_STALE",
		3: "OUTCOME_REJECTED_INVALID",
		4: "OUTCOME_FAILED",
	}
	InstructAck_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":      0,
		"OUTCOME_ACCEPTED":         1,
		"OUTCOME_REJECTED_STALE":   2,
		"OUTCOME_REJECTED_INVALID": 3,
		"OUTCOME_FAILED":           4,
	}
)

func (x InstructAck_Outcome) Enum() *InstructAck_Outcome {
	p := new(InstructAck_Outcome)
	*p = x
	return p
}

func (x InstructAck_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstructAck_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_coordinator_proto_enumTypes[0].Descriptor()
}

func (InstructAck_Outcome) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_coordinator_proto_enumTypes[0]
}

func (x InstructAck_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstructAck_Outcome.Descriptor instead.
func (InstructAck_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{25, 0}
}

type ListQuotasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotasRequest) Reset() {
	*x = ListQuotasRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotasRequest) ProtoMessage() {}

func (x *ListQuotasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotasRequest.ProtoReflect.Descriptor instead.
func (*ListQuotasRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{0}
}

type ListQuotasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocations   []*QuotaAllocation     `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotasResponse) Reset() {
	*x = ListQuotasResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotasResponse) ProtoMessage() {}

func (x *ListQuotasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotasResponse.ProtoReflect.Descriptor instead.
func (*ListQuotasResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ListQuotasResponse) GetAllocations() []*QuotaAllocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

type QuotaAllocation struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Region   string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	// per_shard maps shard_id → speculative-pool slice size.
	PerShard      map[string]int32 `protobuf:"bytes,3,rep,name=per_shard,json=perShard,proto3" json:"per_shard,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaAllocation) Reset() {
	*x = QuotaAllocation{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaAllocation) ProtoMessage() {}

func (x *QuotaAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaAllocation.ProtoReflect.Descriptor instead.
func (*QuotaAllocation) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *QuotaAllocation) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *QuotaAllocation) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *QuotaAllocation) GetPerShard() map[string]int32 {
	if x != nil {
		return x.PerShard
	}
	return nil
}

// Admin RPCs: AssignDomain pins a topology domain (rack / zone /
// region / etc.) to a specific shard. Idempotent — re-assigning a
// domain to its current shard is a no-op success; assigning to a
// *different* shard returns AlreadyExists with the current owner.
type AssignDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	ShardId       string                 `protobuf:"bytes,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDomainRequest) Reset() {
	*x = AssignDomainRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDomainRequest) ProtoMessage() {}

func (x *AssignDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDomainRequest.ProtoReflect.Descriptor instead.
func (*AssignDomainRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *AssignDomainRequest) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *AssignDomainRequest) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

func (x *AssignDomainRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type AssignDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDomainResponse) Reset() {
	*x = AssignDomainResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDomainResponse) ProtoMessage() {}

func (x *AssignDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDomainResponse.ProtoReflect.Descriptor instead.
func (*AssignDomainResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{4}
}

// UnassignDomain removes the domain from coordinator state. Idempotent
// — unassigning an already-absent domain is a no-op success.
type UnassignDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignDomainRequest) Reset() {
	*x = UnassignDomainRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignDomainRequest) ProtoMessage() {}

func (x *UnassignDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignDomainRequest.ProtoReflect.Descriptor instead.
func (*UnassignDomainRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *UnassignDomainRequest) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *UnassignDomainRequest) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

type UnassignDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignDomainResponse) Reset() {
	*x = UnassignDomainResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignDomainResponse) ProtoMessage() {}

func (x *UnassignDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignDomainResponse.ProtoReflect.Descriptor instead.
func (*UnassignDomainResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{6}
}

// RemoveShard deletes the shard's registry entry and cascades cleanup
// of any cluster / domain assignments pointing at it. Returns NotFound
// if the shard isn't registered.
type RemoveShardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveShardRequest) Reset() {
	*x = RemoveShardRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShardRequest) ProtoMessage() {}

func (x *RemoveShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShardRequest.ProtoReflect.Descriptor instead.
func (*RemoveShardRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveShardRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type RemoveShardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveShardResponse) Reset() {
	*x = RemoveShardResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveShardResponse) ProtoMessage() {}

func (x *RemoveShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveShardResponse.ProtoReflect.Descriptor instead.
func (*RemoveShardResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{8}
}

// ListShards returns the registered shard set, sorted by ID.
type ListShardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsRequest) Reset() {
	*x = ListShardsRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsRequest) ProtoMessage() {}

func (x *ListShardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsRequest.ProtoReflect.Descriptor instead.
func (*ListShardsRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{9}
}

type ListShardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shards        []*ShardRegistryEntry  `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShardsResponse) Reset() {
	*x = ListShardsResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShardsResponse) ProtoMessage() {}

func (x *ListShardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShardsResponse.ProtoReflect.Descriptor instead.
func (*ListShardsResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *ListShardsResponse) GetShards() []*ShardRegistryEntry {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ShardRegistryEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ShardId             string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Address             string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RegisteredAtUnixNs  int64                  `protobuf:"varint,3,opt,name=registered_at_unix_ns,json=registeredAtUnixNs,proto3" json:"registered_at_unix_ns,omitempty"`
	LastHeartbeatUnixNs int64                  `protobuf:"varint,4,opt,name=last_heartbeat_unix_ns,json=lastHeartbeatUnixNs,proto3" json:"last_heartbeat_unix_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShardRegistryEntry) Reset() {
	*x = ShardRegistryEntry{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardRegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardRegistryEntry) ProtoMessage() {}

func (x *ShardRegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardRegistryEntry.ProtoReflect.Descriptor instead.
func (*ShardRegistryEntry) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *ShardRegistryEntry) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardRegistryEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShardRegistryEntry) GetRegisteredAtUnixNs() int64 {
	if x != nil {
		return x.RegisteredAtUnixNs
	}
	return 0
}

func (x *ShardRegistryEntry) GetLastHeartbeatUnixNs() int64 {
	if x != nil {
		return x.LastHeartbeatUnixNs
	}
	return 0
}

// ListDomainAssignments returns the topology-domain → shard mapping.
type ListDomainAssignmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainAssignmentsRequest) Reset() {
	*x = ListDomainAssignmentsRequest{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainAssignmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainAssignmentsRequest) ProtoMessage() {}

func (x *ListDomainAssignmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainAssignmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainAssignmentsRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{12}
}

type ListDomainAssignmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*DomainAssignment    `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainAssignmentsResponse) Reset() {
	*x = ListDomainAssignmentsResponse{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainAssignmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainAssignmentsResponse) ProtoMessage() {}

func (x *ListDomainAssignmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainAssignmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainAssignmentsResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *ListDomainAssignmentsResponse) GetAssignments() []*DomainAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

type DomainAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	ShardId       string                 `protobuf:"bytes,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainAssignment) Reset() {
	*x = DomainAssignment{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainAssignment) ProtoMessage() {}

func (x *DomainAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainAssignment.ProtoReflect.Descriptor instead.
func (*DomainAssignment) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *DomainAssignment) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *DomainAssignment) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

func (x *DomainAssignment) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

// ShardReport is what each shard sends every ~30s. Stateless: the
// coordinator builds its fleet picture from the latest report per shard.
type ShardReport struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShardId string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Monotonic counter for this shard's reports. Used by the coordinator
	// to discard out-of-order delivery.
	Cycle int64 `protobuf:"varint,2,opt,name=cycle,proto3" json:"cycle,omitempty"`
	// Wall-clock time of report generation.
	TimestampUnixNanos int64 `protobuf:"varint,3,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	// Shard's epoch. Increments on shard restart. Carried so coordinator
	// logs can correlate with shard-side fencing.
	ShardEpoch int64 `protobuf:"varint,4,opt,name=shard_epoch,json=shardEpoch,proto3" json:"shard_epoch,omitempty"`
	// Aggregate inventory and demand summaries. Bounded in size; not the
	// per-machine inventory.
	Summary *ShardSummary `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	// Top-N unresolved needs, ranked by priority. Bounded to 100 per
	// §3.5 / shortfall protocol.
	Shortfalls []*Shortfall `protobuf:"bytes,6,rep,name=shortfalls,proto3" json:"shortfalls,omitempty"`
	// Acknowledgements for instructions previously delivered to this
	// shard via ReportAck.instructions. Shards include the result for
	// each instruction they've finished acting on (or rejected). The
	// coordinator uses the acks to clear the pending-instruction queue
	// and to learn outcomes (term-rejected, semantically-invalid,
	// failed). Bounded by the shard's outstanding-instruction set.
	InstructionAcks []*InstructAck `protobuf:"bytes,7,rep,name=instruction_acks,json=instructionAcks,proto3" json:"instruction_acks,omitempty"`
	// Shard's gRPC dial address as it would be reachable from operators
	// and admin tools — typically `host:port`, e.g.
	// `bigfleet-shard-2.bigfleet-shard-headless.bigfleet-system.svc:7780`.
	// Carried on every ReportShard for forward-compat: if the coordinator
	// sees an unknown shard_id, it Raft-Applies AddShard with this
	// address and accepts subsequent reports as heartbeats. Optional for
	// compat with shards that don't know their advertise address; when
	// absent, the coordinator records an empty address (the registry
	// entry is still useful for membership / domain assignment).
	ShardAddress  string `protobuf:"bytes,8,opt,name=shard_address,json=shardAddress,proto3" json:"shard_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardReport) Reset() {
	*x = ShardReport{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReport) ProtoMessage() {}

func (x *ShardReport) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReport.ProtoReflect.Descriptor instead.
func (*ShardReport) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *ShardReport) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *ShardReport) GetCycle() int64 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *ShardReport) GetTimestampUnixNanos() int64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *ShardReport) GetShardEpoch() int64 {
	if x != nil {
		return x.ShardEpoch
	}
	return 0
}

func (x *ShardReport) GetSummary() *ShardSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *ShardReport) GetShortfalls() []*Shortfall {
	if x != nil {
		return x.Shortfalls
	}
	return nil
}

func (x *ShardReport) GetInstructionAcks() []*InstructAck {
	if x != nil {
		return x.InstructionAcks
	}
	return nil
}

func (x *ShardReport) GetShardAddress() string {
	if x != nil {
		return x.ShardAddress
	}
	return ""
}

// ShardSummary is a coarse-grained snapshot of a shard's inventory and
// demand. Sized to fit alongside 200 other shard summaries in the
// coordinator's L1/L2-resident state.
type ShardSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total machines owned by the shard, in any state.
	TotalMachines int32 `protobuf:"varint,1,opt,name=total_machines,json=totalMachines,proto3" json:"total_machines,omitempty"`
	// Machines available for assignment (state == IDLE or SPECULATIVE).
	FreeMachines int32 `protobuf:"varint,2,opt,name=free_machines,json=freeMachines,proto3" json:"free_machines,omitempty"`
	// Per-instance-type counts for whichever instance types the shard
	// currently owns. Bounded by the shard's catalog (small).
	PerInstanceTypeCounts map[string]int32 `protobuf:"bytes,3,rep,name=per_instance_type_counts,json=perInstanceTypeCounts,proto3" json:"per_instance_type_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Per-zone counts. Bounded by zones the shard touches.
	PerZoneCounts map[string]int32 `protobuf:"bytes,4,rep,name=per_zone_counts,json=perZoneCounts,proto3" json:"per_zone_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Aggregate utilisation hints. Defined by the operator's reporting
	// policy; the coordinator does not interpret precise values.
	UtilisationCpuFraction    float64 `protobuf:"fixed64,5,opt,name=utilisation_cpu_fraction,json=utilisationCpuFraction,proto3" json:"utilisation_cpu_fraction,omitempty"`
	UtilisationMemoryFraction float64 `protobuf:"fixed64,6,opt,name=utilisation_memory_fraction,json=utilisationMemoryFraction,proto3" json:"utilisation_memory_fraction,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ShardSummary) Reset() {
	*x = ShardSummary{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSummary) ProtoMessage() {}

func (x *ShardSummary) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSummary.ProtoReflect.Descriptor instead.
func (*ShardSummary) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *ShardSummary) GetTotalMachines() int32 {
	if x != nil {
		return x.TotalMachines
	}
	return 0
}

func (x *ShardSummary) GetFreeMachines() int32 {
	if x != nil {
		return x.FreeMachines
	}
	return 0
}

func (x *ShardSummary) GetPerInstanceTypeCounts() map[string]int32 {
	if x != nil {
		return x.PerInstanceTypeCounts
	}
	return nil
}

func (x *ShardSummary) GetPerZoneCounts() map[string]int32 {
	if x != nil {
		return x.PerZoneCounts
	}
	return nil
}

func (x *ShardSummary) GetUtilisationCpuFraction() float64 {
	if x != nil {
		return x.UtilisationCpuFraction
	}
	return 0
}

func (x *ShardSummary) GetUtilisationMemoryFraction() float64 {
	if x != nil {
		return x.UtilisationMemoryFraction
	}
	return 0
}

// Shortfall describes a need the shard could not satisfy from its own
// inventory and could not resolve via in-shard preemption. The coordinator
// uses these to drive cross-shard rebalancing and preemption.
type Shortfall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unsatisfied profile.
	Requirements []*NodeSelectorRequirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Resources    *Resources                 `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	Priority     int32                      `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Count        int32                      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Cycles this shortfall has been unresolved. >5 escalates to fleet
	// telemetry per the shortfall protocol.
	AgeCycles int32 `protobuf:"varint,5,opt,name=age_cycles,json=ageCycles,proto3" json:"age_cycles,omitempty"`
	// Bucketed interruption penalty of the originating CapacityNeed.
	// Lets the coordinator price cross-shard preemption.
	InterruptionPenaltyBucket PenaltyBucket `protobuf:"varint,6,opt,name=interruption_penalty_bucket,json=interruptionPenaltyBucket,proto3,enum=bigfleet.v1alpha1.PenaltyBucket" json:"interruption_penalty_bucket,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Shortfall) Reset() {
	*x = Shortfall{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shortfall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shortfall) ProtoMessage() {}

func (x *Shortfall) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shortfall.ProtoReflect.Descriptor instead.
func (*Shortfall) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{17}
}

func (x *Shortfall) GetRequirements() []*NodeSelectorRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Shortfall) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Shortfall) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Shortfall) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Shortfall) GetAgeCycles() int32 {
	if x != nil {
		return x.AgeCycles
	}
	return 0
}

func (x *Shortfall) GetInterruptionPenaltyBucket() PenaltyBucket {
	if x != nil {
		return x.InterruptionPenaltyBucket
	}
	return PenaltyBucket_PENALTY_BUCKET_UNSPECIFIED
}

type ReportAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The coordinator's current term as observed at report time. The shard
	// updates its high-water mark from this so subsequent CoordinatorInstruction
	// frames can be checked against a known-good term.
	CoordinatorTerm int64 `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	Acknowledged    bool  `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Pending instructions the coordinator wants this shard to execute.
	// The shard processes each, then includes a matching InstructAck on
	// its next ReportShard call. The coordinator may include the same
	// instruction across multiple ReportAcks until it sees an ack —
	// instruction_id is stable for deduplication.
	Instructions  []*CoordinatorInstruction `protobuf:"bytes,3,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{18}
}

func (x *ReportAck) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *ReportAck) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *ReportAck) GetInstructions() []*CoordinatorInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// CoordinatorInstruction is the shard-bound action the coordinator wants
// taken. Each instruction is fenced by (term, sequence) — shards reject
// any instruction whose term is older than the highest observed.
type CoordinatorInstruction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fencing token. The shard rejects instructions whose term is less
	// than its high-water mark.
	CoordinatorTerm int64 `protobuf:"varint,1,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	SequenceNumber  int64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// Stable id for the instruction; reused across retries by the
	// coordinator so shards can deduplicate.
	InstructionId string `protobuf:"bytes,3,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CoordinatorInstruction_AssignDomain
	//	*CoordinatorInstruction_UnassignDomain
	//	*CoordinatorInstruction_ReassignSpeculative
	//	*CoordinatorInstruction_CrossShardDrain
	//	*CoordinatorInstruction_TransferOwnership
	Payload       isCoordinatorInstruction_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorInstruction) Reset() {
	*x = CoordinatorInstruction{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorInstruction) ProtoMessage() {}

func (x *CoordinatorInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorInstruction.ProtoReflect.Descriptor instead.
func (*CoordinatorInstruction) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{19}
}

func (x *CoordinatorInstruction) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *CoordinatorInstruction) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *CoordinatorInstruction) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *CoordinatorInstruction) GetPayload() isCoordinatorInstruction_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CoordinatorInstruction) GetAssignDomain() *AssignDomain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_AssignDomain); ok {
			return x.AssignDomain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetUnassignDomain() *UnassignDomain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_UnassignDomain); ok {
			return x.UnassignDomain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetReassignSpeculative() *ReassignSpeculative {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_ReassignSpeculative); ok {
			return x.ReassignSpeculative
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetCrossShardDrain() *CrossShardDrain {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_CrossShardDrain); ok {
			return x.CrossShardDrain
		}
	}
	return nil
}

func (x *CoordinatorInstruction) GetTransferOwnership() *TransferOwnership {
	if x != nil {
		if x, ok := x.Payload.(*CoordinatorInstruction_TransferOwnership); ok {
			return x.TransferOwnership
		}
	}
	return nil
}

type isCoordinatorInstruction_Payload interface {
	isCoordinatorInstruction_Payload()
}

type CoordinatorInstruction_AssignDomain struct {
	AssignDomain *AssignDomain `protobuf:"bytes,4,opt,name=assign_domain,json=assignDomain,proto3,oneof"`
}

type CoordinatorInstruction_UnassignDomain struct {
	UnassignDomain *UnassignDomain `protobuf:"bytes,5,opt,name=unassign_domain,json=unassignDomain,proto3,oneof"`
}

type CoordinatorInstruction_ReassignSpeculative struct {
	ReassignSpeculative *ReassignSpeculative `protobuf:"bytes,6,opt,name=reassign_speculative,json=reassignSpeculative,proto3,oneof"`
}

type CoordinatorInstruction_CrossShardDrain struct {
	CrossShardDrain *CrossShardDrain `protobuf:"bytes,7,opt,name=cross_shard_drain,json=crossShardDrain,proto3,oneof"`
}

type CoordinatorInstruction_TransferOwnership struct {
	TransferOwnership *TransferOwnership `protobuf:"bytes,8,opt,name=transfer_ownership,json=transferOwnership,proto3,oneof"`
}

func (*CoordinatorInstruction_AssignDomain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_UnassignDomain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_ReassignSpeculative) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_CrossShardDrain) isCoordinatorInstruction_Payload() {}

func (*CoordinatorInstruction_TransferOwnership) isCoordinatorInstruction_Payload() {}

// AssignDomain hands a topology domain to this shard. Per plan §10.1 we
// assign at topology-domain granularity (rack, zone-slice), not machine.
type AssignDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignDomain) Reset() {
	*x = AssignDomain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignDomain) ProtoMessage() {}

func (x *AssignDomain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignDomain.ProtoReflect.Descriptor instead.
func (*AssignDomain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{20}
}

func (x *AssignDomain) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *AssignDomain) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

// UnassignDomain releases a topology domain previously assigned. Used
// during shard splits / merges.
type UnassignDomain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopologyKey   string                 `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	TopologyValue string                 `protobuf:"bytes,2,opt,name=topology_value,json=topologyValue,proto3" json:"topology_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnassignDomain) Reset() {
	*x = UnassignDomain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnassignDomain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnassignDomain) ProtoMessage() {}

func (x *UnassignDomain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnassignDomain.ProtoReflect.Descriptor instead.
func (*UnassignDomain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{21}
}

func (x *UnassignDomain) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *UnassignDomain) GetTopologyValue() string {
	if x != nil {
		return x.TopologyValue
	}
	return ""
}

// ReassignSpeculative moves quota slices between shards. Pure bookkeeping
// — no real machines exist yet.
type ReassignSpeculative struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The speculative machine ids being transferred. The receiving shard
	// takes ownership; the donating shard releases.
	MachineIds    []string `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignSpeculative) Reset() {
	*x = ReassignSpeculative{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignSpeculative) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignSpeculative) ProtoMessage() {}

func (x *ReassignSpeculative) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignSpeculative.ProtoReflect.Descriptor instead.
func (*ReassignSpeculative) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{22}
}

func (x *ReassignSpeculative) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

// CrossShardDrain instructs a donor shard to drain configured machines so
// they can become idle and be transferred. The donor shard scores victims
// and emits ReclaimInstruction frames to the affected cluster operators.
type CrossShardDrain struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	MachineIds []string               `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	// Priority of the preemptor on the requesting shard. The donor uses
	// this to compute the appropriate drain grace period.
	PreemptorPriority int32 `protobuf:"varint,2,opt,name=preemptor_priority,json=preemptorPriority,proto3" json:"preemptor_priority,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrossShardDrain) Reset() {
	*x = CrossShardDrain{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossShardDrain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossShardDrain) ProtoMessage() {}

func (x *CrossShardDrain) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossShardDrain.ProtoReflect.Descriptor instead.
func (*CrossShardDrain) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{23}
}

func (x *CrossShardDrain) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

func (x *CrossShardDrain) GetPreemptorPriority() int32 {
	if x != nil {
		return x.PreemptorPriority
	}
	return 0
}

// TransferOwnership reassigns a now-idle machine from one shard to another.
// The receiving shard takes responsibility for the next Configure.
type TransferOwnership struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineIds    []string               `protobuf:"bytes,1,rep,name=machine_ids,json=machineIds,proto3" json:"machine_ids,omitempty"`
	FromShardId   string                 `protobuf:"bytes,2,opt,name=from_shard_id,json=fromShardId,proto3" json:"from_shard_id,omitempty"`
	ToShardId     string                 `protobuf:"bytes,3,opt,name=to_shard_id,json=toShardId,proto3" json:"to_shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnership) Reset() {
	*x = TransferOwnership{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnership) ProtoMessage() {}

func (x *TransferOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnership.ProtoReflect.Descriptor instead.
func (*TransferOwnership) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{24}
}

func (x *TransferOwnership) GetMachineIds() []string {
	if x != nil {
		return x.MachineIds
	}
	return nil
}

func (x *TransferOwnership) GetFromShardId() string {
	if x != nil {
		return x.FromShardId
	}
	return ""
}

func (x *TransferOwnership) GetToShardId() string {
	if x != nil {
		return x.ToShardId
	}
	return ""
}

type InstructAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	Outcome       InstructAck_Outcome    `protobuf:"varint,2,opt,name=outcome,proto3,enum=bigfleet.v1alpha1.InstructAck_Outcome" json:"outcome,omitempty"`
	// Populated when outcome != ACCEPTED.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructAck) Reset() {
	*x = InstructAck{}
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructAck) ProtoMessage() {}

func (x *InstructAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_coordinator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructAck.ProtoReflect.Descriptor instead.
func (*InstructAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{25}
}

func (x *InstructAck) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *InstructAck) GetOutcome() InstructAck_Outcome {
	if x != nil {
		return x.Outcome
	}
	return InstructAck_OUTCOME_UNSPECIFIED
}

func (x *InstructAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_bigfleet_v1alpha1_coordinator_proto protoreflect.FileDescriptor

const file_bigfleet_v1alpha1_coordinator_proto_rawDesc = "" +
	"\n" +
	"#bigfleet/v1alpha1/coordinator.proto\x12\x11bigfleet.v1alpha1\x1a bigfleet/v1alpha1/capacity.proto\x1a bigfleet/v1alpha1/provider.proto\"\x13\n" +
	"\x11ListQuotasRequest\"Z\n" +
	"\x12ListQuotasResponse\x12D\n" +
	"\vallocations\x18\x01 \x03(\v2\".bigfleet.v1alpha1.QuotaAllocationR\vallocations\"\xd1\x01\n" +
	"\x0fQuotaAllocation\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12M\n" +
	"\tper_shard\x18\x03 \x03(\v20.bigfleet.v1alpha1.QuotaAllocation.PerShardEntryR\bperShard\x1a;\n" +
	"\rPerShardEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"z\n" +
	"\x13AssignDomainRequest\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\tR\ashardId\"\x16\n" +
	"\x14AssignDomainResponse\"a\n" +
	"\x15UnassignDomainRequest\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\"\x18\n" +
	"\x16UnassignDomainResponse\"/\n" +
	"\x12RemoveShardRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"\x15\n" +
	"\x13RemoveShardResponse\"\x13\n" +
	"\x11ListShardsRequest\"S\n" +
	"\x12ListShardsResponse\x12=\n" +
	"\x06shards\x18\x01 \x03(\v2%.bigfleet.v1alpha1.ShardRegistryEntryR\x06shards\"\xb1\x01\n" +
	"\x12ShardRegistryEntry\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x121\n" +
	"\x15registered_at_unix_ns\x18\x03 \x01(\x03R\x12registeredAtUnixNs\x123\n" +
	"\x16last_heartbeat_unix_ns\x18\x04 \x01(\x03R\x13lastHeartbeatUnixNs\"\x1e\n" +
	"\x1cListDomainAssignmentsRequest\"f\n" +
	"\x1dListDomainAssignmentsResponse\x12E\n" +
	"\vassignments\x18\x01 \x03(\v2#.bigfleet.v1alpha1.DomainAssignmentR\vassignments\"w\n" +
	"\x10DomainAssignment\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\tR\ashardId\"\xfa\x02\n" +
	"\vShardReport\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\x12\x14\n" +
	"\x05cycle\x18\x02 \x01(\x03R\x05cycle\x120\n" +
	"\x14timestamp_unix_nanos\x18\x03 \x01(\x03R\x12timestampUnixNanos\x12\x1f\n" +
	"\vshard_epoch\x18\x04 \x01(\x03R\n" +
	"shardEpoch\x129\n" +
	"\asummary\x18\x05 \x01(\v2\x1f.bigfleet.v1alpha1.ShardSummaryR\asummary\x12<\n" +
	"\n" +
	"shortfalls\x18\x06 \x03(\v2\x1c.bigfleet.v1alpha1.ShortfallR\n" +
	"shortfalls\x12I\n" +
	"\x10instruction_acks\x18\a \x03(\v2\x1e.bigfleet.v1alpha1.InstructAckR\x0finstructionAcks\x12#\n" +
	"\rshard_address\x18\b \x01(\tR\fshardAddress\"\xb1\x04\n" +
	"\fShardSummary\x12%\n" +
	"\x0etotal_machines\x18\x01 \x01(\x05R\rtotalMachines\x12#\n" +
	"\rfree_machines\x18\x02 \x01(\x05R\ffreeMachines\x12s\n" +
	"\x18per_instance_type_counts\x18\x03 \x03(\v2:.bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntryR\x15perInstanceTypeCounts\x12Z\n" +
	"\x0fper_zone_counts\x18\x04 \x03(\v22.bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntryR\rperZoneCounts\x128\n" +
	"\x18utilisation_cpu_fraction\x18\x05 \x01(\x01R\x16utilisationCpuFraction\x12>\n" +
	"\x1butilisation_memory_fraction\x18\x06 \x01(\x01R\x19utilisationMemoryFraction\x1aH\n" +
	"\x1aPerInstanceTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a@\n" +
	"\x12PerZoneCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xca\x02\n" +
	"\tShortfall\x12N\n" +
	"\frequirements\x18\x01 \x03(\v2*.bigfleet.v1alpha1.NodeSelectorRequirementR\frequirements\x12:\n" +
	"\tresources\x18\x02 \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\tresources\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x1d\n" +
	"\n" +
	"age_cycles\x18\x05 \x01(\x05R\tageCycles\x12`\n" +
	"\x1binterruption_penalty_bucket\x18\x06 \x01(\x0e2 .bigfleet.v1alpha1.PenaltyBucketR\x19interruptionPenaltyBucket\"\xa9\x01\n" +
	"\tReportAck\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged\x12M\n" +
	"\finstructions\x18\x03 \x03(\v2).bigfleet.v1alpha1.CoordinatorInstructionR\finstructions\"\xba\x04\n" +
	"\x16CoordinatorInstruction\x12)\n" +
	"\x10coordinator_term\x18\x01 \x01(\x03R\x0fcoordinatorTerm\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12%\n" +
	"\x0einstruction_id\x18\x03 \x01(\tR\rinstructionId\x12F\n" +
	"\rassign_domain\x18\x04 \x01(\v2\x1f.bigfleet.v1alpha1.AssignDomainH\x00R\fassignDomain\x12L\n" +
	"\x0funassign_domain\x18\x05 \x01(\v2!.bigfleet.v1alpha1.UnassignDomainH\x00R\x0eunassignDomain\x12[\n" +
	"\x14reassign_speculative\x18\x06 \x01(\v2&.bigfleet.v1alpha1.ReassignSpeculativeH\x00R\x13reassignSpeculative\x12P\n" +
	"\x11cross_shard_drain\x18\a \x01(\v2\".bigfleet.v1alpha1.CrossShardDrainH\x00R\x0fcrossShardDrain\x12U\n" +
	"\x12transfer_ownership\x18\b \x01(\v2$.bigfleet.v1alpha1.TransferOwnershipH\x00R\x11transferOwnershipB\t\n" +
	"\apayload\"X\n" +
	"\fAssignDomain\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\"Z\n" +
	"\x0eUnassignDomain\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12%\n" +
	"\x0etopology_value\x18\x02 \x01(\tR\rtopologyValue\"6\n" +
	"\x13ReassignSpeculative\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\"a\n" +
	"\x0fCrossShardDrain\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\x12-\n" +
	"\x12preemptor_priority\x18\x02 \x01(\x05R\x11preemptorPriority\"x\n" +
	"\x11TransferOwnership\x12\x1f\n" +
	"\vmachine_ids\x18\x01 \x03(\tR\n" +
	"machineIds\x12\"\n" +
	"\rfrom_shard_id\x18\x02 \x01(\tR\vfromShardId\x12\x1e\n" +
	"\vto_shard_id\x18\x03 \x01(\tR\ttoShardId\"\x97\x02\n" +
	"\vInstructAck\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12@\n" +
	"\aoutcome\x18\x02 \x01(\x0e2&.bigfleet.v1alpha1.InstructAck.OutcomeR\aoutcome\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x86\x01\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12\x1a\n" +
	"\x16OUTCOME_REJECTED_STALE\x10\x02\x12\x1c\n" +
	"\x18OUTCOME_REJECTED_INVALID\x10\x03\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x042\xb2\x05\n" +
	"\vCoordinator\x12K\n" +
	"\vReportShard\x12\x1e.bigfleet.v1alpha1.ShardReport\x1a\x1c.bigfleet.v1alpha1.ReportAck\x12_\n" +
	"\fAssignDomain\x12&.bigfleet.v1alpha1.AssignDomainRequest\x1a'.bigfleet.v1alpha1.AssignDomainResponse\x12e\n" +
	"\x0eUnassignDomain\x12(.bigfleet.v1alpha1.UnassignDomainRequest\x1a).bigfleet.v1alpha1.UnassignDomainResponse\x12\\\n" +
	"\vRemoveShard\x12%.bigfleet.v1alpha1.RemoveShardRequest\x1a&.bigfleet.v1alpha1.RemoveShardResponse\x12Y\n" +
	"\n" +
	"ListShards\x12$.bigfleet.v1alpha1.ListShardsRequest\x1a%.bigfleet.v1alpha1.ListShardsResponse\x12z\n" +
	"\x15ListDomainAssignments\x12/.bigfleet.v1alpha1.ListDomainAssignmentsRequest\x1a0.bigfleet.v1alpha1.ListDomainAssignmentsResponse\x12Y\n" +
	"\n" +
	"ListQuotas\x12$.bigfleet.v1alpha1.ListQuotasRequest\x1a%.bigfleet.v1alpha1.ListQuotasResponseB\xdd\x01\n" +
	"\x15com.bigfleet.v1alpha1B\x10CoordinatorProtoP\x01ZMgithub.com/intUnderflow/bigfleet/pkg/proto/bigfleet/v1alpha1;bigfleetv1alpha1\xa2\x02\x03BXX\xaa\x02\x11Bigfleet.V1alpha1\xca\x02\x11Bigfleet\\V1alpha1\xe2\x02\x1dBigfleet\\V1alpha1\\GPBMetadata\xea\x02\x12Bigfleet::V1alpha1b\x06proto3"

var (
	file_bigfleet_v1alpha1_coordinator_proto_rawDescOnce sync.Once
	file_bigfleet_v1alpha1_coordinator_proto_rawDescData []byte
)

func file_bigfleet_v1alpha1_coordinator_proto_rawDescGZIP() []byte {
	file_bigfleet_v1alpha1_coordinator_proto_rawDescOnce.Do(func() {
		file_bigfleet_v1alpha1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_coordinator_proto_rawDesc), len(file_bigfleet_v1alpha1_coordinator_proto_rawDesc)))
	})
	return file_bigfleet_v1alpha1_coordinator_proto_rawDescData
}

var file_bigfleet_v1alpha1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bigfleet_v1alpha1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_bigfleet_v1alpha1_coordinator_proto_goTypes = []any{
	(InstructAck_Outcome)(0),              // 0: bigfleet.v1alpha1.InstructAck.Outcome
	(*ListQuotasRequest)(nil),             // 1: bigfleet.v1alpha1.ListQuotasRequest
	(*ListQuotasResponse)(nil),            // 2: bigfleet.v1alpha1.ListQuotasResponse
	(*QuotaAllocation)(nil),               // 3: bigfleet.v1alpha1.QuotaAllocation
	(*AssignDomainRequest)(nil),           // 4: bigfleet.v1alpha1.AssignDomainRequest
	(*AssignDomainResponse)(nil),          // 5: bigfleet.v1alpha1.AssignDomainResponse
	(*UnassignDomainRequest)(nil),         // 6: bigfleet.v1alpha1.UnassignDomainRequest
	(*UnassignDomainResponse)(nil),        // 7: bigfleet.v1alpha1.UnassignDomainResponse
	(*RemoveShardRequest)(nil),            // 8: bigfleet.v1alpha1.RemoveShardRequest
	(*RemoveShardResponse)(nil),           // 9: bigfleet.v1alpha1.RemoveShardResponse
	(*ListShardsRequest)(nil),             // 10: bigfleet.v1alpha1.ListShardsRequest
	(*ListShardsResponse)(nil),            // 11: bigfleet.v1alpha1.ListShardsResponse
	(*ShardRegistryEntry)(nil),            // 12: bigfleet.v1alpha1.ShardRegistryEntry
	(*ListDomainAssignmentsRequest)(nil),  // 13: bigfleet.v1alpha1.ListDomainAssignmentsRequest
	(*ListDomainAssignmentsResponse)(nil), // 14: bigfleet.v1alpha1.ListDomainAssignmentsResponse
	(*DomainAssignment)(nil),              // 15: bigfleet.v1alpha1.DomainAssignment
	(*ShardReport)(nil),                   // 16: bigfleet.v1alpha1.ShardReport
	(*ShardSummary)(nil),                  // 17: bigfleet.v1alpha1.ShardSummary
	(*Shortfall)(nil),                     // 18: bigfleet.v1alpha1.Shortfall
	(*ReportAck)(nil),                     // 19: bigfleet.v1alpha1.ReportAck
	(*CoordinatorInstruction)(nil),        // 20: bigfleet.v1alpha1.CoordinatorInstruction
	(*AssignDomain)(nil),                  // 21: bigfleet.v1alpha1.AssignDomain
	(*UnassignDomain)(nil),                // 22: bigfleet.v1alpha1.UnassignDomain
	(*ReassignSpeculative)(nil),           // 23: bigfleet.v1alpha1.ReassignSpeculative
	(*CrossShardDrain)(nil),               // 24: bigfleet.v1alpha1.CrossShardDrain
	(*TransferOwnership)(nil),             // 25: bigfleet.v1alpha1.TransferOwnership
	(*InstructAck)(nil),                   // 26: bigfleet.v1alpha1.InstructAck
	nil,                                   // 27: bigfleet.v1alpha1.QuotaAllocation.PerShardEntry
	nil,                                   // 28: bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntry
	nil,                                   // 29: bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntry
	(*NodeSelectorRequirement)(nil),       // 30: bigfleet.v1alpha1.NodeSelectorRequirement
	(*Resources)(nil),                     // 31: bigfleet.v1alpha1.Resources
	(PenaltyBucket)(0),                    // 32: bigfleet.v1alpha1.PenaltyBucket
}
var file_bigfleet_v1alpha1_coordinator_proto_depIdxs = []int32{
	3,  // 0: bigfleet.v1alpha1.ListQuotasResponse.allocations:type_name -> bigfleet.v1alpha1.QuotaAllocation
	27, // 1: bigfleet.v1alpha1.QuotaAllocation.per_shard:type_name -> bigfleet.v1alpha1.QuotaAllocation.PerShardEntry
	12, // 2: bigfleet.v1alpha1.ListShardsResponse.shards:type_name -> bigfleet.v1alpha1.ShardRegistryEntry
	15, // 3: bigfleet.v1alpha1.ListDomainAssignmentsResponse.assignments:type_name -> bigfleet.v1alpha1.DomainAssignment
	17, // 4: bigfleet.v1alpha1.ShardReport.summary:type_name -> bigfleet.v1alpha1.ShardSummary
	18, // 5: bigfleet.v1alpha1.ShardReport.shortfalls:type_name -> bigfleet.v1alpha1.Shortfall
	26, // 6: bigfleet.v1alpha1.ShardReport.instruction_acks:type_name -> bigfleet.v1alpha1.InstructAck
	28, // 7: bigfleet.v1alpha1.ShardSummary.per_instance_type_counts:type_name -> bigfleet.v1alpha1.ShardSummary.PerInstanceTypeCountsEntry
	29, // 8: bigfleet.v1alpha1.ShardSummary.per_zone_counts:type_name -> bigfleet.v1alpha1.ShardSummary.PerZoneCountsEntry
	30, // 9: bigfleet.v1alpha1.Shortfall.requirements:type_name -> bigfleet.v1alpha1.NodeSelectorRequirement
	31, // 10: bigfleet.v1alpha1.Shortfall.resources:type_name -> bigfleet.v1alpha1.Resources
	32, // 11: bigfleet.v1alpha1.Shortfall.interruption_penalty_bucket:type_name -> bigfleet.v1alpha1.PenaltyBucket
	20, // 12: bigfleet.v1alpha1.ReportAck.instructions:type_name -> bigfleet.v1alpha1.CoordinatorInstruction
	21, // 13: bigfleet.v1alpha1.CoordinatorInstruction.assign_domain:type_name -> bigfleet.v1alpha1.AssignDomain
	22, // 14: bigfleet.v1alpha1.CoordinatorInstruction.unassign_domain:type_name -> bigfleet.v1alpha1.UnassignDomain
	23, // 15: bigfleet.v1alpha1.CoordinatorInstruction.reassign_speculative:type_name -> bigfleet.v1alpha1.ReassignSpeculative
	24, // 16: bigfleet.v1alpha1.CoordinatorInstruction.cross_shard_drain:type_name -> bigfleet.v1alpha1.CrossShardDrain
	25, // 17: bigfleet.v1alpha1.CoordinatorInstruction.transfer_ownership:type_name -> bigfleet.v1alpha1.TransferOwnership
	0,  // 18: bigfleet.v1alpha1.InstructAck.outcome:type_name -> bigfleet.v1alpha1.InstructAck.Outcome
	16, // 19: bigfleet.v1alpha1.Coordinator.ReportShard:input_type -> bigfleet.v1alpha1.ShardReport
	4,  // 20: bigfleet.v1alpha1.Coordinator.AssignDomain:input_type -> bigfleet.v1alpha1.AssignDomainRequest
	6,  // 21: bigfleet.v1alpha1.Coordinator.UnassignDomain:input_type -> bigfleet.v1alpha1.UnassignDomainRequest
	8,  // 22: bigfleet.v1alpha1.Coordinator.RemoveShard:input_type -> bigfleet.v1alpha1.RemoveShardRequest
	10, // 23: bigfleet.v1alpha1.Coordinator.ListShards:input_type -> bigfleet.v1alpha1.ListShardsRequest
	13, // 24: bigfleet.v1alpha1.Coordinator.ListDomainAssignments:input_type -> bigfleet.v1alpha1.ListDomainAssignmentsRequest
	1,  // 25: bigfleet.v1alpha1.Coordinator.ListQuotas:input_type -> bigfleet.v1alpha1.ListQuotasRequest
	19, // 26: bigfleet.v1alpha1.Coordinator.ReportShard:output_type -> bigfleet.v1alpha1.ReportAck
	5,  // 27: bigfleet.v1alpha1.Coordinator.AssignDomain:output_type -> bigfleet.v1alpha1.AssignDomainResponse
	7,  // 28: bigfleet.v1alpha1.Coordinator.UnassignDomain:output_type -> bigfleet.v1alpha1.UnassignDomainResponse
	9,  // 29: bigfleet.v1alpha1.Coordinator.RemoveShard:output_type -> bigfleet.v1alpha1.RemoveShardResponse
	11, // 30: bigfleet.v1alpha1.Coordinator.ListShards:output_type -> bigfleet.v1alpha1.ListShardsResponse
	14, // 31: bigfleet.v1alpha1.Coordinator.ListDomainAssignments:output_type -> bigfleet.v1alpha1.ListDomainAssignmentsResponse
	2,  // 32: bigfleet.v1alpha1.Coordinator.ListQuotas:output_type -> bigfleet.v1alpha1.ListQuotasResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_bigfleet_v1alpha1_coordinator_proto_init() }
func file_bigfleet_v1alpha1_coordinator_proto_init() {
	if File_bigfleet_v1alpha1_coordinator_proto != nil {
		return
	}
	file_bigfleet_v1alpha1_capacity_proto_init()
	file_bigfleet_v1alpha1_provider_proto_init()
	file_bigfleet_v1alpha1_coordinator_proto_msgTypes[19].OneofWrappers = []any{
		(*CoordinatorInstruction_AssignDomain)(nil),
		(*CoordinatorInstruction_UnassignDomain)(nil),
		(*CoordinatorInstruction_ReassignSpeculative)(nil),
		(*CoordinatorInstruction_CrossShardDrain)(nil),
		(*CoordinatorInstruction_TransferOwnership)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_coordinator_proto_rawDesc), len(file_bigfleet_v1alpha1_coordinator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigfleet_v1alpha1_coordinator_proto_goTypes,
		DependencyIndexes: file_bigfleet_v1alpha1_coordinator_proto_depIdxs,
		EnumInfos:         file_bigfleet_v1alpha1_coordinator_proto_enumTypes,
		MessageInfos:      file_bigfleet_v1alpha1_coordinator_proto_msgTypes,
	}.Build()
	File_bigfleet_v1alpha1_coordinator_proto = out.File
	file_bigfleet_v1alpha1_coordinator_proto_goTypes = nil
	file_bigfleet_v1alpha1_coordinator_proto_depIdxs = nil
}
