// CapacityProvider is the contract every out-of-tree provider implements.
//
// Six RPCs only — Create, Configure, Drain, Delete, Get, List. All four
// lifecycle RPCs (Create/Configure/Drain/Delete) are *asynchronous*: they
// return a TransitionAck immediately and the actual transition is observed
// via state changes visible through subsequent List/Get calls. All
// lifecycle RPCs are *idempotent* on (machine_id, target_state).
//
// There is no Watch RPC. Reconciliation is List + Get only (see plan §10.6
// for why; List supports an optional `since_revision` cursor so providers
// above a documented threshold can serve incremental state efficiently).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bigfleet/v1alpha1/provider.proto

package bigfleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineState enumerates the eight states a machine can occupy. Three
// stable (Speculative, Idle, Configured), four transitional (Creating,
// Configuring, Draining, Deleting), one terminal-pending-cleanup (Failed).
type MachineState int32

const (
	MachineState_MACHINE_STATE_UNSPECIFIED MachineState = 0
	MachineState_MACHINE_STATE_SPECULATIVE MachineState = 1 // host=nil, cluster=0
	MachineState_MACHINE_STATE_CREATING    MachineState = 2 // Speculative → Idle in progress
	MachineState_MACHINE_STATE_IDLE        MachineState = 3 // host=set,  cluster=0
	MachineState_MACHINE_STATE_CONFIGURING MachineState = 4 // Idle → Configured in progress
	MachineState_MACHINE_STATE_CONFIGURED  MachineState = 5 // host=set,  cluster=set
	MachineState_MACHINE_STATE_DRAINING    MachineState = 6 // Configured → Idle in progress
	MachineState_MACHINE_STATE_DELETING    MachineState = 7 // Idle → Speculative in progress (cloud only)
	MachineState_MACHINE_STATE_FAILED      MachineState = 8 // last transition timed out; needs intervention
)

// Enum value maps for MachineState.
var (
	MachineState_name = map[int32]string{
		0: "MACHINE_STATE_UNSPECIFIED",
		1: "MACHINE_STATE_SPECULATIVE",
		2: "MACHINE_STATE_CREATING",
		3: "MACHINE_STATE_IDLE",
		4: "MACHINE_STATE_CONFIGURING",
		5: "MACHINE_STATE_CONFIGURED",
		6: "MACHINE_STATE_DRAINING",
		7: "MACHINE_STATE_DELETING",
		8: "MACHINE_STATE_FAILED",
	}
	MachineState_value = map[string]int32{
		"MACHINE_STATE_UNSPECIFIED": 0,
		"MACHINE_STATE_SPECULATIVE": 1,
		"MACHINE_STATE_CREATING":    2,
		"MACHINE_STATE_IDLE":        3,
		"MACHINE_STATE_CONFIGURING": 4,
		"MACHINE_STATE_CONFIGURED":  5,
		"MACHINE_STATE_DRAINING":    6,
		"MACHINE_STATE_DELETING":    7,
		"MACHINE_STATE_FAILED":      8,
	}
)

func (x MachineState) Enum() *MachineState {
	p := new(MachineState)
	*p = x
	return p
}

func (x MachineState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MachineState) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_provider_proto_enumTypes[0].Descriptor()
}

func (MachineState) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_provider_proto_enumTypes[0]
}

func (x MachineState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MachineState.Descriptor instead.
func (MachineState) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{0}
}

// CapacityType is the cost-of-holding category. Drives idle-hold policy
// (bare-metal: forever; reserved: forever; on-demand: minutes; spot: ~1m).
type CapacityType int32

const (
	CapacityType_CAPACITY_TYPE_UNSPECIFIED CapacityType = 0
	CapacityType_CAPACITY_TYPE_BARE_METAL  CapacityType = 1
	CapacityType_CAPACITY_TYPE_RESERVED    CapacityType = 2
	CapacityType_CAPACITY_TYPE_ON_DEMAND   CapacityType = 3
	CapacityType_CAPACITY_TYPE_SPOT        CapacityType = 4
)

// Enum value maps for CapacityType.
var (
	CapacityType_name = map[int32]string{
		0: "CAPACITY_TYPE_UNSPECIFIED",
		1: "CAPACITY_TYPE_BARE_METAL",
		2: "CAPACITY_TYPE_RESERVED",
		3: "CAPACITY_TYPE_ON_DEMAND",
		4: "CAPACITY_TYPE_SPOT",
	}
	CapacityType_value = map[string]int32{
		"CAPACITY_TYPE_UNSPECIFIED": 0,
		"CAPACITY_TYPE_BARE_METAL":  1,
		"CAPACITY_TYPE_RESERVED":    2,
		"CAPACITY_TYPE_ON_DEMAND":   3,
		"CAPACITY_TYPE_SPOT":        4,
	}
)

func (x CapacityType) Enum() *CapacityType {
	p := new(CapacityType)
	*p = x
	return p
}

func (x CapacityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapacityType) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_provider_proto_enumTypes[1].Descriptor()
}

func (CapacityType) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_provider_proto_enumTypes[1]
}

func (x CapacityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapacityType.Descriptor instead.
func (CapacityType) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{1}
}

// HostRef is the provider's identifier for a real host. Empty when the
// machine is in the SPECULATIVE state.
type HostRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // e.g. "aws-eu-west-1", "bare-metal-amsterdam"
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`           // provider-scoped ID (instance-id, serial number, …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostRef) Reset() {
	*x = HostRef{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostRef) ProtoMessage() {}

func (x *HostRef) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostRef.ProtoReflect.Descriptor instead.
func (*HostRef) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *HostRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *HostRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Resources is per-machine allocatable capacity. Map keys mirror Kubernetes
// resource names; values are quantity strings.
type Resources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     map[string]string      `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resources) Reset() {
	*x = Resources{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resources) ProtoMessage() {}

func (x *Resources) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resources.ProtoReflect.Descriptor instead.
func (*Resources) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *Resources) GetResources() map[string]string {
	if x != nil {
		return x.Resources
	}
	return nil
}

// Machine is the unit of inventory the autoscaler reasons about. Same shape
// regardless of whether the machine is a quota slot, a real but idle node,
// or a configured cluster member.
type Machine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BigFleet's internal machine identifier. Stable across the entire
	// lifecycle (a Speculative slot that becomes a real Idle host keeps the
	// same machine_id; the host_ref is the field that fills in).
	Id    string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State MachineState `protobuf:"varint,2,opt,name=state,proto3,enum=bigfleet.v1alpha1.MachineState" json:"state,omitempty"`
	// Empty when state == SPECULATIVE (or CREATING before host attaches).
	Host         *HostRef     `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	InstanceType string       `protobuf:"bytes,4,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Zone         string       `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	CapacityType CapacityType `protobuf:"varint,6,opt,name=capacity_type,json=capacityType,proto3,enum=bigfleet.v1alpha1.CapacityType" json:"capacity_type,omitempty"`
	// Per-hour price in USD. Zero for bare metal (already paid for).
	PricePerHour float64 `protobuf:"fixed64,7,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	// Hourly interruption probability, [0.0, 1.0]. Provider-declared only:
	// forecast for SPECULATIVE machines, observed for real ones. No
	// cluster-side override (per design memory).
	InterruptionProbability float64    `protobuf:"fixed64,8,opt,name=interruption_probability,json=interruptionProbability,proto3" json:"interruption_probability,omitempty"`
	Resources               *Resources `protobuf:"bytes,9,opt,name=resources,proto3" json:"resources,omitempty"`
	// Provider-supplied labels. Used by the autoscaler to satisfy node-selector
	// requirements without re-deriving them from instance_type/zone.
	Labels map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Unix-nanos when the current transitional state began. Zero if state is
	// stable. Used to detect stuck transitions.
	TransitionStartedUnixNanos int64 `protobuf:"varint,11,opt,name=transition_started_unix_nanos,json=transitionStartedUnixNanos,proto3" json:"transition_started_unix_nanos,omitempty"`
	// Populated when state == FAILED.
	LastError     string `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Machine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Machine) GetState() MachineState {
	if x != nil {
		return x.State
	}
	return MachineState_MACHINE_STATE_UNSPECIFIED
}

func (x *Machine) GetHost() *HostRef {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Machine) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *Machine) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Machine) GetCapacityType() CapacityType {
	if x != nil {
		return x.CapacityType
	}
	return CapacityType_CAPACITY_TYPE_UNSPECIFIED
}

func (x *Machine) GetPricePerHour() float64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *Machine) GetInterruptionProbability() float64 {
	if x != nil {
		return x.InterruptionProbability
	}
	return 0
}

func (x *Machine) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Machine) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Machine) GetTransitionStartedUnixNanos() int64 {
	if x != nil {
		return x.TransitionStartedUnixNanos
	}
	return 0
}

func (x *Machine) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type MachineRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineRef) Reset() {
	*x = MachineRef{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRef) ProtoMessage() {}

func (x *MachineRef) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRef.ProtoReflect.Descriptor instead.
func (*MachineRef) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *MachineRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MachineList struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Machines []*Machine             `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty"`
	// Opaque cursor. Providers that support incremental List echo a revision
	// here that the caller can pass back as ListFilter.since_revision on the
	// next call to receive only deltas. Providers below the conformance
	// threshold may leave this empty and return full state every time.
	Revision      []byte `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineList) Reset() {
	*x = MachineList{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineList) ProtoMessage() {}

func (x *MachineList) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineList.ProtoReflect.Descriptor instead.
func (*MachineList) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *MachineList) GetMachines() []*Machine {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *MachineList) GetRevision() []byte {
	if x != nil {
		return x.Revision
	}
	return nil
}

type ListFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Restrict to the listed states. Empty list = any state.
	States []MachineState `protobuf:"varint,1,rep,packed,name=states,proto3,enum=bigfleet.v1alpha1.MachineState" json:"states,omitempty"`
	// Optional zone / instance-type filters. Empty = any.
	Zone         string `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	InstanceType string `protobuf:"bytes,3,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	// Cap on returned results. Zero means no cap.
	MaxResults int32 `protobuf:"varint,4,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	// Optional opaque cursor returned by a prior MachineList.revision. When
	// set, the provider should return only machines whose state has changed
	// since the cursor was issued. Providers that don't support cursors must
	// ignore this field and return full state. See plan §0.1 C.
	SinceRevision []byte `protobuf:"bytes,5,opt,name=since_revision,json=sinceRevision,proto3" json:"since_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *ListFilter) GetStates() []MachineState {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *ListFilter) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *ListFilter) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *ListFilter) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *ListFilter) GetSinceRevision() []byte {
	if x != nil {
		return x.SinceRevision
	}
	return nil
}

// CreateRequest moves Speculative → Creating → Idle.
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The speculative machine to actuate. Must be a machine the caller
	// currently observes in MACHINE_STATE_SPECULATIVE.
	MachineId string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Optional: tags / labels to apply on creation.
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *CreateRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ConfigureRequest moves Idle → Configuring → Configured. The bootstrap
// blob is opaque to the provider (cloud: cloud-init / ignition; bare-metal:
// PXE / iPXE config). It is generated on demand by the cluster operator
// over the Shard.Session stream and forwarded by the shard.
type ConfigureRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Cluster the machine is being configured for. The provider records this
	// so subsequent Get/List responses can populate it.
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Provider-opaque bootstrap data. Applied as user-data / ignition / PXE.
	BootstrapBlob []byte `protobuf:"bytes,3,opt,name=bootstrap_blob,json=bootstrapBlob,proto3" json:"bootstrap_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigureRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ConfigureRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ConfigureRequest) GetBootstrapBlob() []byte {
	if x != nil {
		return x.BootstrapBlob
	}
	return nil
}

// DrainRequest moves Configured → Draining → Idle. The grace period bounds
// how long the kubelet's graceful shutdown is permitted to take. PDBs are
// honoured up to the grace period; beyond it, the provider may escalate
// (kubelet kill, instance shutdown).
type DrainRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MachineId string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Grace period for the kubelet's graceful node shutdown.
	GracePeriodSeconds int64 `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *DrainRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *DrainRequest) GetGracePeriodSeconds() int64 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// TransitionAck is the response from any of Create/Configure/Drain/Delete.
// Acceptance is immediate; progress is observed via state changes.
type TransitionAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Operation identifier for idempotent retry and provider-side tracking.
	// Repeated calls keyed by (machine_id, target_state) must reuse the same
	// operation_id rather than starting a new transition.
	OperationId string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Snapshot of the machine at acceptance time — typically already in the
	// corresponding transitional state (CREATING, CONFIGURING, DRAINING,
	// DELETING).
	Machine       *Machine `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionAck) Reset() {
	*x = TransitionAck{}
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionAck) ProtoMessage() {}

func (x *TransitionAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionAck.ProtoReflect.Descriptor instead.
func (*TransitionAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *TransitionAck) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *TransitionAck) GetMachine() *Machine {
	if x != nil {
		return x.Machine
	}
	return nil
}

var File_bigfleet_v1alpha1_provider_proto protoreflect.FileDescriptor

const file_bigfleet_v1alpha1_provider_proto_rawDesc = "" +
	"\n" +
	" bigfleet/v1alpha1/provider.proto\x12\x11bigfleet.v1alpha1\"7\n" +
	"\aHostRef\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\"\x94\x01\n" +
	"\tResources\x12I\n" +
	"\tresources\x18\x01 \x03(\v2+.bigfleet.v1alpha1.Resources.ResourcesEntryR\tresources\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x04\n" +
	"\aMachine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1f.bigfleet.v1alpha1.MachineStateR\x05state\x12.\n" +
	"\x04host\x18\x03 \x01(\v2\x1a.bigfleet.v1alpha1.HostRefR\x04host\x12#\n" +
	"\rinstance_type\x18\x04 \x01(\tR\finstanceType\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12D\n" +
	"\rcapacity_type\x18\x06 \x01(\x0e2\x1f.bigfleet.v1alpha1.CapacityTypeR\fcapacityType\x12$\n" +
	"\x0eprice_per_hour\x18\a \x01(\x01R\fpricePerHour\x129\n" +
	"\x18interruption_probability\x18\b \x01(\x01R\x17interruptionProbability\x12:\n" +
	"\tresources\x18\t \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\tresources\x12>\n" +
	"\x06labels\x18\n" +
	" \x03(\v2&.bigfleet.v1alpha1.Machine.LabelsEntryR\x06labels\x12A\n" +
	"\x1dtransition_started_unix_nanos\x18\v \x01(\x03R\x1atransitionStartedUnixNanos\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\n" +
	"MachineRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\vMachineList\x126\n" +
	"\bmachines\x18\x01 \x03(\v2\x1a.bigfleet.v1alpha1.MachineR\bmachines\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\fR\brevision\"\xc6\x01\n" +
	"\n" +
	"ListFilter\x127\n" +
	"\x06states\x18\x01 \x03(\x0e2\x1f.bigfleet.v1alpha1.MachineStateR\x06states\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12#\n" +
	"\rinstance_type\x18\x03 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vmax_results\x18\x04 \x01(\x05R\n" +
	"maxResults\x12%\n" +
	"\x0esince_revision\x18\x05 \x01(\fR\rsinceRevision\"\xaf\x01\n" +
	"\rCreateRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12D\n" +
	"\x06labels\x18\x02 \x03(\v2,.bigfleet.v1alpha1.CreateRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x10ConfigureRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12%\n" +
	"\x0ebootstrap_blob\x18\x03 \x01(\fR\rbootstrapBlob\"_\n" +
	"\fDrainRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x03R\x12gracePeriodSeconds\"h\n" +
	"\rTransitionAck\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x124\n" +
	"\amachine\x18\x02 \x01(\v2\x1a.bigfleet.v1alpha1.MachineR\amachine*\x8f\x02\n" +
	"\fMachineState\x12\x1d\n" +
	"\x19MACHINE_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MACHINE_STATE_SPECULATIVE\x10\x01\x12\x1a\n" +
	"\x16MACHINE_STATE_CREATING\x10\x02\x12\x16\n" +
	"\x12MACHINE_STATE_IDLE\x10\x03\x12\x1d\n" +
	"\x19MACHINE_STATE_CONFIGURING\x10\x04\x12\x1c\n" +
	"\x18MACHINE_STATE_CONFIGURED\x10\x05\x12\x1a\n" +
	"\x16MACHINE_STATE_DRAINING\x10\x06\x12\x1a\n" +
	"\x16MACHINE_STATE_DELETING\x10\a\x12\x18\n" +
	"\x14MACHINE_STATE_FAILED\x10\b*\x9c\x01\n" +
	"\fCapacityType\x12\x1d\n" +
	"\x19CAPACITY_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CAPACITY_TYPE_BARE_METAL\x10\x01\x12\x1a\n" +
	"\x16CAPACITY_TYPE_RESERVED\x10\x02\x12\x1b\n" +
	"\x17CAPACITY_TYPE_ON_DEMAND\x10\x03\x12\x16\n" +
	"\x12CAPACITY_TYPE_SPOT\x10\x042\xd4\x03\n" +
	"\x10CapacityProvider\x12L\n" +
	"\x06Create\x12 .bigfleet.v1alpha1.CreateRequest\x1a .bigfleet.v1alpha1.TransitionAck\x12R\n" +
	"\tConfigure\x12#.bigfleet.v1alpha1.ConfigureRequest\x1a .bigfleet.v1alpha1.TransitionAck\x12J\n" +
	"\x05Drain\x12\x1f.bigfleet.v1alpha1.DrainRequest\x1a .bigfleet.v1alpha1.TransitionAck\x12I\n" +
	"\x06Delete\x12\x1d.bigfleet.v1alpha1.MachineRef\x1a .bigfleet.v1alpha1.TransitionAck\x12@\n" +
	"\x03Get\x12\x1d.bigfleet.v1alpha1.MachineRef\x1a\x1a.bigfleet.v1alpha1.Machine\x12E\n" +
	"\x04List\x12\x1d.bigfleet.v1alpha1.ListFilter\x1a\x1e.bigfleet.v1alpha1.MachineListB\xda\x01\n" +
	"\x15com.bigfleet.v1alpha1B\rProviderProtoP\x01ZMgithub.com/intUnderflow/bigfleet/pkg/proto/bigfleet/v1alpha1;bigfleetv1alpha1\xa2\x02\x03BXX\xaa\x02\x11Bigfleet.V1alpha1\xca\x02\x11Bigfleet\\V1alpha1\xe2\x02\x1dBigfleet\\V1alpha1\\GPBMetadata\xea\x02\x12Bigfleet::V1alpha1b\x06proto3"

var (
	file_bigfleet_v1alpha1_provider_proto_rawDescOnce sync.Once
	file_bigfleet_v1alpha1_provider_proto_rawDescData []byte
)

func file_bigfleet_v1alpha1_provider_proto_rawDescGZIP() []byte {
	file_bigfleet_v1alpha1_provider_proto_rawDescOnce.Do(func() {
		file_bigfleet_v1alpha1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_provider_proto_rawDesc), len(file_bigfleet_v1alpha1_provider_proto_rawDesc)))
	})
	return file_bigfleet_v1alpha1_provider_proto_rawDescData
}

var file_bigfleet_v1alpha1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bigfleet_v1alpha1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_bigfleet_v1alpha1_provider_proto_goTypes = []any{
	(MachineState)(0),        // 0: bigfleet.v1alpha1.MachineState
	(CapacityType)(0),        // 1: bigfleet.v1alpha1.CapacityType
	(*HostRef)(nil),          // 2: bigfleet.v1alpha1.HostRef
	(*Resources)(nil),        // 3: bigfleet.v1alpha1.Resources
	(*Machine)(nil),          // 4: bigfleet.v1alpha1.Machine
	(*MachineRef)(nil),       // 5: bigfleet.v1alpha1.MachineRef
	(*MachineList)(nil),      // 6: bigfleet.v1alpha1.MachineList
	(*ListFilter)(nil),       // 7: bigfleet.v1alpha1.ListFilter
	(*CreateRequest)(nil),    // 8: bigfleet.v1alpha1.CreateRequest
	(*ConfigureRequest)(nil), // 9: bigfleet.v1alpha1.ConfigureRequest
	(*DrainRequest)(nil),     // 10: bigfleet.v1alpha1.DrainRequest
	(*TransitionAck)(nil),    // 11: bigfleet.v1alpha1.TransitionAck
	nil,                      // 12: bigfleet.v1alpha1.Resources.ResourcesEntry
	nil,                      // 13: bigfleet.v1alpha1.Machine.LabelsEntry
	nil,                      // 14: bigfleet.v1alpha1.CreateRequest.LabelsEntry
}
var file_bigfleet_v1alpha1_provider_proto_depIdxs = []int32{
	12, // 0: bigfleet.v1alpha1.Resources.resources:type_name -> bigfleet.v1alpha1.Resources.ResourcesEntry
	0,  // 1: bigfleet.v1alpha1.Machine.state:type_name -> bigfleet.v1alpha1.MachineState
	2,  // 2: bigfleet.v1alpha1.Machine.host:type_name -> bigfleet.v1alpha1.HostRef
	1,  // 3: bigfleet.v1alpha1.Machine.capacity_type:type_name -> bigfleet.v1alpha1.CapacityType
	3,  // 4: bigfleet.v1alpha1.Machine.resources:type_name -> bigfleet.v1alpha1.Resources
	13, // 5: bigfleet.v1alpha1.Machine.labels:type_name -> bigfleet.v1alpha1.Machine.LabelsEntry
	4,  // 6: bigfleet.v1alpha1.MachineList.machines:type_name -> bigfleet.v1alpha1.Machine
	0,  // 7: bigfleet.v1alpha1.ListFilter.states:type_name -> bigfleet.v1alpha1.MachineState
	14, // 8: bigfleet.v1alpha1.CreateRequest.labels:type_name -> bigfleet.v1alpha1.CreateRequest.LabelsEntry
	4,  // 9: bigfleet.v1alpha1.TransitionAck.machine:type_name -> bigfleet.v1alpha1.Machine
	8,  // 10: bigfleet.v1alpha1.CapacityProvider.Create:input_type -> bigfleet.v1alpha1.CreateRequest
	9,  // 11: bigfleet.v1alpha1.CapacityProvider.Configure:input_type -> bigfleet.v1alpha1.ConfigureRequest
	10, // 12: bigfleet.v1alpha1.CapacityProvider.Drain:input_type -> bigfleet.v1alpha1.DrainRequest
	5,  // 13: bigfleet.v1alpha1.CapacityProvider.Delete:input_type -> bigfleet.v1alpha1.MachineRef
	5,  // 14: bigfleet.v1alpha1.CapacityProvider.Get:input_type -> bigfleet.v1alpha1.MachineRef
	7,  // 15: bigfleet.v1alpha1.CapacityProvider.List:input_type -> bigfleet.v1alpha1.ListFilter
	11, // 16: bigfleet.v1alpha1.CapacityProvider.Create:output_type -> bigfleet.v1alpha1.TransitionAck
	11, // 17: bigfleet.v1alpha1.CapacityProvider.Configure:output_type -> bigfleet.v1alpha1.TransitionAck
	11, // 18: bigfleet.v1alpha1.CapacityProvider.Drain:output_type -> bigfleet.v1alpha1.TransitionAck
	11, // 19: bigfleet.v1alpha1.CapacityProvider.Delete:output_type -> bigfleet.v1alpha1.TransitionAck
	4,  // 20: bigfleet.v1alpha1.CapacityProvider.Get:output_type -> bigfleet.v1alpha1.Machine
	6,  // 21: bigfleet.v1alpha1.CapacityProvider.List:output_type -> bigfleet.v1alpha1.MachineList
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_bigfleet_v1alpha1_provider_proto_init() }
func file_bigfleet_v1alpha1_provider_proto_init() {
	if File_bigfleet_v1alpha1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_provider_proto_rawDesc), len(file_bigfleet_v1alpha1_provider_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigfleet_v1alpha1_provider_proto_goTypes,
		DependencyIndexes: file_bigfleet_v1alpha1_provider_proto_depIdxs,
		EnumInfos:         file_bigfleet_v1alpha1_provider_proto_enumTypes,
		MessageInfos:      file_bigfleet_v1alpha1_provider_proto_msgTypes,
	}.Build()
	File_bigfleet_v1alpha1_provider_proto = out.File
	file_bigfleet_v1alpha1_provider_proto_goTypes = nil
	file_bigfleet_v1alpha1_provider_proto_depIdxs = nil
}
