// Shard is the operator-initiated bidirectional stream that carries every
// piece of cluster ↔ shard traffic. The cluster operator dials the shard
// and holds a long-lived stream; no inbound listener is required on the
// cluster side. All multiplexing happens here:
//
//  • roll-ups (operator → shard, periodic, full-replacement)
//  • bootstrap blob requests/responses (shard pulls; operator answers)
//  • reclaim instructions (shard → operator) and acks
//  • node state and available-capacity updates (shard → operator)
//
// Coalescing messages (NodeStateUpdate, AvailableCapacityUpdate) carry an
// explicit `supersedes_key`. The shard's outbox is permitted to drop an
// older queued frame when a newer one with the same key arrives. The
// operator applies frames in arrival order.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bigfleet/v1alpha1/shard.proto

package bigfleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailableCapacityUpdate_Confidence int32

const (
	AvailableCapacityUpdate_CONFIDENCE_UNSPECIFIED AvailableCapacityUpdate_Confidence = 0
	AvailableCapacityUpdate_CONFIDENCE_NONE        AvailableCapacityUpdate_Confidence = 1
	AvailableCapacityUpdate_CONFIDENCE_LOW         AvailableCapacityUpdate_Confidence = 2
	AvailableCapacityUpdate_CONFIDENCE_MEDIUM      AvailableCapacityUpdate_Confidence = 3
	AvailableCapacityUpdate_CONFIDENCE_HIGH        AvailableCapacityUpdate_Confidence = 4
)

// Enum value maps for AvailableCapacityUpdate_Confidence.
var (
	AvailableCapacityUpdate_Confidence_name = map[int32]string{
		0: "CONFIDENCE_UNSPECIFIED",
		1: "CONFIDENCE_NONE",
		2: "CONFIDENCE_LOW",
		3: "CONFIDENCE_MEDIUM",
		4: "CONFIDENCE_HIGH",
	}
	AvailableCapacityUpdate_Confidence_value = map[string]int32{
		"CONFIDENCE_UNSPECIFIED": 0,
		"CONFIDENCE_NONE":        1,
		"CONFIDENCE_LOW":         2,
		"CONFIDENCE_MEDIUM":      3,
		"CONFIDENCE_HIGH":        4,
	}
)

func (x AvailableCapacityUpdate_Confidence) Enum() *AvailableCapacityUpdate_Confidence {
	p := new(AvailableCapacityUpdate_Confidence)
	*p = x
	return p
}

func (x AvailableCapacityUpdate_Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailableCapacityUpdate_Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_shard_proto_enumTypes[0].Descriptor()
}

func (AvailableCapacityUpdate_Confidence) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_shard_proto_enumTypes[0]
}

func (x AvailableCapacityUpdate_Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailableCapacityUpdate_Confidence.Descriptor instead.
func (AvailableCapacityUpdate_Confidence) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{10, 0}
}

// OperatorMessage is anything the operator sends up the stream.
type OperatorMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*OperatorMessage_Hello
	//	*OperatorMessage_Rollup
	//	*OperatorMessage_BootstrapResponse
	//	*OperatorMessage_ReclaimAck
	Payload       isOperatorMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperatorMessage) Reset() {
	*x = OperatorMessage{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorMessage) ProtoMessage() {}

func (x *OperatorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorMessage.ProtoReflect.Descriptor instead.
func (*OperatorMessage) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{0}
}

func (x *OperatorMessage) GetPayload() isOperatorMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OperatorMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*OperatorMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *OperatorMessage) GetRollup() *ClusterCapacityNeeds {
	if x != nil {
		if x, ok := x.Payload.(*OperatorMessage_Rollup); ok {
			return x.Rollup
		}
	}
	return nil
}

func (x *OperatorMessage) GetBootstrapResponse() *BootstrapBlobResponse {
	if x != nil {
		if x, ok := x.Payload.(*OperatorMessage_BootstrapResponse); ok {
			return x.BootstrapResponse
		}
	}
	return nil
}

func (x *OperatorMessage) GetReclaimAck() *ReclaimAck {
	if x != nil {
		if x, ok := x.Payload.(*OperatorMessage_ReclaimAck); ok {
			return x.ReclaimAck
		}
	}
	return nil
}

type isOperatorMessage_Payload interface {
	isOperatorMessage_Payload()
}

type OperatorMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type OperatorMessage_Rollup struct {
	Rollup *ClusterCapacityNeeds `protobuf:"bytes,2,opt,name=rollup,proto3,oneof"`
}

type OperatorMessage_BootstrapResponse struct {
	BootstrapResponse *BootstrapBlobResponse `protobuf:"bytes,3,opt,name=bootstrap_response,json=bootstrapResponse,proto3,oneof"`
}

type OperatorMessage_ReclaimAck struct {
	ReclaimAck *ReclaimAck `protobuf:"bytes,4,opt,name=reclaim_ack,json=reclaimAck,proto3,oneof"`
}

func (*OperatorMessage_Hello) isOperatorMessage_Payload() {}

func (*OperatorMessage_Rollup) isOperatorMessage_Payload() {}

func (*OperatorMessage_BootstrapResponse) isOperatorMessage_Payload() {}

func (*OperatorMessage_ReclaimAck) isOperatorMessage_Payload() {}

// ShardMessage is anything the shard sends down the stream.
type ShardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ShardMessage_Ack
	//	*ShardMessage_BootstrapRequest
	//	*ShardMessage_ReclaimInstruction
	//	*ShardMessage_NodeStateUpdate
	//	*ShardMessage_AvailableCapacity
	Payload       isShardMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardMessage) Reset() {
	*x = ShardMessage{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMessage) ProtoMessage() {}

func (x *ShardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMessage.ProtoReflect.Descriptor instead.
func (*ShardMessage) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{1}
}

func (x *ShardMessage) GetPayload() isShardMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ShardMessage) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*ShardMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ShardMessage) GetBootstrapRequest() *BootstrapRequest {
	if x != nil {
		if x, ok := x.Payload.(*ShardMessage_BootstrapRequest); ok {
			return x.BootstrapRequest
		}
	}
	return nil
}

func (x *ShardMessage) GetReclaimInstruction() *ReclaimInstruction {
	if x != nil {
		if x, ok := x.Payload.(*ShardMessage_ReclaimInstruction); ok {
			return x.ReclaimInstruction
		}
	}
	return nil
}

func (x *ShardMessage) GetNodeStateUpdate() *NodeStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ShardMessage_NodeStateUpdate); ok {
			return x.NodeStateUpdate
		}
	}
	return nil
}

func (x *ShardMessage) GetAvailableCapacity() *AvailableCapacityUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ShardMessage_AvailableCapacity); ok {
			return x.AvailableCapacity
		}
	}
	return nil
}

type isShardMessage_Payload interface {
	isShardMessage_Payload()
}

type ShardMessage_Ack struct {
	Ack *Acknowledgement `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type ShardMessage_BootstrapRequest struct {
	BootstrapRequest *BootstrapRequest `protobuf:"bytes,2,opt,name=bootstrap_request,json=bootstrapRequest,proto3,oneof"`
}

type ShardMessage_ReclaimInstruction struct {
	ReclaimInstruction *ReclaimInstruction `protobuf:"bytes,3,opt,name=reclaim_instruction,json=reclaimInstruction,proto3,oneof"`
}

type ShardMessage_NodeStateUpdate struct {
	NodeStateUpdate *NodeStateUpdate `protobuf:"bytes,4,opt,name=node_state_update,json=nodeStateUpdate,proto3,oneof"`
}

type ShardMessage_AvailableCapacity struct {
	AvailableCapacity *AvailableCapacityUpdate `protobuf:"bytes,5,opt,name=available_capacity,json=availableCapacity,proto3,oneof"`
}

func (*ShardMessage_Ack) isShardMessage_Payload() {}

func (*ShardMessage_BootstrapRequest) isShardMessage_Payload() {}

func (*ShardMessage_ReclaimInstruction) isShardMessage_Payload() {}

func (*ShardMessage_NodeStateUpdate) isShardMessage_Payload() {}

func (*ShardMessage_AvailableCapacity) isShardMessage_Payload() {}

// Hello is the first frame the operator sends. Carries identity and
// capability negotiation.
type Hello struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ClusterId string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Operator's view of the protocol version it speaks.
	ProtocolVersion string `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

type Acknowledgement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of the request kind the shard is acknowledging — useful for
	// operators that want to confirm a roll-up was processed before
	// garbage-collecting local state.
	Echo string `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	// Coordinator term and the shard's epoch at the time of ack. Operators
	// do not act on these but logging them helps when reasoning about
	// multi-shard / multi-coordinator state in incident review.
	CoordinatorTerm int64 `protobuf:"varint,2,opt,name=coordinator_term,json=coordinatorTerm,proto3" json:"coordinator_term,omitempty"`
	ShardEpoch      int64 `protobuf:"varint,3,opt,name=shard_epoch,json=shardEpoch,proto3" json:"shard_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{3}
}

func (x *Acknowledgement) GetEcho() string {
	if x != nil {
		return x.Echo
	}
	return ""
}

func (x *Acknowledgement) GetCoordinatorTerm() int64 {
	if x != nil {
		return x.CoordinatorTerm
	}
	return 0
}

func (x *Acknowledgement) GetShardEpoch() int64 {
	if x != nil {
		return x.ShardEpoch
	}
	return 0
}

// BootstrapRequest is the shard pulling a kubelet bootstrap blob from the
// operator. The operator's BootstrapBlobResponse must echo `request_id`.
type BootstrapRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Requirements the bootstrapped node must satisfy (kubelet version,
	// feature gates, labels, …). The operator translates these into
	// kubelet flags / labels when generating the blob.
	Requirements []*NodeSelectorRequirement `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	// Cluster-side context for telemetry and operator-side template
	// selection. Always echoes the cluster_id from Hello.
	ClusterId     string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapRequest) Reset() {
	*x = BootstrapRequest{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapRequest) ProtoMessage() {}

func (x *BootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapRequest.ProtoReflect.Descriptor instead.
func (*BootstrapRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{4}
}

func (x *BootstrapRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BootstrapRequest) GetRequirements() []*NodeSelectorRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *BootstrapRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type BootstrapBlobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlation with the originating BootstrapRequest.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Provider-opaque blob. Forwarded as-is to CapacityProvider.Configure.
	UserData []byte `protobuf:"bytes,2,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	// Bootstrap token / kubeconfig credential lifetime. The shard must apply
	// this blob before ttl_seconds elapses, or pull a fresh one.
	TtlSeconds int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	// Populated when the cluster cannot satisfy the requirements (e.g.,
	// requested kubelet version is outside the apiserver's skew window).
	// The shard treats a non-empty error as an unsatisfiable requirement
	// and emits a shortfall.
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapBlobResponse) Reset() {
	*x = BootstrapBlobResponse{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapBlobResponse) ProtoMessage() {}

func (x *BootstrapBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapBlobResponse.ProtoReflect.Descriptor instead.
func (*BootstrapBlobResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{5}
}

func (x *BootstrapBlobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BootstrapBlobResponse) GetUserData() []byte {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *BootstrapBlobResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *BootstrapBlobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ReclaimInstruction tells the operator to drain specific nodes with a
// supplied grace period. The grace scales with the priority gap between
// the preemptor and the victim (10s / 30s / 2m / 10m).
type ReclaimInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Node names (Kubernetes node names) to drain.
	Nodes []string `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Grace period the operator must pass to the kubelet's graceful node
	// shutdown. PDBs are honoured up to this bound.
	GracePeriodSeconds int64 `protobuf:"varint,3,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	// For observability only — the priority of the workload that triggered
	// the reclaim. Operators may surface this in events / logs.
	PreemptorPriority int32 `protobuf:"varint,4,opt,name=preemptor_priority,json=preemptorPriority,proto3" json:"preemptor_priority,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReclaimInstruction) Reset() {
	*x = ReclaimInstruction{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimInstruction) ProtoMessage() {}

func (x *ReclaimInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimInstruction.ProtoReflect.Descriptor instead.
func (*ReclaimInstruction) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{6}
}

func (x *ReclaimInstruction) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *ReclaimInstruction) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ReclaimInstruction) GetGracePeriodSeconds() int64 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

func (x *ReclaimInstruction) GetPreemptorPriority() int32 {
	if x != nil {
		return x.PreemptorPriority
	}
	return 0
}

type ReclaimAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstructionId string                 `protobuf:"bytes,1,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	// Number of nodes the operator has begun to drain. Equal to the count
	// in the instruction unless some nodes have already gone away locally.
	NodesStarted  int32 `protobuf:"varint,2,opt,name=nodes_started,json=nodesStarted,proto3" json:"nodes_started,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReclaimAck) Reset() {
	*x = ReclaimAck{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReclaimAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReclaimAck) ProtoMessage() {}

func (x *ReclaimAck) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReclaimAck.ProtoReflect.Descriptor instead.
func (*ReclaimAck) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{7}
}

func (x *ReclaimAck) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *ReclaimAck) GetNodesStarted() int32 {
	if x != nil {
		return x.NodesStarted
	}
	return 0
}

// NodeStateUpdate drives UpcomingNode CR phase transitions. Coalescing:
// receivers may drop any queued frame whose supersedes_key matches a
// later frame's. The operator applies frames in arrival order.
type NodeStateUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Coalescing key. Conventionally "node:<machine_id>". The shard's
	// outbox is permitted to drop older frames with the same key.
	SupersedesKey string `protobuf:"bytes,1,opt,name=supersedes_key,json=supersedesKey,proto3" json:"supersedes_key,omitempty"`
	// BigFleet machine_id (stable across speculative → idle → configured).
	MachineId string `protobuf:"bytes,2,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// Cluster the node is bound to (or being bound to).
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Current state of the underlying machine. Operators map this to the
	// UpcomingNode CRD phase.
	State MachineState `protobuf:"varint,4,opt,name=state,proto3,enum=bigfleet.v1alpha1.MachineState" json:"state,omitempty"`
	// Set once the kubelet registers and the provider's view of the host
	// includes a node name.
	NodeName string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Optional provider ID (e.g., "aws:///us-east-1a/i-…") that callers
	// may surface in UpcomingNode.status for debugging.
	ProviderId string `protobuf:"bytes,6,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	// Populated when state == FAILED.
	LastError string `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Node identity the shard is bringing online. Operators copy these into
	// UpcomingNode.Spec so observers (kubectl, the bigfleet-scaletest-pod-shim,
	// any controller that wants to pre-allocate against an upcoming node)
	// know the shape of the node before it joins. All three are
	// present-but-empty when the shard hasn't yet decided (e.g. for
	// SPECULATIVE machines mid-flight) and stable once a host has been
	// bound.
	Labels        map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources     *Resources        `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	Taints        []*Taint          `protobuf:"bytes,11,rep,name=taints,proto3" json:"taints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStateUpdate) Reset() {
	*x = NodeStateUpdate{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStateUpdate) ProtoMessage() {}

func (x *NodeStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStateUpdate.ProtoReflect.Descriptor instead.
func (*NodeStateUpdate) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{8}
}

func (x *NodeStateUpdate) GetSupersedesKey() string {
	if x != nil {
		return x.SupersedesKey
	}
	return ""
}

func (x *NodeStateUpdate) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeStateUpdate) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeStateUpdate) GetState() MachineState {
	if x != nil {
		return x.State
	}
	return MachineState_MACHINE_STATE_UNSPECIFIED
}

func (x *NodeStateUpdate) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeStateUpdate) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *NodeStateUpdate) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *NodeStateUpdate) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeStateUpdate) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *NodeStateUpdate) GetTaints() []*Taint {
	if x != nil {
		return x.Taints
	}
	return nil
}

// Taint mirrors the Kubernetes Taint shape so an operator can copy it
// straight into UpcomingNode.Spec.Taints (and hence into the eventual
// Node).
type Taint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Effect        string                 `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"` // "NoSchedule" | "PreferNoSchedule" | "NoExecute"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taint) Reset() {
	*x = Taint{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taint) ProtoMessage() {}

func (x *Taint) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taint.ProtoReflect.Descriptor instead.
func (*Taint) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{9}
}

func (x *Taint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Taint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Taint) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

// AvailableCapacityUpdate is a hint about what capacity the shard could
// procure. Eventually consistent, advisory only. Operators write this
// through to AvailableCapacity CRDs.
type AvailableCapacityUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Coalescing key. Conventionally "available:<profile-hash>".
	SupersedesKey string `protobuf:"bytes,1,opt,name=supersedes_key,json=supersedesKey,proto3" json:"supersedes_key,omitempty"`
	// Machine profile this hint refers to.
	Requirements []*NodeSelectorRequirement `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Resources    *Resources                 `protobuf:"bytes,3,opt,name=resources,proto3" json:"resources,omitempty"`
	// How many machines of this profile the shard could provide soon.
	AvailableCount int32                              `protobuf:"varint,4,opt,name=available_count,json=availableCount,proto3" json:"available_count,omitempty"`
	Confidence     AvailableCapacityUpdate_Confidence `protobuf:"varint,5,opt,name=confidence,proto3,enum=bigfleet.v1alpha1.AvailableCapacityUpdate_Confidence" json:"confidence,omitempty"`
	// Per-hour cost the shard expects to pay if it draws on this capacity.
	CostPerHour   float64 `protobuf:"fixed64,6,opt,name=cost_per_hour,json=costPerHour,proto3" json:"cost_per_hour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailableCapacityUpdate) Reset() {
	*x = AvailableCapacityUpdate{}
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableCapacityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableCapacityUpdate) ProtoMessage() {}

func (x *AvailableCapacityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableCapacityUpdate.ProtoReflect.Descriptor instead.
func (*AvailableCapacityUpdate) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shard_proto_rawDescGZIP(), []int{10}
}

func (x *AvailableCapacityUpdate) GetSupersedesKey() string {
	if x != nil {
		return x.SupersedesKey
	}
	return ""
}

func (x *AvailableCapacityUpdate) GetRequirements() []*NodeSelectorRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *AvailableCapacityUpdate) GetResources() *Resources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AvailableCapacityUpdate) GetAvailableCount() int32 {
	if x != nil {
		return x.AvailableCount
	}
	return 0
}

func (x *AvailableCapacityUpdate) GetConfidence() AvailableCapacityUpdate_Confidence {
	if x != nil {
		return x.Confidence
	}
	return AvailableCapacityUpdate_CONFIDENCE_UNSPECIFIED
}

func (x *AvailableCapacityUpdate) GetCostPerHour() float64 {
	if x != nil {
		return x.CostPerHour
	}
	return 0
}

var File_bigfleet_v1alpha1_shard_proto protoreflect.FileDescriptor

const file_bigfleet_v1alpha1_shard_proto_rawDesc = "" +
	"\n" +
	"\x1dbigfleet/v1alpha1/shard.proto\x12\x11bigfleet.v1alpha1\x1a bigfleet/v1alpha1/capacity.proto\x1a bigfleet/v1alpha1/provider.proto\"\xae\x02\n" +
	"\x0fOperatorMessage\x120\n" +
	"\x05hello\x18\x01 \x01(\v2\x18.bigfleet.v1alpha1.HelloH\x00R\x05hello\x12A\n" +
	"\x06rollup\x18\x02 \x01(\v2'.bigfleet.v1alpha1.ClusterCapacityNeedsH\x00R\x06rollup\x12Y\n" +
	"\x12bootstrap_response\x18\x03 \x01(\v2(.bigfleet.v1alpha1.BootstrapBlobResponseH\x00R\x11bootstrapResponse\x12@\n" +
	"\vreclaim_ack\x18\x04 \x01(\v2\x1d.bigfleet.v1alpha1.ReclaimAckH\x00R\n" +
	"reclaimAckB\t\n" +
	"\apayload\"\xae\x03\n" +
	"\fShardMessage\x126\n" +
	"\x03ack\x18\x01 \x01(\v2\".bigfleet.v1alpha1.AcknowledgementH\x00R\x03ack\x12R\n" +
	"\x11bootstrap_request\x18\x02 \x01(\v2#.bigfleet.v1alpha1.BootstrapRequestH\x00R\x10bootstrapRequest\x12X\n" +
	"\x13reclaim_instruction\x18\x03 \x01(\v2%.bigfleet.v1alpha1.ReclaimInstructionH\x00R\x12reclaimInstruction\x12P\n" +
	"\x11node_state_update\x18\x04 \x01(\v2\".bigfleet.v1alpha1.NodeStateUpdateH\x00R\x0fnodeStateUpdate\x12[\n" +
	"\x12available_capacity\x18\x05 \x01(\v2*.bigfleet.v1alpha1.AvailableCapacityUpdateH\x00R\x11availableCapacityB\t\n" +
	"\apayload\"W\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersionJ\x04\b\x02\x10\x03\"q\n" +
	"\x0fAcknowledgement\x12\x12\n" +
	"\x04echo\x18\x01 \x01(\tR\x04echo\x12)\n" +
	"\x10coordinator_term\x18\x02 \x01(\x03R\x0fcoordinatorTerm\x12\x1f\n" +
	"\vshard_epoch\x18\x03 \x01(\x03R\n" +
	"shardEpoch\"\xa0\x01\n" +
	"\x10BootstrapRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12N\n" +
	"\frequirements\x18\x02 \x03(\v2*.bigfleet.v1alpha1.NodeSelectorRequirementR\frequirements\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\"\x8a\x01\n" +
	"\x15BootstrapBlobResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tuser_data\x18\x02 \x01(\fR\buserData\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xb2\x01\n" +
	"\x12ReclaimInstruction\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x120\n" +
	"\x14grace_period_seconds\x18\x03 \x01(\x03R\x12gracePeriodSeconds\x12-\n" +
	"\x12preemptor_priority\x18\x04 \x01(\x05R\x11preemptorPriority\"X\n" +
	"\n" +
	"ReclaimAck\x12%\n" +
	"\x0einstruction_id\x18\x01 \x01(\tR\rinstructionId\x12#\n" +
	"\rnodes_started\x18\x02 \x01(\x05R\fnodesStarted\"\x81\x04\n" +
	"\x0fNodeStateUpdate\x12%\n" +
	"\x0esupersedes_key\x18\x01 \x01(\tR\rsupersedesKey\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x02 \x01(\tR\tmachineId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x125\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1f.bigfleet.v1alpha1.MachineStateR\x05state\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12\x1f\n" +
	"\vprovider_id\x18\x06 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x12F\n" +
	"\x06labels\x18\t \x03(\v2..bigfleet.v1alpha1.NodeStateUpdate.LabelsEntryR\x06labels\x12:\n" +
	"\tresources\x18\n" +
	" \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\tresources\x120\n" +
	"\x06taints\x18\v \x03(\v2\x18.bigfleet.v1alpha1.TaintR\x06taints\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\a\x10\b\"G\n" +
	"\x05Taint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\"\x81\x04\n" +
	"\x17AvailableCapacityUpdate\x12%\n" +
	"\x0esupersedes_key\x18\x01 \x01(\tR\rsupersedesKey\x12N\n" +
	"\frequirements\x18\x02 \x03(\v2*.bigfleet.v1alpha1.NodeSelectorRequirementR\frequirements\x12:\n" +
	"\tresources\x18\x03 \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\tresources\x12'\n" +
	"\x0favailable_count\x18\x04 \x01(\x05R\x0eavailableCount\x12U\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x0e25.bigfleet.v1alpha1.AvailableCapacityUpdate.ConfidenceR\n" +
	"confidence\x12\"\n" +
	"\rcost_per_hour\x18\x06 \x01(\x01R\vcostPerHour\"}\n" +
	"\n" +
	"Confidence\x12\x1a\n" +
	"\x16CONFIDENCE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCONFIDENCE_NONE\x10\x01\x12\x12\n" +
	"\x0eCONFIDENCE_LOW\x10\x02\x12\x15\n" +
	"\x11CONFIDENCE_MEDIUM\x10\x03\x12\x13\n" +
	"\x0fCONFIDENCE_HIGH\x10\x04J\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"2[\n" +
	"\x05Shard\x12R\n" +
	"\aSession\x12\".bigfleet.v1alpha1.OperatorMessage\x1a\x1f.bigfleet.v1alpha1.ShardMessage(\x010\x01B\xd7\x01\n" +
	"\x15com.bigfleet.v1alpha1B\n" +
	"ShardProtoP\x01ZMgithub.com/intUnderflow/bigfleet/pkg/proto/bigfleet/v1alpha1;bigfleetv1alpha1\xa2\x02\x03BXX\xaa\x02\x11Bigfleet.V1alpha1\xca\x02\x11Bigfleet\\V1alpha1\xe2\x02\x1dBigfleet\\V1alpha1\\GPBMetadata\xea\x02\x12Bigfleet::V1alpha1b\x06proto3"

var (
	file_bigfleet_v1alpha1_shard_proto_rawDescOnce sync.Once
	file_bigfleet_v1alpha1_shard_proto_rawDescData []byte
)

func file_bigfleet_v1alpha1_shard_proto_rawDescGZIP() []byte {
	file_bigfleet_v1alpha1_shard_proto_rawDescOnce.Do(func() {
		file_bigfleet_v1alpha1_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_shard_proto_rawDesc), len(file_bigfleet_v1alpha1_shard_proto_rawDesc)))
	})
	return file_bigfleet_v1alpha1_shard_proto_rawDescData
}

var file_bigfleet_v1alpha1_shard_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bigfleet_v1alpha1_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_bigfleet_v1alpha1_shard_proto_goTypes = []any{
	(AvailableCapacityUpdate_Confidence)(0), // 0: bigfleet.v1alpha1.AvailableCapacityUpdate.Confidence
	(*OperatorMessage)(nil),                 // 1: bigfleet.v1alpha1.OperatorMessage
	(*ShardMessage)(nil),                    // 2: bigfleet.v1alpha1.ShardMessage
	(*Hello)(nil),                           // 3: bigfleet.v1alpha1.Hello
	(*Acknowledgement)(nil),                 // 4: bigfleet.v1alpha1.Acknowledgement
	(*BootstrapRequest)(nil),                // 5: bigfleet.v1alpha1.BootstrapRequest
	(*BootstrapBlobResponse)(nil),           // 6: bigfleet.v1alpha1.BootstrapBlobResponse
	(*ReclaimInstruction)(nil),              // 7: bigfleet.v1alpha1.ReclaimInstruction
	(*ReclaimAck)(nil),                      // 8: bigfleet.v1alpha1.ReclaimAck
	(*NodeStateUpdate)(nil),                 // 9: bigfleet.v1alpha1.NodeStateUpdate
	(*Taint)(nil),                           // 10: bigfleet.v1alpha1.Taint
	(*AvailableCapacityUpdate)(nil),         // 11: bigfleet.v1alpha1.AvailableCapacityUpdate
	nil,                                     // 12: bigfleet.v1alpha1.NodeStateUpdate.LabelsEntry
	(*ClusterCapacityNeeds)(nil),            // 13: bigfleet.v1alpha1.ClusterCapacityNeeds
	(*NodeSelectorRequirement)(nil),         // 14: bigfleet.v1alpha1.NodeSelectorRequirement
	(MachineState)(0),                       // 15: bigfleet.v1alpha1.MachineState
	(*Resources)(nil),                       // 16: bigfleet.v1alpha1.Resources
}
var file_bigfleet_v1alpha1_shard_proto_depIdxs = []int32{
	3,  // 0: bigfleet.v1alpha1.OperatorMessage.hello:type_name -> bigfleet.v1alpha1.Hello
	13, // 1: bigfleet.v1alpha1.OperatorMessage.rollup:type_name -> bigfleet.v1alpha1.ClusterCapacityNeeds
	6,  // 2: bigfleet.v1alpha1.OperatorMessage.bootstrap_response:type_name -> bigfleet.v1alpha1.BootstrapBlobResponse
	8,  // 3: bigfleet.v1alpha1.OperatorMessage.reclaim_ack:type_name -> bigfleet.v1alpha1.ReclaimAck
	4,  // 4: bigfleet.v1alpha1.ShardMessage.ack:type_name -> bigfleet.v1alpha1.Acknowledgement
	5,  // 5: bigfleet.v1alpha1.ShardMessage.bootstrap_request:type_name -> bigfleet.v1alpha1.BootstrapRequest
	7,  // 6: bigfleet.v1alpha1.ShardMessage.reclaim_instruction:type_name -> bigfleet.v1alpha1.ReclaimInstruction
	9,  // 7: bigfleet.v1alpha1.ShardMessage.node_state_update:type_name -> bigfleet.v1alpha1.NodeStateUpdate
	11, // 8: bigfleet.v1alpha1.ShardMessage.available_capacity:type_name -> bigfleet.v1alpha1.AvailableCapacityUpdate
	14, // 9: bigfleet.v1alpha1.BootstrapRequest.requirements:type_name -> bigfleet.v1alpha1.NodeSelectorRequirement
	15, // 10: bigfleet.v1alpha1.NodeStateUpdate.state:type_name -> bigfleet.v1alpha1.MachineState
	12, // 11: bigfleet.v1alpha1.NodeStateUpdate.labels:type_name -> bigfleet.v1alpha1.NodeStateUpdate.LabelsEntry
	16, // 12: bigfleet.v1alpha1.NodeStateUpdate.resources:type_name -> bigfleet.v1alpha1.Resources
	10, // 13: bigfleet.v1alpha1.NodeStateUpdate.taints:type_name -> bigfleet.v1alpha1.Taint
	14, // 14: bigfleet.v1alpha1.AvailableCapacityUpdate.requirements:type_name -> bigfleet.v1alpha1.NodeSelectorRequirement
	16, // 15: bigfleet.v1alpha1.AvailableCapacityUpdate.resources:type_name -> bigfleet.v1alpha1.Resources
	0,  // 16: bigfleet.v1alpha1.AvailableCapacityUpdate.confidence:type_name -> bigfleet.v1alpha1.AvailableCapacityUpdate.Confidence
	1,  // 17: bigfleet.v1alpha1.Shard.Session:input_type -> bigfleet.v1alpha1.OperatorMessage
	2,  // 18: bigfleet.v1alpha1.Shard.Session:output_type -> bigfleet.v1alpha1.ShardMessage
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_bigfleet_v1alpha1_shard_proto_init() }
func file_bigfleet_v1alpha1_shard_proto_init() {
	if File_bigfleet_v1alpha1_shard_proto != nil {
		return
	}
	file_bigfleet_v1alpha1_capacity_proto_init()
	file_bigfleet_v1alpha1_provider_proto_init()
	file_bigfleet_v1alpha1_shard_proto_msgTypes[0].OneofWrappers = []any{
		(*OperatorMessage_Hello)(nil),
		(*OperatorMessage_Rollup)(nil),
		(*OperatorMessage_BootstrapResponse)(nil),
		(*OperatorMessage_ReclaimAck)(nil),
	}
	file_bigfleet_v1alpha1_shard_proto_msgTypes[1].OneofWrappers = []any{
		(*ShardMessage_Ack)(nil),
		(*ShardMessage_BootstrapRequest)(nil),
		(*ShardMessage_ReclaimInstruction)(nil),
		(*ShardMessage_NodeStateUpdate)(nil),
		(*ShardMessage_AvailableCapacity)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_shard_proto_rawDesc), len(file_bigfleet_v1alpha1_shard_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigfleet_v1alpha1_shard_proto_goTypes,
		DependencyIndexes: file_bigfleet_v1alpha1_shard_proto_depIdxs,
		EnumInfos:         file_bigfleet_v1alpha1_shard_proto_enumTypes,
		MessageInfos:      file_bigfleet_v1alpha1_shard_proto_msgTypes,
	}.Build()
	File_bigfleet_v1alpha1_shard_proto = out.File
	file_bigfleet_v1alpha1_shard_proto_goTypes = nil
	file_bigfleet_v1alpha1_shard_proto_depIdxs = nil
}
