// ShardRead is the shard's read-only diagnostic surface (ADR-0061),
// separate from the operator-initiated Shard.Session stream. It exposes
// the per-Need last-cycle verdict the decision engine computes every cycle
// and would otherwise discard, so operator tooling — a CLI, alerting, and
// the bigfleet-web-dashboard — can explore "which of a cluster's needs are
// satisfied vs unmet, and why".
//
// Read-only and general-purpose. Under mTLS the RPCs are gated by the
// bigfleet://readonly (or admin) URI SAN, exactly like the coordinator's
// read RPCs (ADR-0048 / ADR-0060); on plaintext the gate is skipped (the
// trust-the-network default). The data is leader-local-equivalent shard
// soft state: at most one cycle stale, empty before the first cycle.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: bigfleet/v1alpha1/shardread.proto

package bigfleetv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardRead_InspectNeeds_FullMethodName = "/bigfleet.v1alpha1.ShardRead/InspectNeeds"
)

// ShardReadClient is the client API for ShardRead service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardReadClient interface {
	// InspectNeeds streams the shard's last-cycle per-Need verdicts. The
	// first frame is always an InspectNeedsHeader (cycle + freshness);
	// subsequent frames are NeedView rows in the shard's Snapshot order
	// (priority desc, then arrival asc, then cluster asc). Filter to one
	// cluster via InspectNeedsRequest.cluster_id.
	InspectNeeds(ctx context.Context, in *InspectNeedsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InspectNeedsResponse], error)
}

type shardReadClient struct {
	cc grpc.ClientConnInterface
}

func NewShardReadClient(cc grpc.ClientConnInterface) ShardReadClient {
	return &shardReadClient{cc}
}

func (c *shardReadClient) InspectNeeds(ctx context.Context, in *InspectNeedsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InspectNeedsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShardRead_ServiceDesc.Streams[0], ShardRead_InspectNeeds_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InspectNeedsRequest, InspectNeedsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardRead_InspectNeedsClient = grpc.ServerStreamingClient[InspectNeedsResponse]

// ShardReadServer is the server API for ShardRead service.
// All implementations must embed UnimplementedShardReadServer
// for forward compatibility.
type ShardReadServer interface {
	// InspectNeeds streams the shard's last-cycle per-Need verdicts. The
	// first frame is always an InspectNeedsHeader (cycle + freshness);
	// subsequent frames are NeedView rows in the shard's Snapshot order
	// (priority desc, then arrival asc, then cluster asc). Filter to one
	// cluster via InspectNeedsRequest.cluster_id.
	InspectNeeds(*InspectNeedsRequest, grpc.ServerStreamingServer[InspectNeedsResponse]) error
	mustEmbedUnimplementedShardReadServer()
}

// UnimplementedShardReadServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardReadServer struct{}

func (UnimplementedShardReadServer) InspectNeeds(*InspectNeedsRequest, grpc.ServerStreamingServer[InspectNeedsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method InspectNeeds not implemented")
}
func (UnimplementedShardReadServer) mustEmbedUnimplementedShardReadServer() {}
func (UnimplementedShardReadServer) testEmbeddedByValue()                   {}

// UnsafeShardReadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardReadServer will
// result in compilation errors.
type UnsafeShardReadServer interface {
	mustEmbedUnimplementedShardReadServer()
}

func RegisterShardReadServer(s grpc.ServiceRegistrar, srv ShardReadServer) {
	// If the following call pancis, it indicates UnimplementedShardReadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardRead_ServiceDesc, srv)
}

func _ShardRead_InspectNeeds_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InspectNeedsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ShardReadServer).InspectNeeds(m, &grpc.GenericServerStream[InspectNeedsRequest, InspectNeedsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShardRead_InspectNeedsServer = grpc.ServerStreamingServer[InspectNeedsResponse]

// ShardRead_ServiceDesc is the grpc.ServiceDesc for ShardRead service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardRead_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigfleet.v1alpha1.ShardRead",
	HandlerType: (*ShardReadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InspectNeeds",
			Handler:       _ShardRead_InspectNeeds_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bigfleet/v1alpha1/shardread.proto",
}
