// ShardRead is the shard's read-only diagnostic surface (ADR-0061),
// separate from the operator-initiated Shard.Session stream. It exposes
// the per-Need last-cycle verdict the decision engine computes every cycle
// and would otherwise discard, so operator tooling — a CLI, alerting, and
// the bigfleet-web-dashboard — can explore "which of a cluster's needs are
// satisfied vs unmet, and why".
//
// Read-only and general-purpose. Under mTLS the RPCs are gated by the
// bigfleet://readonly (or admin) URI SAN, exactly like the coordinator's
// read RPCs (ADR-0048 / ADR-0060); on plaintext the gate is skipped (the
// trust-the-network default). The data is leader-local-equivalent shard
// soft state: at most one cycle stale, empty before the first cycle.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: bigfleet/v1alpha1/shardread.proto

package bigfleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UnmetReason classifies why a Need is unmet (ADR-0061). SATISFIED Needs
// carry UNMET_REASON_UNSPECIFIED.
type UnmetReason int32

const (
	UnmetReason_UNMET_REASON_UNSPECIFIED UnmetReason = 0
	// Matching supply exists but is held by equal-or-higher-precedence
	// incumbents with nothing displaceable below the cut-line.
	UnmetReason_UNMET_REASON_PRIORITY_STARVED UnmetReason = 1
	// No machine of a satisfying shape exists in the shard's inventory at any
	// price (provisioning could not produce one this cycle).
	UnmetReason_UNMET_REASON_NO_MATCHING_SUPPLY UnmetReason = 2
	// A Same/co-location constraint cannot be satisfied within the shard
	// (topology constraints never cross a shard boundary).
	UnmetReason_UNMET_REASON_TOPOLOGY_UNSATISFIABLE UnmetReason = 3
	// Phase 2 found lower-precedence victims of the right shape but could not
	// free enough to cover the deficit.
	UnmetReason_UNMET_REASON_PREEMPTION_EXHAUSTED UnmetReason = 4
)

// Enum value maps for UnmetReason.
var (
	UnmetReason_name = map[int32]string{
		0: "UNMET_REASON_UNSPECIFIED",
		1: "UNMET_REASON_PRIORITY_STARVED",
		2: "UNMET_REASON_NO_MATCHING_SUPPLY",
		3: "UNMET_REASON_TOPOLOGY_UNSATISFIABLE",
		4: "UNMET_REASON_PREEMPTION_EXHAUSTED",
	}
	UnmetReason_value = map[string]int32{
		"UNMET_REASON_UNSPECIFIED":            0,
		"UNMET_REASON_PRIORITY_STARVED":       1,
		"UNMET_REASON_NO_MATCHING_SUPPLY":     2,
		"UNMET_REASON_TOPOLOGY_UNSATISFIABLE": 3,
		"UNMET_REASON_PREEMPTION_EXHAUSTED":   4,
	}
)

func (x UnmetReason) Enum() *UnmetReason {
	p := new(UnmetReason)
	*p = x
	return p
}

func (x UnmetReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnmetReason) Descriptor() protoreflect.EnumDescriptor {
	return file_bigfleet_v1alpha1_shardread_proto_enumTypes[0].Descriptor()
}

func (UnmetReason) Type() protoreflect.EnumType {
	return &file_bigfleet_v1alpha1_shardread_proto_enumTypes[0]
}

func (x UnmetReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnmetReason.Descriptor instead.
func (UnmetReason) EnumDescriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{0}
}

type InspectNeedsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Restrict to one cluster. Empty = every cluster the shard currently
	// holds needs for. The NeedsTable is indexed by cluster, so the filter
	// is free.
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Optional cap on the number of NeedView rows streamed (0 = no cap).
	// total_needs in the header reports the pre-cap count.
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectNeedsRequest) Reset() {
	*x = InspectNeedsRequest{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectNeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectNeedsRequest) ProtoMessage() {}

func (x *InspectNeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectNeedsRequest.ProtoReflect.Descriptor instead.
func (*InspectNeedsRequest) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{0}
}

func (x *InspectNeedsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *InspectNeedsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type InspectNeedsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*InspectNeedsResponse_Header
	//	*InspectNeedsResponse_Need
	Frame         isInspectNeedsResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectNeedsResponse) Reset() {
	*x = InspectNeedsResponse{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectNeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectNeedsResponse) ProtoMessage() {}

func (x *InspectNeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectNeedsResponse.ProtoReflect.Descriptor instead.
func (*InspectNeedsResponse) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{1}
}

func (x *InspectNeedsResponse) GetFrame() isInspectNeedsResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *InspectNeedsResponse) GetHeader() *InspectNeedsHeader {
	if x != nil {
		if x, ok := x.Frame.(*InspectNeedsResponse_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *InspectNeedsResponse) GetNeed() *NeedView {
	if x != nil {
		if x, ok := x.Frame.(*InspectNeedsResponse_Need); ok {
			return x.Need
		}
	}
	return nil
}

type isInspectNeedsResponse_Frame interface {
	isInspectNeedsResponse_Frame()
}

type InspectNeedsResponse_Header struct {
	Header *InspectNeedsHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"` // always the first frame
}

type InspectNeedsResponse_Need struct {
	Need *NeedView `protobuf:"bytes,2,opt,name=need,proto3,oneof"`
}

func (*InspectNeedsResponse_Header) isInspectNeedsResponse_Frame() {}

func (*InspectNeedsResponse_Need) isInspectNeedsResponse_Frame() {}

// InspectNeedsHeader is the first streamed frame: which cycle the verdicts
// are from and when it was computed. Soft state — one cycle stale at most;
// an empty stream (header with cycle 0 / no rows) means "not yet computed",
// not "no demand".
type InspectNeedsHeader struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Cycle               int64                  `protobuf:"varint,1,opt,name=cycle,proto3" json:"cycle,omitempty"`
	ComputedAtUnixNanos int64                  `protobuf:"varint,2,opt,name=computed_at_unix_nanos,json=computedAtUnixNanos,proto3" json:"computed_at_unix_nanos,omitempty"`
	// Needs matching the filter before `limit` was applied.
	TotalNeeds    int32 `protobuf:"varint,3,opt,name=total_needs,json=totalNeeds,proto3" json:"total_needs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectNeedsHeader) Reset() {
	*x = InspectNeedsHeader{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectNeedsHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectNeedsHeader) ProtoMessage() {}

func (x *InspectNeedsHeader) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectNeedsHeader.ProtoReflect.Descriptor instead.
func (*InspectNeedsHeader) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{2}
}

func (x *InspectNeedsHeader) GetCycle() int64 {
	if x != nil {
		return x.Cycle
	}
	return 0
}

func (x *InspectNeedsHeader) GetComputedAtUnixNanos() int64 {
	if x != nil {
		return x.ComputedAtUnixNanos
	}
	return 0
}

func (x *InspectNeedsHeader) GetTotalNeeds() int32 {
	if x != nil {
		return x.TotalNeeds
	}
	return 0
}

// NeedView is one Need plus the decision engine's last-cycle verdict for it.
// The verdict fields are observation-only: they reflect what the engine
// decided, they never feed back into it.
type NeedView struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The demand: requirements / aggregate_resources / min_unit / priority /
	// spread / both penalty buckets / group (ADR-0027).
	Need               *CapacityNeed `protobuf:"bytes,1,opt,name=need,proto3" json:"need,omitempty"`
	ClusterId          string        `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ArrivalUnixNanos   int64         `protobuf:"varint,3,opt,name=arrival_unix_nanos,json=arrivalUnixNanos,proto3" json:"arrival_unix_nanos,omitempty"`
	ProfileFingerprint string        `protobuf:"bytes,4,opt,name=profile_fingerprint,json=profileFingerprint,proto3" json:"profile_fingerprint,omitempty"`
	// Whether the engine satisfied this Need's full aggregate demand.
	Satisfied bool `protobuf:"varint,5,opt,name=satisfied,proto3" json:"satisfied,omitempty"`
	// The residual unmet demand vector (ADR-0027); absent/empty when satisfied.
	ResidualDeficit *Resources `protobuf:"bytes,6,opt,name=residual_deficit,json=residualDeficit,proto3" json:"residual_deficit,omitempty"`
	// The Need's complete claimed-machine count this cycle (credited
	// Configured/Configuring + worker-committed Idle/Speculative), and the
	// acquired subsets.
	ClaimedMachineCount int32 `protobuf:"varint,7,opt,name=claimed_machine_count,json=claimedMachineCount,proto3" json:"claimed_machine_count,omitempty"`
	BootstrapCount      int32 `protobuf:"varint,8,opt,name=bootstrap_count,json=bootstrapCount,proto3" json:"bootstrap_count,omitempty"` // idle → configured acquired this cycle
	ProvisionCount      int32 `protobuf:"varint,9,opt,name=provision_count,json=provisionCount,proto3" json:"provision_count,omitempty"` // speculative → configured acquired
	// Co-location (Same) bookkeeping. same_domain is the domain the engine
	// chose for a Same-Need ("" for plain Needs); same_satisfiable is the
	// structural verdict (some domain's joint total could cover the deficit).
	SameDomain      string `protobuf:"bytes,10,opt,name=same_domain,json=sameDomain,proto3" json:"same_domain,omitempty"`
	SameSatisfiable bool   `protobuf:"varint,11,opt,name=same_satisfiable,json=sameSatisfiable,proto3" json:"same_satisfiable,omitempty"`
	// ADR-0042 acquisition parking: a Same-Need the shard stopped acquiring
	// for after it was structurally unsatisfiable for parkAfterCycles, plus
	// how long it has been parked.
	AcquisitionParked bool  `protobuf:"varint,12,opt,name=acquisition_parked,json=acquisitionParked,proto3" json:"acquisition_parked,omitempty"`
	ParkedAgeCycles   int32 `protobuf:"varint,13,opt,name=parked_age_cycles,json=parkedAgeCycles,proto3" json:"parked_age_cycles,omitempty"`
	// Cycles this Need has been unmet (from the shard's shortfall ledger;
	// 0 when satisfied).
	AgeCyclesUnmet int32 `protobuf:"varint,14,opt,name=age_cycles_unmet,json=ageCyclesUnmet,proto3" json:"age_cycles_unmet,omitempty"`
	// Why the Need is unmet. UNSPECIFIED when satisfied.
	UnmetReason UnmetReason `protobuf:"varint,15,opt,name=unmet_reason,json=unmetReason,proto3,enum=bigfleet.v1alpha1.UnmetReason" json:"unmet_reason,omitempty"`
	// Per-state cardinality of machines whose shape matches this Need
	// (MatchProfile + covers MinUnit), ignoring claims/priority — the count
	// behind the PRIORITY_STARVED (exist but held) vs NO_MATCHING_SUPPLY (all
	// zero) split. Capped per state; only populated for unsatisfied Needs.
	MatchingSupply *MatchingSupply `protobuf:"bytes,16,opt,name=matching_supply,json=matchingSupply,proto3" json:"matching_supply,omitempty"`
	// Phase 2's preemption summary for a PREEMPTION_EXHAUSTED Need: how many
	// victims it picked and the aggregate capacity they would free (still-short
	// is residual_deficit). Absent on the priority-starved path.
	Preemption *PreemptionSummary `protobuf:"bytes,17,opt,name=preemption,proto3" json:"preemption,omitempty"`
	// The top-K candidate topology domains the pre-pass weighed for a Same-Need
	// (best coverage first) — why the chosen same_domain won and how short the
	// runners-up were. Empty for plain Needs.
	SameCandidates []*DomainCoverage `protobuf:"bytes,18,rep,name=same_candidates,json=sameCandidates,proto3" json:"same_candidates,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NeedView) Reset() {
	*x = NeedView{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedView) ProtoMessage() {}

func (x *NeedView) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedView.ProtoReflect.Descriptor instead.
func (*NeedView) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{3}
}

func (x *NeedView) GetNeed() *CapacityNeed {
	if x != nil {
		return x.Need
	}
	return nil
}

func (x *NeedView) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NeedView) GetArrivalUnixNanos() int64 {
	if x != nil {
		return x.ArrivalUnixNanos
	}
	return 0
}

func (x *NeedView) GetProfileFingerprint() string {
	if x != nil {
		return x.ProfileFingerprint
	}
	return ""
}

func (x *NeedView) GetSatisfied() bool {
	if x != nil {
		return x.Satisfied
	}
	return false
}

func (x *NeedView) GetResidualDeficit() *Resources {
	if x != nil {
		return x.ResidualDeficit
	}
	return nil
}

func (x *NeedView) GetClaimedMachineCount() int32 {
	if x != nil {
		return x.ClaimedMachineCount
	}
	return 0
}

func (x *NeedView) GetBootstrapCount() int32 {
	if x != nil {
		return x.BootstrapCount
	}
	return 0
}

func (x *NeedView) GetProvisionCount() int32 {
	if x != nil {
		return x.ProvisionCount
	}
	return 0
}

func (x *NeedView) GetSameDomain() string {
	if x != nil {
		return x.SameDomain
	}
	return ""
}

func (x *NeedView) GetSameSatisfiable() bool {
	if x != nil {
		return x.SameSatisfiable
	}
	return false
}

func (x *NeedView) GetAcquisitionParked() bool {
	if x != nil {
		return x.AcquisitionParked
	}
	return false
}

func (x *NeedView) GetParkedAgeCycles() int32 {
	if x != nil {
		return x.ParkedAgeCycles
	}
	return 0
}

func (x *NeedView) GetAgeCyclesUnmet() int32 {
	if x != nil {
		return x.AgeCyclesUnmet
	}
	return 0
}

func (x *NeedView) GetUnmetReason() UnmetReason {
	if x != nil {
		return x.UnmetReason
	}
	return UnmetReason_UNMET_REASON_UNSPECIFIED
}

func (x *NeedView) GetMatchingSupply() *MatchingSupply {
	if x != nil {
		return x.MatchingSupply
	}
	return nil
}

func (x *NeedView) GetPreemption() *PreemptionSummary {
	if x != nil {
		return x.Preemption
	}
	return nil
}

func (x *NeedView) GetSameCandidates() []*DomainCoverage {
	if x != nil {
		return x.SameCandidates
	}
	return nil
}

// MatchingSupply is the per-state count of machines matching an unsatisfied
// Need's shape (ADR-0061 amendment). capped is true if any state hit the
// internal cap (the real number may be higher).
type MatchingSupply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idle          int32                  `protobuf:"varint,1,opt,name=idle,proto3" json:"idle,omitempty"`
	Configured    int32                  `protobuf:"varint,2,opt,name=configured,proto3" json:"configured,omitempty"`
	Speculative   int32                  `protobuf:"varint,3,opt,name=speculative,proto3" json:"speculative,omitempty"`
	Capped        bool                   `protobuf:"varint,4,opt,name=capped,proto3" json:"capped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingSupply) Reset() {
	*x = MatchingSupply{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingSupply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingSupply) ProtoMessage() {}

func (x *MatchingSupply) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingSupply.ProtoReflect.Descriptor instead.
func (*MatchingSupply) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{4}
}

func (x *MatchingSupply) GetIdle() int32 {
	if x != nil {
		return x.Idle
	}
	return 0
}

func (x *MatchingSupply) GetConfigured() int32 {
	if x != nil {
		return x.Configured
	}
	return 0
}

func (x *MatchingSupply) GetSpeculative() int32 {
	if x != nil {
		return x.Speculative
	}
	return 0
}

func (x *MatchingSupply) GetCapped() bool {
	if x != nil {
		return x.Capped
	}
	return false
}

// PreemptionSummary describes Phase 2's preemption attempt for a still-unmet
// Need (ADR-0061 amendment).
type PreemptionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VictimsFound  int32                  `protobuf:"varint,1,opt,name=victims_found,json=victimsFound,proto3" json:"victims_found,omitempty"`
	CapacityFreed *Resources             `protobuf:"bytes,2,opt,name=capacity_freed,json=capacityFreed,proto3" json:"capacity_freed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreemptionSummary) Reset() {
	*x = PreemptionSummary{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreemptionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreemptionSummary) ProtoMessage() {}

func (x *PreemptionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreemptionSummary.ProtoReflect.Descriptor instead.
func (*PreemptionSummary) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{5}
}

func (x *PreemptionSummary) GetVictimsFound() int32 {
	if x != nil {
		return x.VictimsFound
	}
	return 0
}

func (x *PreemptionSummary) GetCapacityFreed() *Resources {
	if x != nil {
		return x.CapacityFreed
	}
	return nil
}

// DomainCoverage is one candidate topology domain the Same pre-pass weighed:
// coverage_per_mille (0..1000, the worst-covered deficit dimension) and
// whether it fully covered the deficit (ADR-0061 amendment).
type DomainCoverage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Domain           string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	CoveragePerMille int32                  `protobuf:"varint,2,opt,name=coverage_per_mille,json=coveragePerMille,proto3" json:"coverage_per_mille,omitempty"`
	Satisfiable      bool                   `protobuf:"varint,3,opt,name=satisfiable,proto3" json:"satisfiable,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainCoverage) Reset() {
	*x = DomainCoverage{}
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainCoverage) ProtoMessage() {}

func (x *DomainCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_bigfleet_v1alpha1_shardread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainCoverage.ProtoReflect.Descriptor instead.
func (*DomainCoverage) Descriptor() ([]byte, []int) {
	return file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP(), []int{6}
}

func (x *DomainCoverage) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainCoverage) GetCoveragePerMille() int32 {
	if x != nil {
		return x.CoveragePerMille
	}
	return 0
}

func (x *DomainCoverage) GetSatisfiable() bool {
	if x != nil {
		return x.Satisfiable
	}
	return false
}

var File_bigfleet_v1alpha1_shardread_proto protoreflect.FileDescriptor

const file_bigfleet_v1alpha1_shardread_proto_rawDesc = "" +
	"\n" +
	"!bigfleet/v1alpha1/shardread.proto\x12\x11bigfleet.v1alpha1\x1a bigfleet/v1alpha1/capacity.proto\x1a bigfleet/v1alpha1/provider.proto\"J\n" +
	"\x13InspectNeedsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x93\x01\n" +
	"\x14InspectNeedsResponse\x12?\n" +
	"\x06header\x18\x01 \x01(\v2%.bigfleet.v1alpha1.InspectNeedsHeaderH\x00R\x06header\x121\n" +
	"\x04need\x18\x02 \x01(\v2\x1b.bigfleet.v1alpha1.NeedViewH\x00R\x04needB\a\n" +
	"\x05frame\"\x80\x01\n" +
	"\x12InspectNeedsHeader\x12\x14\n" +
	"\x05cycle\x18\x01 \x01(\x03R\x05cycle\x123\n" +
	"\x16computed_at_unix_nanos\x18\x02 \x01(\x03R\x13computedAtUnixNanos\x12\x1f\n" +
	"\vtotal_needs\x18\x03 \x01(\x05R\n" +
	"totalNeeds\"\x9c\a\n" +
	"\bNeedView\x123\n" +
	"\x04need\x18\x01 \x01(\v2\x1f.bigfleet.v1alpha1.CapacityNeedR\x04need\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12,\n" +
	"\x12arrival_unix_nanos\x18\x03 \x01(\x03R\x10arrivalUnixNanos\x12/\n" +
	"\x13profile_fingerprint\x18\x04 \x01(\tR\x12profileFingerprint\x12\x1c\n" +
	"\tsatisfied\x18\x05 \x01(\bR\tsatisfied\x12G\n" +
	"\x10residual_deficit\x18\x06 \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\x0fresidualDeficit\x122\n" +
	"\x15claimed_machine_count\x18\a \x01(\x05R\x13claimedMachineCount\x12'\n" +
	"\x0fbootstrap_count\x18\b \x01(\x05R\x0ebootstrapCount\x12'\n" +
	"\x0fprovision_count\x18\t \x01(\x05R\x0eprovisionCount\x12\x1f\n" +
	"\vsame_domain\x18\n" +
	" \x01(\tR\n" +
	"sameDomain\x12)\n" +
	"\x10same_satisfiable\x18\v \x01(\bR\x0fsameSatisfiable\x12-\n" +
	"\x12acquisition_parked\x18\f \x01(\bR\x11acquisitionParked\x12*\n" +
	"\x11parked_age_cycles\x18\r \x01(\x05R\x0fparkedAgeCycles\x12(\n" +
	"\x10age_cycles_unmet\x18\x0e \x01(\x05R\x0eageCyclesUnmet\x12A\n" +
	"\funmet_reason\x18\x0f \x01(\x0e2\x1e.bigfleet.v1alpha1.UnmetReasonR\vunmetReason\x12J\n" +
	"\x0fmatching_supply\x18\x10 \x01(\v2!.bigfleet.v1alpha1.MatchingSupplyR\x0ematchingSupply\x12D\n" +
	"\n" +
	"preemption\x18\x11 \x01(\v2$.bigfleet.v1alpha1.PreemptionSummaryR\n" +
	"preemption\x12J\n" +
	"\x0fsame_candidates\x18\x12 \x03(\v2!.bigfleet.v1alpha1.DomainCoverageR\x0esameCandidates\"~\n" +
	"\x0eMatchingSupply\x12\x12\n" +
	"\x04idle\x18\x01 \x01(\x05R\x04idle\x12\x1e\n" +
	"\n" +
	"configured\x18\x02 \x01(\x05R\n" +
	"configured\x12 \n" +
	"\vspeculative\x18\x03 \x01(\x05R\vspeculative\x12\x16\n" +
	"\x06capped\x18\x04 \x01(\bR\x06capped\"}\n" +
	"\x11PreemptionSummary\x12#\n" +
	"\rvictims_found\x18\x01 \x01(\x05R\fvictimsFound\x12C\n" +
	"\x0ecapacity_freed\x18\x02 \x01(\v2\x1c.bigfleet.v1alpha1.ResourcesR\rcapacityFreed\"x\n" +
	"\x0eDomainCoverage\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12,\n" +
	"\x12coverage_per_mille\x18\x02 \x01(\x05R\x10coveragePerMille\x12 \n" +
	"\vsatisfiable\x18\x03 \x01(\bR\vsatisfiable*\xc3\x01\n" +
	"\vUnmetReason\x12\x1c\n" +
	"\x18UNMET_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dUNMET_REASON_PRIORITY_STARVED\x10\x01\x12#\n" +
	"\x1fUNMET_REASON_NO_MATCHING_SUPPLY\x10\x02\x12'\n" +
	"#UNMET_REASON_TOPOLOGY_UNSATISFIABLE\x10\x03\x12%\n" +
	"!UNMET_REASON_PREEMPTION_EXHAUSTED\x10\x042n\n" +
	"\tShardRead\x12a\n" +
	"\fInspectNeeds\x12&.bigfleet.v1alpha1.InspectNeedsRequest\x1a'.bigfleet.v1alpha1.InspectNeedsResponse0\x01B\xdb\x01\n" +
	"\x15com.bigfleet.v1alpha1B\x0eShardreadProtoP\x01ZMgithub.com/intUnderflow/bigfleet/pkg/proto/bigfleet/v1alpha1;bigfleetv1alpha1\xa2\x02\x03BXX\xaa\x02\x11Bigfleet.V1alpha1\xca\x02\x11Bigfleet\\V1alpha1\xe2\x02\x1dBigfleet\\V1alpha1\\GPBMetadata\xea\x02\x12Bigfleet::V1alpha1b\x06proto3"

var (
	file_bigfleet_v1alpha1_shardread_proto_rawDescOnce sync.Once
	file_bigfleet_v1alpha1_shardread_proto_rawDescData []byte
)

func file_bigfleet_v1alpha1_shardread_proto_rawDescGZIP() []byte {
	file_bigfleet_v1alpha1_shardread_proto_rawDescOnce.Do(func() {
		file_bigfleet_v1alpha1_shardread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_shardread_proto_rawDesc), len(file_bigfleet_v1alpha1_shardread_proto_rawDesc)))
	})
	return file_bigfleet_v1alpha1_shardread_proto_rawDescData
}

var file_bigfleet_v1alpha1_shardread_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bigfleet_v1alpha1_shardread_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_bigfleet_v1alpha1_shardread_proto_goTypes = []any{
	(UnmetReason)(0),             // 0: bigfleet.v1alpha1.UnmetReason
	(*InspectNeedsRequest)(nil),  // 1: bigfleet.v1alpha1.InspectNeedsRequest
	(*InspectNeedsResponse)(nil), // 2: bigfleet.v1alpha1.InspectNeedsResponse
	(*InspectNeedsHeader)(nil),   // 3: bigfleet.v1alpha1.InspectNeedsHeader
	(*NeedView)(nil),             // 4: bigfleet.v1alpha1.NeedView
	(*MatchingSupply)(nil),       // 5: bigfleet.v1alpha1.MatchingSupply
	(*PreemptionSummary)(nil),    // 6: bigfleet.v1alpha1.PreemptionSummary
	(*DomainCoverage)(nil),       // 7: bigfleet.v1alpha1.DomainCoverage
	(*CapacityNeed)(nil),         // 8: bigfleet.v1alpha1.CapacityNeed
	(*Resources)(nil),            // 9: bigfleet.v1alpha1.Resources
}
var file_bigfleet_v1alpha1_shardread_proto_depIdxs = []int32{
	3,  // 0: bigfleet.v1alpha1.InspectNeedsResponse.header:type_name -> bigfleet.v1alpha1.InspectNeedsHeader
	4,  // 1: bigfleet.v1alpha1.InspectNeedsResponse.need:type_name -> bigfleet.v1alpha1.NeedView
	8,  // 2: bigfleet.v1alpha1.NeedView.need:type_name -> bigfleet.v1alpha1.CapacityNeed
	9,  // 3: bigfleet.v1alpha1.NeedView.residual_deficit:type_name -> bigfleet.v1alpha1.Resources
	0,  // 4: bigfleet.v1alpha1.NeedView.unmet_reason:type_name -> bigfleet.v1alpha1.UnmetReason
	5,  // 5: bigfleet.v1alpha1.NeedView.matching_supply:type_name -> bigfleet.v1alpha1.MatchingSupply
	6,  // 6: bigfleet.v1alpha1.NeedView.preemption:type_name -> bigfleet.v1alpha1.PreemptionSummary
	7,  // 7: bigfleet.v1alpha1.NeedView.same_candidates:type_name -> bigfleet.v1alpha1.DomainCoverage
	9,  // 8: bigfleet.v1alpha1.PreemptionSummary.capacity_freed:type_name -> bigfleet.v1alpha1.Resources
	1,  // 9: bigfleet.v1alpha1.ShardRead.InspectNeeds:input_type -> bigfleet.v1alpha1.InspectNeedsRequest
	2,  // 10: bigfleet.v1alpha1.ShardRead.InspectNeeds:output_type -> bigfleet.v1alpha1.InspectNeedsResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_bigfleet_v1alpha1_shardread_proto_init() }
func file_bigfleet_v1alpha1_shardread_proto_init() {
	if File_bigfleet_v1alpha1_shardread_proto != nil {
		return
	}
	file_bigfleet_v1alpha1_capacity_proto_init()
	file_bigfleet_v1alpha1_provider_proto_init()
	file_bigfleet_v1alpha1_shardread_proto_msgTypes[1].OneofWrappers = []any{
		(*InspectNeedsResponse_Header)(nil),
		(*InspectNeedsResponse_Need)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bigfleet_v1alpha1_shardread_proto_rawDesc), len(file_bigfleet_v1alpha1_shardread_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bigfleet_v1alpha1_shardread_proto_goTypes,
		DependencyIndexes: file_bigfleet_v1alpha1_shardread_proto_depIdxs,
		EnumInfos:         file_bigfleet_v1alpha1_shardread_proto_enumTypes,
		MessageInfos:      file_bigfleet_v1alpha1_shardread_proto_msgTypes,
	}.Build()
	File_bigfleet_v1alpha1_shardread_proto = out.File
	file_bigfleet_v1alpha1_shardread_proto_goTypes = nil
	file_bigfleet_v1alpha1_shardread_proto_depIdxs = nil
}
