apiVersion: v2
name: bigfleet-operator
description: BigFleet per-cluster operator. Installs the agent that dials the BigFleet shard, plus the bigfleet.lucy.sh CRDs.
type: application
version: 0.1.0
appVersion: "v0.1.0"
home: https://github.com/intUnderflow/bigfleet
sources:
  - https://github.com/intUnderflow/bigfleet
maintainers:
  - name: Lucy Sweet
keywords:
  - bigfleet
  - kubernetes
  - autoscaler
  - per-cluster-agent
