{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bigfleet.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bigfleet.labels" . | nindent 4 }}
{{- end }}
