// Capacity message types shared by the cluster operator → shard stream and
// the shard's internal data model.
//
// The CapacityNeed is the unit of aggregated demand. Every send up the
// Shard.Session stream is a *full replacement* of the cluster's desired
// state: the receiver must treat the message as the cluster's complete
// current need set. Withdrawal is implicit (a CR no longer present).
//
// Per docs/plan.md §0.1 B, the two penalty fields on CapacityNeed are
// bucketed to a coarse log scale at aggregation time so that workloads
// with slightly different penalty values still aggregate into a single
// need. The bucket boundary list is published with the CapacityRequest CRD.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fleet/v1alpha1/capacity.proto

package fleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PenaltyBucket enumerates the boundaries used to coarsen workload-specific
// penalty values. Selected at aggregation time by rounding up the raw
// dollar value to the nearest bucket.
//
// Boundaries:   $0  $0.50  $1  $2  $4  $8  $16  …  $5,242,880  $10,485,760
// Anything ≥ $10,485,760 falls in BUCKET_PINNED (treated as effectively
// non-interruptible / non-reclaimable for cost-function purposes).
type PenaltyBucket int32

const (
	PenaltyBucket_PENALTY_BUCKET_UNSPECIFIED PenaltyBucket = 0
	PenaltyBucket_PENALTY_BUCKET_ZERO        PenaltyBucket = 1 // $0
	PenaltyBucket_PENALTY_BUCKET_HALF_DOLLAR PenaltyBucket = 2 // (0, $0.50]
	PenaltyBucket_PENALTY_BUCKET_1           PenaltyBucket = 3 // ($0.50, $1]
	PenaltyBucket_PENALTY_BUCKET_2           PenaltyBucket = 4
	PenaltyBucket_PENALTY_BUCKET_4           PenaltyBucket = 5
	PenaltyBucket_PENALTY_BUCKET_8           PenaltyBucket = 6
	PenaltyBucket_PENALTY_BUCKET_16          PenaltyBucket = 7
	PenaltyBucket_PENALTY_BUCKET_32          PenaltyBucket = 8
	PenaltyBucket_PENALTY_BUCKET_64          PenaltyBucket = 9
	PenaltyBucket_PENALTY_BUCKET_128         PenaltyBucket = 10
	PenaltyBucket_PENALTY_BUCKET_256         PenaltyBucket = 11
	PenaltyBucket_PENALTY_BUCKET_512         PenaltyBucket = 12
	PenaltyBucket_PENALTY_BUCKET_1024        PenaltyBucket = 13 // $1,024
	PenaltyBucket_PENALTY_BUCKET_2048        PenaltyBucket = 14
	PenaltyBucket_PENALTY_BUCKET_4096        PenaltyBucket = 15
	PenaltyBucket_PENALTY_BUCKET_8192        PenaltyBucket = 16
	PenaltyBucket_PENALTY_BUCKET_16384       PenaltyBucket = 17
	PenaltyBucket_PENALTY_BUCKET_32768       PenaltyBucket = 18
	PenaltyBucket_PENALTY_BUCKET_65536       PenaltyBucket = 19
	PenaltyBucket_PENALTY_BUCKET_131072      PenaltyBucket = 20
	PenaltyBucket_PENALTY_BUCKET_262144      PenaltyBucket = 21
	PenaltyBucket_PENALTY_BUCKET_524288      PenaltyBucket = 22
	PenaltyBucket_PENALTY_BUCKET_1048576     PenaltyBucket = 23 // $1,048,576
	PenaltyBucket_PENALTY_BUCKET_2097152     PenaltyBucket = 24
	PenaltyBucket_PENALTY_BUCKET_4194304     PenaltyBucket = 25
	PenaltyBucket_PENALTY_BUCKET_10485760    PenaltyBucket = 26 // $10,485,760
	PenaltyBucket_PENALTY_BUCKET_PINNED      PenaltyBucket = 27 // > $10,485,760: treat as effectively infinite
)

// Enum value maps for PenaltyBucket.
var (
	PenaltyBucket_name = map[int32]string{
		0:  "PENALTY_BUCKET_UNSPECIFIED",
		1:  "PENALTY_BUCKET_ZERO",
		2:  "PENALTY_BUCKET_HALF_DOLLAR",
		3:  "PENALTY_BUCKET_1",
		4:  "PENALTY_BUCKET_2",
		5:  "PENALTY_BUCKET_4",
		6:  "PENALTY_BUCKET_8",
		7:  "PENALTY_BUCKET_16",
		8:  "PENALTY_BUCKET_32",
		9:  "PENALTY_BUCKET_64",
		10: "PENALTY_BUCKET_128",
		11: "PENALTY_BUCKET_256",
		12: "PENALTY_BUCKET_512",
		13: "PENALTY_BUCKET_1024",
		14: "PENALTY_BUCKET_2048",
		15: "PENALTY_BUCKET_4096",
		16: "PENALTY_BUCKET_8192",
		17: "PENALTY_BUCKET_16384",
		18: "PENALTY_BUCKET_32768",
		19: "PENALTY_BUCKET_65536",
		20: "PENALTY_BUCKET_131072",
		21: "PENALTY_BUCKET_262144",
		22: "PENALTY_BUCKET_524288",
		23: "PENALTY_BUCKET_1048576",
		24: "PENALTY_BUCKET_2097152",
		25: "PENALTY_BUCKET_4194304",
		26: "PENALTY_BUCKET_10485760",
		27: "PENALTY_BUCKET_PINNED",
	}
	PenaltyBucket_value = map[string]int32{
		"PENALTY_BUCKET_UNSPECIFIED": 0,
		"PENALTY_BUCKET_ZERO":        1,
		"PENALTY_BUCKET_HALF_DOLLAR": 2,
		"PENALTY_BUCKET_1":           3,
		"PENALTY_BUCKET_2":           4,
		"PENALTY_BUCKET_4":           5,
		"PENALTY_BUCKET_8":           6,
		"PENALTY_BUCKET_16":          7,
		"PENALTY_BUCKET_32":          8,
		"PENALTY_BUCKET_64":          9,
		"PENALTY_BUCKET_128":         10,
		"PENALTY_BUCKET_256":         11,
		"PENALTY_BUCKET_512":         12,
		"PENALTY_BUCKET_1024":        13,
		"PENALTY_BUCKET_2048":        14,
		"PENALTY_BUCKET_4096":        15,
		"PENALTY_BUCKET_8192":        16,
		"PENALTY_BUCKET_16384":       17,
		"PENALTY_BUCKET_32768":       18,
		"PENALTY_BUCKET_65536":       19,
		"PENALTY_BUCKET_131072":      20,
		"PENALTY_BUCKET_262144":      21,
		"PENALTY_BUCKET_524288":      22,
		"PENALTY_BUCKET_1048576":     23,
		"PENALTY_BUCKET_2097152":     24,
		"PENALTY_BUCKET_4194304":     25,
		"PENALTY_BUCKET_10485760":    26,
		"PENALTY_BUCKET_PINNED":      27,
	}
)

func (x PenaltyBucket) Enum() *PenaltyBucket {
	p := new(PenaltyBucket)
	*p = x
	return p
}

func (x PenaltyBucket) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PenaltyBucket) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1alpha1_capacity_proto_enumTypes[0].Descriptor()
}

func (PenaltyBucket) Type() protoreflect.EnumType {
	return &file_fleet_v1alpha1_capacity_proto_enumTypes[0]
}

func (x PenaltyBucket) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PenaltyBucket.Descriptor instead.
func (PenaltyBucket) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{0}
}

type NodeSelectorRequirement_Operator int32

const (
	NodeSelectorRequirement_OPERATOR_UNSPECIFIED    NodeSelectorRequirement_Operator = 0
	NodeSelectorRequirement_OPERATOR_IN             NodeSelectorRequirement_Operator = 1
	NodeSelectorRequirement_OPERATOR_NOT_IN         NodeSelectorRequirement_Operator = 2
	NodeSelectorRequirement_OPERATOR_EXISTS         NodeSelectorRequirement_Operator = 3
	NodeSelectorRequirement_OPERATOR_DOES_NOT_EXIST NodeSelectorRequirement_Operator = 4
	// Same: all `count` nodes in this CapacityNeed must share a value for
	// this key. Optional values restrict which value is acceptable. Only
	// valid in the protobuf wire format; not surfaced on the CRD.
	NodeSelectorRequirement_OPERATOR_SAME NodeSelectorRequirement_Operator = 5
)

// Enum value maps for NodeSelectorRequirement_Operator.
var (
	NodeSelectorRequirement_Operator_name = map[int32]string{
		0: "OPERATOR_UNSPECIFIED",
		1: "OPERATOR_IN",
		2: "OPERATOR_NOT_IN",
		3: "OPERATOR_EXISTS",
		4: "OPERATOR_DOES_NOT_EXIST",
		5: "OPERATOR_SAME",
	}
	NodeSelectorRequirement_Operator_value = map[string]int32{
		"OPERATOR_UNSPECIFIED":    0,
		"OPERATOR_IN":             1,
		"OPERATOR_NOT_IN":         2,
		"OPERATOR_EXISTS":         3,
		"OPERATOR_DOES_NOT_EXIST": 4,
		"OPERATOR_SAME":           5,
	}
)

func (x NodeSelectorRequirement_Operator) Enum() *NodeSelectorRequirement_Operator {
	p := new(NodeSelectorRequirement_Operator)
	*p = x
	return p
}

func (x NodeSelectorRequirement_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeSelectorRequirement_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1alpha1_capacity_proto_enumTypes[1].Descriptor()
}

func (NodeSelectorRequirement_Operator) Type() protoreflect.EnumType {
	return &file_fleet_v1alpha1_capacity_proto_enumTypes[1]
}

func (x NodeSelectorRequirement_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeSelectorRequirement_Operator.Descriptor instead.
func (NodeSelectorRequirement_Operator) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{2, 0}
}

type TopologySpread_WhenUnsatisfiable int32

const (
	TopologySpread_WHEN_UNSATISFIABLE_UNSPECIFIED     TopologySpread_WhenUnsatisfiable = 0
	TopologySpread_WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE TopologySpread_WhenUnsatisfiable = 1
	TopologySpread_WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY TopologySpread_WhenUnsatisfiable = 2
)

// Enum value maps for TopologySpread_WhenUnsatisfiable.
var (
	TopologySpread_WhenUnsatisfiable_name = map[int32]string{
		0: "WHEN_UNSATISFIABLE_UNSPECIFIED",
		1: "WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE",
		2: "WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY",
	}
	TopologySpread_WhenUnsatisfiable_value = map[string]int32{
		"WHEN_UNSATISFIABLE_UNSPECIFIED":     0,
		"WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE": 1,
		"WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY": 2,
	}
)

func (x TopologySpread_WhenUnsatisfiable) Enum() *TopologySpread_WhenUnsatisfiable {
	p := new(TopologySpread_WhenUnsatisfiable)
	*p = x
	return p
}

func (x TopologySpread_WhenUnsatisfiable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopologySpread_WhenUnsatisfiable) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_v1alpha1_capacity_proto_enumTypes[2].Descriptor()
}

func (TopologySpread_WhenUnsatisfiable) Type() protoreflect.EnumType {
	return &file_fleet_v1alpha1_capacity_proto_enumTypes[2]
}

func (x TopologySpread_WhenUnsatisfiable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopologySpread_WhenUnsatisfiable.Descriptor instead.
func (TopologySpread_WhenUnsatisfiable) EnumDescriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{3, 0}
}

// ClusterCapacityNeeds is what an operator sends to its shard each cycle.
// It is a full replacement of the cluster's desired state. The shard diffs
// against its inventory and reacts.
type ClusterCapacityNeeds struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier for the cluster. Assigned by the operator and never
	// changed for the life of the cluster.
	ClusterId string `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// Wall-clock time at which the operator built this snapshot.
	TimestampUnixNanos int64 `protobuf:"varint,2,opt,name=timestamp_unix_nanos,json=timestampUnixNanos,proto3" json:"timestamp_unix_nanos,omitempty"`
	// Aggregated demand. Pods sharing a profile collapse into one entry.
	Needs         []*CapacityNeed `protobuf:"bytes,3,rep,name=needs,proto3" json:"needs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterCapacityNeeds) Reset() {
	*x = ClusterCapacityNeeds{}
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterCapacityNeeds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterCapacityNeeds) ProtoMessage() {}

func (x *ClusterCapacityNeeds) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterCapacityNeeds.ProtoReflect.Descriptor instead.
func (*ClusterCapacityNeeds) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterCapacityNeeds) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ClusterCapacityNeeds) GetTimestampUnixNanos() int64 {
	if x != nil {
		return x.TimestampUnixNanos
	}
	return 0
}

func (x *ClusterCapacityNeeds) GetNeeds() []*CapacityNeed {
	if x != nil {
		return x.Needs
	}
	return nil
}

// CapacityNeed is the aggregated unit of capacity demand. The aggregation
// key is (requirements, resources, priority, spread, interruption_penalty_bucket,
// reclamation_penalty_bucket). Two CRs whose fields all match across that key
// become a single CapacityNeed with count = 2.
type CapacityNeed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Node-selector style requirements that must be satisfied. The autoscaler
	// is responsible for honouring all standard operators (In, NotIn, Exists,
	// DoesNotExist) plus the protobuf-only Same operator (see below).
	Requirements []*NodeSelectorRequirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	// Per-machine resource requests. Map keys are Kubernetes resource names
	// (e.g., "cpu", "memory", "nvidia.com/gpu"); values are quantity strings
	// ("96", "768Gi", "8"). The autoscaler does not parse these; it forwards
	// them to the provider, which is responsible for matching offerings.
	Resources map[string]string `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The pod's PriorityClass value. Higher = served first. The autoscaler
	// walks needs top-down by priority.
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Number of identically-shaped machines required.
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// Topology-spread constraints copied from the source pod(s). Pass-through
	// to the autoscaler so it can spread provisioning across domains.
	Spread []*TopologySpread `protobuf:"bytes,5,rep,name=spread,proto3" json:"spread,omitempty"`
	// Bucketed penalties. Bucket boundaries are powers of 2 in dollars between
	// $0.50 and $10M; CRs with raw penalties in the same bucket aggregate.
	// The cost-function effect of bucketing is bounded and small; the size
	// of the roll-up message stays bounded even when penalties are
	// workload-specific.
	InterruptionPenaltyBucket PenaltyBucket `protobuf:"varint,6,opt,name=interruption_penalty_bucket,json=interruptionPenaltyBucket,proto3,enum=fleet.v1alpha1.PenaltyBucket" json:"interruption_penalty_bucket,omitempty"`
	ReclamationPenaltyBucket  PenaltyBucket `protobuf:"varint,7,opt,name=reclamation_penalty_bucket,json=reclamationPenaltyBucket,proto3,enum=fleet.v1alpha1.PenaltyBucket" json:"reclamation_penalty_bucket,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CapacityNeed) Reset() {
	*x = CapacityNeed{}
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityNeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityNeed) ProtoMessage() {}

func (x *CapacityNeed) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityNeed.ProtoReflect.Descriptor instead.
func (*CapacityNeed) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{1}
}

func (x *CapacityNeed) GetRequirements() []*NodeSelectorRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *CapacityNeed) GetResources() map[string]string {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CapacityNeed) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CapacityNeed) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *CapacityNeed) GetSpread() []*TopologySpread {
	if x != nil {
		return x.Spread
	}
	return nil
}

func (x *CapacityNeed) GetInterruptionPenaltyBucket() PenaltyBucket {
	if x != nil {
		return x.InterruptionPenaltyBucket
	}
	return PenaltyBucket_PENALTY_BUCKET_UNSPECIFIED
}

func (x *CapacityNeed) GetReclamationPenaltyBucket() PenaltyBucket {
	if x != nil {
		return x.ReclamationPenaltyBucket
	}
	return PenaltyBucket_PENALTY_BUCKET_UNSPECIFIED
}

// NodeSelectorRequirement mirrors core/v1.NodeSelectorRequirement, plus a
// protobuf-only Same operator that the cluster operator emits when a CR
// requires co-location (e.g., all 64 nodes on one rack).
type NodeSelectorRequirement struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Key           string                           `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Operator      NodeSelectorRequirement_Operator `protobuf:"varint,2,opt,name=operator,proto3,enum=fleet.v1alpha1.NodeSelectorRequirement_Operator" json:"operator,omitempty"`
	Values        []string                         `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSelectorRequirement) Reset() {
	*x = NodeSelectorRequirement{}
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSelectorRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSelectorRequirement) ProtoMessage() {}

func (x *NodeSelectorRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSelectorRequirement.ProtoReflect.Descriptor instead.
func (*NodeSelectorRequirement) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{2}
}

func (x *NodeSelectorRequirement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *NodeSelectorRequirement) GetOperator() NodeSelectorRequirement_Operator {
	if x != nil {
		return x.Operator
	}
	return NodeSelectorRequirement_OPERATOR_UNSPECIFIED
}

func (x *NodeSelectorRequirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// TopologySpread is the autoscaler-visible projection of a pod's
// topologySpreadConstraints. Whether the autoscaler honours the constraint
// when no machines exist depends on whenUnsatisfiable.
type TopologySpread struct {
	state             protoimpl.MessageState           `protogen:"open.v1"`
	TopologyKey       string                           `protobuf:"bytes,1,opt,name=topology_key,json=topologyKey,proto3" json:"topology_key,omitempty"`
	MaxSkew           int32                            `protobuf:"varint,2,opt,name=max_skew,json=maxSkew,proto3" json:"max_skew,omitempty"`
	WhenUnsatisfiable TopologySpread_WhenUnsatisfiable `protobuf:"varint,3,opt,name=when_unsatisfiable,json=whenUnsatisfiable,proto3,enum=fleet.v1alpha1.TopologySpread_WhenUnsatisfiable" json:"when_unsatisfiable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopologySpread) Reset() {
	*x = TopologySpread{}
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologySpread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologySpread) ProtoMessage() {}

func (x *TopologySpread) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologySpread.ProtoReflect.Descriptor instead.
func (*TopologySpread) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{3}
}

func (x *TopologySpread) GetTopologyKey() string {
	if x != nil {
		return x.TopologyKey
	}
	return ""
}

func (x *TopologySpread) GetMaxSkew() int32 {
	if x != nil {
		return x.MaxSkew
	}
	return 0
}

func (x *TopologySpread) GetWhenUnsatisfiable() TopologySpread_WhenUnsatisfiable {
	if x != nil {
		return x.WhenUnsatisfiable
	}
	return TopologySpread_WHEN_UNSATISFIABLE_UNSPECIFIED
}

var File_fleet_v1alpha1_capacity_proto protoreflect.FileDescriptor

const file_fleet_v1alpha1_capacity_proto_rawDesc = "" +
	"\n" +
	"\x1dfleet/v1alpha1/capacity.proto\x12\x0efleet.v1alpha1\"\x9b\x01\n" +
	"\x14ClusterCapacityNeeds\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x120\n" +
	"\x14timestamp_unix_nanos\x18\x02 \x01(\x03R\x12timestampUnixNanos\x122\n" +
	"\x05needs\x18\x03 \x03(\v2\x1c.fleet.v1alpha1.CapacityNeedR\x05needs\"\x8a\x04\n" +
	"\fCapacityNeed\x12K\n" +
	"\frequirements\x18\x01 \x03(\v2'.fleet.v1alpha1.NodeSelectorRequirementR\frequirements\x12I\n" +
	"\tresources\x18\x02 \x03(\v2+.fleet.v1alpha1.CapacityNeed.ResourcesEntryR\tresources\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x126\n" +
	"\x06spread\x18\x05 \x03(\v2\x1e.fleet.v1alpha1.TopologySpreadR\x06spread\x12]\n" +
	"\x1binterruption_penalty_bucket\x18\x06 \x01(\x0e2\x1d.fleet.v1alpha1.PenaltyBucketR\x19interruptionPenaltyBucket\x12[\n" +
	"\x1areclamation_penalty_bucket\x18\a \x01(\x0e2\x1d.fleet.v1alpha1.PenaltyBucketR\x18reclamationPenaltyBucket\x1a<\n" +
	"\x0eResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\x17NodeSelectorRequirement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12L\n" +
	"\boperator\x18\x02 \x01(\x0e20.fleet.v1alpha1.NodeSelectorRequirement.OperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values\"\x8f\x01\n" +
	"\bOperator\x12\x18\n" +
	"\x14OPERATOR_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOPERATOR_IN\x10\x01\x12\x13\n" +
	"\x0fOPERATOR_NOT_IN\x10\x02\x12\x13\n" +
	"\x0fOPERATOR_EXISTS\x10\x03\x12\x1b\n" +
	"\x17OPERATOR_DOES_NOT_EXIST\x10\x04\x12\x11\n" +
	"\rOPERATOR_SAME\x10\x05\"\xb9\x02\n" +
	"\x0eTopologySpread\x12!\n" +
	"\ftopology_key\x18\x01 \x01(\tR\vtopologyKey\x12\x19\n" +
	"\bmax_skew\x18\x02 \x01(\x05R\amaxSkew\x12_\n" +
	"\x12when_unsatisfiable\x18\x03 \x01(\x0e20.fleet.v1alpha1.TopologySpread.WhenUnsatisfiableR\x11whenUnsatisfiable\"\x87\x01\n" +
	"\x11WhenUnsatisfiable\x12\"\n" +
	"\x1eWHEN_UNSATISFIABLE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"WHEN_UNSATISFIABLE_DO_NOT_SCHEDULE\x10\x01\x12&\n" +
	"\"WHEN_UNSATISFIABLE_SCHEDULE_ANYWAY\x10\x02*\xdc\x05\n" +
	"\rPenaltyBucket\x12\x1e\n" +
	"\x1aPENALTY_BUCKET_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PENALTY_BUCKET_ZERO\x10\x01\x12\x1e\n" +
	"\x1aPENALTY_BUCKET_HALF_DOLLAR\x10\x02\x12\x14\n" +
	"\x10PENALTY_BUCKET_1\x10\x03\x12\x14\n" +
	"\x10PENALTY_BUCKET_2\x10\x04\x12\x14\n" +
	"\x10PENALTY_BUCKET_4\x10\x05\x12\x14\n" +
	"\x10PENALTY_BUCKET_8\x10\x06\x12\x15\n" +
	"\x11PENALTY_BUCKET_16\x10\a\x12\x15\n" +
	"\x11PENALTY_BUCKET_32\x10\b\x12\x15\n" +
	"\x11PENALTY_BUCKET_64\x10\t\x12\x16\n" +
	"\x12PENALTY_BUCKET_128\x10\n" +
	"\x12\x16\n" +
	"\x12PENALTY_BUCKET_256\x10\v\x12\x16\n" +
	"\x12PENALTY_BUCKET_512\x10\f\x12\x17\n" +
	"\x13PENALTY_BUCKET_1024\x10\r\x12\x17\n" +
	"\x13PENALTY_BUCKET_2048\x10\x0e\x12\x17\n" +
	"\x13PENALTY_BUCKET_4096\x10\x0f\x12\x17\n" +
	"\x13PENALTY_BUCKET_8192\x10\x10\x12\x18\n" +
	"\x14PENALTY_BUCKET_16384\x10\x11\x12\x18\n" +
	"\x14PENALTY_BUCKET_32768\x10\x12\x12\x18\n" +
	"\x14PENALTY_BUCKET_65536\x10\x13\x12\x19\n" +
	"\x15PENALTY_BUCKET_131072\x10\x14\x12\x19\n" +
	"\x15PENALTY_BUCKET_262144\x10\x15\x12\x19\n" +
	"\x15PENALTY_BUCKET_524288\x10\x16\x12\x1a\n" +
	"\x16PENALTY_BUCKET_1048576\x10\x17\x12\x1a\n" +
	"\x16PENALTY_BUCKET_2097152\x10\x18\x12\x1a\n" +
	"\x16PENALTY_BUCKET_4194304\x10\x19\x12\x1b\n" +
	"\x17PENALTY_BUCKET_10485760\x10\x1a\x12\x19\n" +
	"\x15PENALTY_BUCKET_PINNED\x10\x1bB\xc9\x01\n" +
	"\x12com.fleet.v1alpha1B\rCapacityProtoP\x01ZKgithub.com/intUnderflow/bigfleet/pkg/api/proto/fleet/v1alpha1;fleetv1alpha1\xa2\x02\x03FXX\xaa\x02\x0eFleet.V1alpha1\xca\x02\x0eFleet\\V1alpha1\xe2\x02\x1aFleet\\V1alpha1\\GPBMetadata\xea\x02\x0fFleet::V1alpha1b\x06proto3"

var (
	file_fleet_v1alpha1_capacity_proto_rawDescOnce sync.Once
	file_fleet_v1alpha1_capacity_proto_rawDescData []byte
)

func file_fleet_v1alpha1_capacity_proto_rawDescGZIP() []byte {
	file_fleet_v1alpha1_capacity_proto_rawDescOnce.Do(func() {
		file_fleet_v1alpha1_capacity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_capacity_proto_rawDesc), len(file_fleet_v1alpha1_capacity_proto_rawDesc)))
	})
	return file_fleet_v1alpha1_capacity_proto_rawDescData
}

var file_fleet_v1alpha1_capacity_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_fleet_v1alpha1_capacity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_fleet_v1alpha1_capacity_proto_goTypes = []any{
	(PenaltyBucket)(0),                    // 0: fleet.v1alpha1.PenaltyBucket
	(NodeSelectorRequirement_Operator)(0), // 1: fleet.v1alpha1.NodeSelectorRequirement.Operator
	(TopologySpread_WhenUnsatisfiable)(0), // 2: fleet.v1alpha1.TopologySpread.WhenUnsatisfiable
	(*ClusterCapacityNeeds)(nil),          // 3: fleet.v1alpha1.ClusterCapacityNeeds
	(*CapacityNeed)(nil),                  // 4: fleet.v1alpha1.CapacityNeed
	(*NodeSelectorRequirement)(nil),       // 5: fleet.v1alpha1.NodeSelectorRequirement
	(*TopologySpread)(nil),                // 6: fleet.v1alpha1.TopologySpread
	nil,                                   // 7: fleet.v1alpha1.CapacityNeed.ResourcesEntry
}
var file_fleet_v1alpha1_capacity_proto_depIdxs = []int32{
	4, // 0: fleet.v1alpha1.ClusterCapacityNeeds.needs:type_name -> fleet.v1alpha1.CapacityNeed
	5, // 1: fleet.v1alpha1.CapacityNeed.requirements:type_name -> fleet.v1alpha1.NodeSelectorRequirement
	7, // 2: fleet.v1alpha1.CapacityNeed.resources:type_name -> fleet.v1alpha1.CapacityNeed.ResourcesEntry
	6, // 3: fleet.v1alpha1.CapacityNeed.spread:type_name -> fleet.v1alpha1.TopologySpread
	0, // 4: fleet.v1alpha1.CapacityNeed.interruption_penalty_bucket:type_name -> fleet.v1alpha1.PenaltyBucket
	0, // 5: fleet.v1alpha1.CapacityNeed.reclamation_penalty_bucket:type_name -> fleet.v1alpha1.PenaltyBucket
	1, // 6: fleet.v1alpha1.NodeSelectorRequirement.operator:type_name -> fleet.v1alpha1.NodeSelectorRequirement.Operator
	2, // 7: fleet.v1alpha1.TopologySpread.when_unsatisfiable:type_name -> fleet.v1alpha1.TopologySpread.WhenUnsatisfiable
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_fleet_v1alpha1_capacity_proto_init() }
func file_fleet_v1alpha1_capacity_proto_init() {
	if File_fleet_v1alpha1_capacity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_capacity_proto_rawDesc), len(file_fleet_v1alpha1_capacity_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1alpha1_capacity_proto_goTypes,
		DependencyIndexes: file_fleet_v1alpha1_capacity_proto_depIdxs,
		EnumInfos:         file_fleet_v1alpha1_capacity_proto_enumTypes,
		MessageInfos:      file_fleet_v1alpha1_capacity_proto_msgTypes,
	}.Build()
	File_fleet_v1alpha1_capacity_proto = out.File
	file_fleet_v1alpha1_capacity_proto_goTypes = nil
	file_fleet_v1alpha1_capacity_proto_depIdxs = nil
}
