// Capacity message types shared by the cluster operator → shard stream and
// the shard's internal data model. Defines the wire shape of a CapacityNeed
// (the aggregated unit of demand) and the supporting requirement / spread
// types. Real fields are added in M1; this stub only exists so buf generates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fleet/v1alpha1/capacity.proto

package fleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CapacityNeed is the aggregated unit of capacity demand. Filled out in M1.
type CapacityNeed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Placeholder. M1 adds requirements, resources, priority, count, spread,
	// interruption_penalty, reclamation_penalty (bucketed per plan §0.1 B).
	Placeholder   string `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityNeed) Reset() {
	*x = CapacityNeed{}
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityNeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityNeed) ProtoMessage() {}

func (x *CapacityNeed) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_capacity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityNeed.ProtoReflect.Descriptor instead.
func (*CapacityNeed) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_capacity_proto_rawDescGZIP(), []int{0}
}

func (x *CapacityNeed) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

var File_fleet_v1alpha1_capacity_proto protoreflect.FileDescriptor

const file_fleet_v1alpha1_capacity_proto_rawDesc = "" +
	"\n" +
	"\x1dfleet/v1alpha1/capacity.proto\x12\x0efleet.v1alpha1\"0\n" +
	"\fCapacityNeed\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholderB\xc9\x01\n" +
	"\x12com.fleet.v1alpha1B\rCapacityProtoP\x01ZKgithub.com/intUnderflow/bigfleet/pkg/api/proto/fleet/v1alpha1;fleetv1alpha1\xa2\x02\x03FXX\xaa\x02\x0eFleet.V1alpha1\xca\x02\x0eFleet\\V1alpha1\xe2\x02\x1aFleet\\V1alpha1\\GPBMetadata\xea\x02\x0fFleet::V1alpha1b\x06proto3"

var (
	file_fleet_v1alpha1_capacity_proto_rawDescOnce sync.Once
	file_fleet_v1alpha1_capacity_proto_rawDescData []byte
)

func file_fleet_v1alpha1_capacity_proto_rawDescGZIP() []byte {
	file_fleet_v1alpha1_capacity_proto_rawDescOnce.Do(func() {
		file_fleet_v1alpha1_capacity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_capacity_proto_rawDesc), len(file_fleet_v1alpha1_capacity_proto_rawDesc)))
	})
	return file_fleet_v1alpha1_capacity_proto_rawDescData
}

var file_fleet_v1alpha1_capacity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fleet_v1alpha1_capacity_proto_goTypes = []any{
	(*CapacityNeed)(nil), // 0: fleet.v1alpha1.CapacityNeed
}
var file_fleet_v1alpha1_capacity_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fleet_v1alpha1_capacity_proto_init() }
func file_fleet_v1alpha1_capacity_proto_init() {
	if File_fleet_v1alpha1_capacity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_capacity_proto_rawDesc), len(file_fleet_v1alpha1_capacity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1alpha1_capacity_proto_goTypes,
		DependencyIndexes: file_fleet_v1alpha1_capacity_proto_depIdxs,
		MessageInfos:      file_fleet_v1alpha1_capacity_proto_msgTypes,
	}.Build()
	File_fleet_v1alpha1_capacity_proto = out.File
	file_fleet_v1alpha1_capacity_proto_goTypes = nil
	file_fleet_v1alpha1_capacity_proto_depIdxs = nil
}
