// Coordinator service: internal RPCs between shards and the global coordinator.
// Shard → coordinator: ReportShard (summary + shortfalls).
// Coordinator → shard: Instruct (rebalance, drain, transfer ownership) carrying
// (coordinator_term, sequence_number) for fencing.
//
// Real fields are added in M1; this stub only exists so buf generates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fleet/v1alpha1/coordinator.proto

package fleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShardReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardReport) Reset() {
	*x = ShardReport{}
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardReport) ProtoMessage() {}

func (x *ShardReport) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardReport.ProtoReflect.Descriptor instead.
func (*ShardReport) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *ShardReport) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type ReportAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAck) Reset() {
	*x = ReportAck{}
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAck) ProtoMessage() {}

func (x *ReportAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAck.ProtoReflect.Descriptor instead.
func (*ReportAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAck) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type CoordinatorInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorInstruction) Reset() {
	*x = CoordinatorInstruction{}
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorInstruction) ProtoMessage() {}

func (x *CoordinatorInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorInstruction.ProtoReflect.Descriptor instead.
func (*CoordinatorInstruction) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorInstruction) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type InstructAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstructAck) Reset() {
	*x = InstructAck{}
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstructAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstructAck) ProtoMessage() {}

func (x *InstructAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstructAck.ProtoReflect.Descriptor instead.
func (*InstructAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *InstructAck) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

var File_fleet_v1alpha1_coordinator_proto protoreflect.FileDescriptor

const file_fleet_v1alpha1_coordinator_proto_rawDesc = "" +
	"\n" +
	" fleet/v1alpha1/coordinator.proto\x12\x0efleet.v1alpha1\"/\n" +
	"\vShardReport\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"-\n" +
	"\tReportAck\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\":\n" +
	"\x16CoordinatorInstruction\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"/\n" +
	"\vInstructAck\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder2\xa5\x01\n" +
	"\vCoordinator\x12E\n" +
	"\vReportShard\x12\x1b.fleet.v1alpha1.ShardReport\x1a\x19.fleet.v1alpha1.ReportAck\x12O\n" +
	"\bInstruct\x12&.fleet.v1alpha1.CoordinatorInstruction\x1a\x1b.fleet.v1alpha1.InstructAckB\xcc\x01\n" +
	"\x12com.fleet.v1alpha1B\x10CoordinatorProtoP\x01ZKgithub.com/intUnderflow/bigfleet/pkg/api/proto/fleet/v1alpha1;fleetv1alpha1\xa2\x02\x03FXX\xaa\x02\x0eFleet.V1alpha1\xca\x02\x0eFleet\\V1alpha1\xe2\x02\x1aFleet\\V1alpha1\\GPBMetadata\xea\x02\x0fFleet::V1alpha1b\x06proto3"

var (
	file_fleet_v1alpha1_coordinator_proto_rawDescOnce sync.Once
	file_fleet_v1alpha1_coordinator_proto_rawDescData []byte
)

func file_fleet_v1alpha1_coordinator_proto_rawDescGZIP() []byte {
	file_fleet_v1alpha1_coordinator_proto_rawDescOnce.Do(func() {
		file_fleet_v1alpha1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_coordinator_proto_rawDesc), len(file_fleet_v1alpha1_coordinator_proto_rawDesc)))
	})
	return file_fleet_v1alpha1_coordinator_proto_rawDescData
}

var file_fleet_v1alpha1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fleet_v1alpha1_coordinator_proto_goTypes = []any{
	(*ShardReport)(nil),            // 0: fleet.v1alpha1.ShardReport
	(*ReportAck)(nil),              // 1: fleet.v1alpha1.ReportAck
	(*CoordinatorInstruction)(nil), // 2: fleet.v1alpha1.CoordinatorInstruction
	(*InstructAck)(nil),            // 3: fleet.v1alpha1.InstructAck
}
var file_fleet_v1alpha1_coordinator_proto_depIdxs = []int32{
	0, // 0: fleet.v1alpha1.Coordinator.ReportShard:input_type -> fleet.v1alpha1.ShardReport
	2, // 1: fleet.v1alpha1.Coordinator.Instruct:input_type -> fleet.v1alpha1.CoordinatorInstruction
	1, // 2: fleet.v1alpha1.Coordinator.ReportShard:output_type -> fleet.v1alpha1.ReportAck
	3, // 3: fleet.v1alpha1.Coordinator.Instruct:output_type -> fleet.v1alpha1.InstructAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fleet_v1alpha1_coordinator_proto_init() }
func file_fleet_v1alpha1_coordinator_proto_init() {
	if File_fleet_v1alpha1_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_coordinator_proto_rawDesc), len(file_fleet_v1alpha1_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_v1alpha1_coordinator_proto_goTypes,
		DependencyIndexes: file_fleet_v1alpha1_coordinator_proto_depIdxs,
		MessageInfos:      file_fleet_v1alpha1_coordinator_proto_msgTypes,
	}.Build()
	File_fleet_v1alpha1_coordinator_proto = out.File
	file_fleet_v1alpha1_coordinator_proto_goTypes = nil
	file_fleet_v1alpha1_coordinator_proto_depIdxs = nil
}
