// CapacityProvider service: the contract every out-of-tree provider implements.
// Six RPCs only — Create, Configure, Drain, Delete, Get, List — all async,
// all idempotent. No Watch (reconciliation is List + Get).
//
// Real fields are added in M1; this stub only exists so buf generates.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fleet/v1alpha1/provider.proto

package fleetv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapacityProvider_Create_FullMethodName    = "/fleet.v1alpha1.CapacityProvider/Create"
	CapacityProvider_Configure_FullMethodName = "/fleet.v1alpha1.CapacityProvider/Configure"
	CapacityProvider_Drain_FullMethodName     = "/fleet.v1alpha1.CapacityProvider/Drain"
	CapacityProvider_Delete_FullMethodName    = "/fleet.v1alpha1.CapacityProvider/Delete"
	CapacityProvider_Get_FullMethodName       = "/fleet.v1alpha1.CapacityProvider/Get"
	CapacityProvider_List_FullMethodName      = "/fleet.v1alpha1.CapacityProvider/List"
)

// CapacityProviderClient is the client API for CapacityProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapacityProviderClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TransitionAck, error)
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*TransitionAck, error)
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*TransitionAck, error)
	Delete(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*TransitionAck, error)
	Get(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*Machine, error)
	List(ctx context.Context, in *ListFilter, opts ...grpc.CallOption) (*MachineList, error)
}

type capacityProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewCapacityProviderClient(cc grpc.ClientConnInterface) CapacityProviderClient {
	return &capacityProviderClient{cc}
}

func (c *capacityProviderClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*TransitionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionAck)
	err := c.cc.Invoke(ctx, CapacityProvider_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityProviderClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*TransitionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionAck)
	err := c.cc.Invoke(ctx, CapacityProvider_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityProviderClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*TransitionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionAck)
	err := c.cc.Invoke(ctx, CapacityProvider_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityProviderClient) Delete(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*TransitionAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionAck)
	err := c.cc.Invoke(ctx, CapacityProvider_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityProviderClient) Get(ctx context.Context, in *MachineRef, opts ...grpc.CallOption) (*Machine, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Machine)
	err := c.cc.Invoke(ctx, CapacityProvider_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capacityProviderClient) List(ctx context.Context, in *ListFilter, opts ...grpc.CallOption) (*MachineList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MachineList)
	err := c.cc.Invoke(ctx, CapacityProvider_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapacityProviderServer is the server API for CapacityProvider service.
// All implementations must embed UnimplementedCapacityProviderServer
// for forward compatibility.
type CapacityProviderServer interface {
	Create(context.Context, *CreateRequest) (*TransitionAck, error)
	Configure(context.Context, *ConfigureRequest) (*TransitionAck, error)
	Drain(context.Context, *DrainRequest) (*TransitionAck, error)
	Delete(context.Context, *MachineRef) (*TransitionAck, error)
	Get(context.Context, *MachineRef) (*Machine, error)
	List(context.Context, *ListFilter) (*MachineList, error)
	mustEmbedUnimplementedCapacityProviderServer()
}

// UnimplementedCapacityProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapacityProviderServer struct{}

func (UnimplementedCapacityProviderServer) Create(context.Context, *CreateRequest) (*TransitionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCapacityProviderServer) Configure(context.Context, *ConfigureRequest) (*TransitionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedCapacityProviderServer) Drain(context.Context, *DrainRequest) (*TransitionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedCapacityProviderServer) Delete(context.Context, *MachineRef) (*TransitionAck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCapacityProviderServer) Get(context.Context, *MachineRef) (*Machine, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCapacityProviderServer) List(context.Context, *ListFilter) (*MachineList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCapacityProviderServer) mustEmbedUnimplementedCapacityProviderServer() {}
func (UnimplementedCapacityProviderServer) testEmbeddedByValue()                          {}

// UnsafeCapacityProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapacityProviderServer will
// result in compilation errors.
type UnsafeCapacityProviderServer interface {
	mustEmbedUnimplementedCapacityProviderServer()
}

func RegisterCapacityProviderServer(s grpc.ServiceRegistrar, srv CapacityProviderServer) {
	// If the following call pancis, it indicates UnimplementedCapacityProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapacityProvider_ServiceDesc, srv)
}

func _CapacityProvider_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityProvider_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityProvider_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityProvider_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).Delete(ctx, req.(*MachineRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityProvider_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MachineRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).Get(ctx, req.(*MachineRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapacityProvider_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapacityProviderServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapacityProvider_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapacityProviderServer).List(ctx, req.(*ListFilter))
	}
	return interceptor(ctx, in, info, handler)
}

// CapacityProvider_ServiceDesc is the grpc.ServiceDesc for CapacityProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapacityProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1alpha1.CapacityProvider",
	HandlerType: (*CapacityProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CapacityProvider_Create_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _CapacityProvider_Configure_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _CapacityProvider_Drain_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CapacityProvider_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _CapacityProvider_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CapacityProvider_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleet/v1alpha1/provider.proto",
}
