// CapacityProvider service: the contract every out-of-tree provider implements.
// Six RPCs only — Create, Configure, Drain, Delete, Get, List — all async,
// all idempotent. No Watch (reconciliation is List + Get).
//
// Real fields are added in M1; this stub only exists so buf generates.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fleet/v1alpha1/provider.proto

package fleetv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type ConfigureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type DrainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *DrainRequest) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type MachineRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineRef) Reset() {
	*x = MachineRef{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineRef) ProtoMessage() {}

func (x *MachineRef) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineRef.ProtoReflect.Descriptor instead.
func (*MachineRef) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *MachineRef) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type TransitionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionAck) Reset() {
	*x = TransitionAck{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionAck) ProtoMessage() {}

func (x *TransitionAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionAck.ProtoReflect.Descriptor instead.
func (*TransitionAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *TransitionAck) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type Machine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Machine) Reset() {
	*x = Machine{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Machine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Machine) ProtoMessage() {}

func (x *Machine) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Machine.ProtoReflect.Descriptor instead.
func (*Machine) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *Machine) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

type MachineList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineList) Reset() {
	*x = MachineList{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineList) ProtoMessage() {}

func (x *MachineList) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineList.ProtoReflect.Descriptor instead.
func (*MachineList) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *MachineList) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

// M1 adds the optional `since_revision` field per plan §0.1 C.
type ListFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placeholder   string                 `protobuf:"bytes,1,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilter) Reset() {
	*x = ListFilter{}
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilter) ProtoMessage() {}

func (x *ListFilter) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1alpha1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilter.ProtoReflect.Descriptor instead.
func (*ListFilter) Descriptor() ([]byte, []int) {
	return file_fleet_v1alpha1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ListFilter) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

var File_fleet_v1alpha1_provider_proto protoreflect.FileDescriptor

const file_fleet_v1alpha1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1dfleet/v1alpha1/provider.proto\x12\x0efleet.v1alpha1\"1\n" +
	"\rCreateRequest\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"4\n" +
	"\x10ConfigureRequest\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"0\n" +
	"\fDrainRequest\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\".\n" +
	"\n" +
	"MachineRef\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"1\n" +
	"\rTransitionAck\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"+\n" +
	"\aMachine\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\"/\n" +
	"\vMachineList\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder\".\n" +
	"\n" +
	"ListFilter\x12 \n" +
	"\vplaceholder\x18\x01 \x01(\tR\vplaceholder2\xb0\x03\n" +
	"\x10CapacityProvider\x12F\n" +
	"\x06Create\x12\x1d.fleet.v1alpha1.CreateRequest\x1a\x1d.fleet.v1alpha1.TransitionAck\x12L\n" +
	"\tConfigure\x12 .fleet.v1alpha1.ConfigureRequest\x1a\x1d.fleet.v1alpha1.TransitionAck\x12D\n" +
	"\x05Drain\x12\x1c.fleet.v1alpha1.DrainRequest\x1a\x1d.fleet.v1alpha1.TransitionAck\x12C\n" +
	"\x06Delete\x12\x1a.fleet.v1alpha1.MachineRef\x1a\x1d.fleet.v1alpha1.TransitionAck\x12:\n" +
	"\x03Get\x12\x1a.fleet.v1alpha1.MachineRef\x1a\x17.fleet.v1alpha1.Machine\x12?\n" +
	"\x04List\x12\x1a.fleet.v1alpha1.ListFilter\x1a\x1b.fleet.v1alpha1.MachineListB\xc9\x01\n" +
	"\x12com.fleet.v1alpha1B\rProviderProtoP\x01ZKgithub.com/intUnderflow/bigfleet/pkg/api/proto/fleet/v1alpha1;fleetv1alpha1\xa2\x02\x03FXX\xaa\x02\x0eFleet.V1alpha1\xca\x02\x0eFleet\\V1alpha1\xe2\x02\x1aFleet\\V1alpha1\\GPBMetadata\xea\x02\x0fFleet::V1alpha1b\x06proto3"

var (
	file_fleet_v1alpha1_provider_proto_rawDescOnce sync.Once
	file_fleet_v1alpha1_provider_proto_rawDescData []byte
)

func file_fleet_v1alpha1_provider_proto_rawDescGZIP() []byte {
	file_fleet_v1alpha1_provider_proto_rawDescOnce.Do(func() {
		file_fleet_v1alpha1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_provider_proto_rawDesc), len(file_fleet_v1alpha1_provider_proto_rawDesc)))
	})
	return file_fleet_v1alpha1_provider_proto_rawDescData
}

var file_fleet_v1alpha1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_fleet_v1alpha1_provider_proto_goTypes = []any{
	(*CreateRequest)(nil),    // 0: fleet.v1alpha1.CreateRequest
	(*ConfigureRequest)(nil), // 1: fleet.v1alpha1.ConfigureRequest
	(*DrainRequest)(nil),     // 2: fleet.v1alpha1.DrainRequest
	(*MachineRef)(nil),       // 3: fleet.v1alpha1.MachineRef
	(*TransitionAck)(nil),    // 4: fleet.v1alpha1.TransitionAck
	(*Machine)(nil),          // 5: fleet.v1alpha1.Machine
	(*MachineList)(nil),      // 6: fleet.v1alpha1.MachineList
	(*ListFilter)(nil),       // 7: fleet.v1alpha1.ListFilter
}
var file_fleet_v1alpha1_provider_proto_depIdxs = []int32{
	0, // 0: fleet.v1alpha1.CapacityProvider.Create:input_type -> fleet.v1alpha1.CreateRequest
	1, // 1: fleet.v1alpha1.CapacityProvider.Configure:input_type -> fleet.v1alpha1.ConfigureRequest
	2, // 2: fleet.v1alpha1.CapacityProvider.Drain:input_type -> fleet.v1alpha1.DrainRequest
	3, // 3: fleet.v1alpha1.CapacityProvider.Delete:input_type -> fleet.v1alpha1.MachineRef
	3, // 4: fleet.v1alpha1.CapacityProvider.Get:input_type -> fleet.v1alpha1.MachineRef
	7, // 5: fleet.v1alpha1.CapacityProvider.List:input_type -> fleet.v1alpha1.ListFilter
	4, // 6: fleet.v1alpha1.CapacityProvider.Create:output_type -> fleet.v1alpha1.TransitionAck
	4, // 7: fleet.v1alpha1.CapacityProvider.Configure:output_type -> fleet.v1alpha1.TransitionAck
	4, // 8: fleet.v1alpha1.CapacityProvider.Drain:output_type -> fleet.v1alpha1.TransitionAck
	4, // 9: fleet.v1alpha1.CapacityProvider.Delete:output_type -> fleet.v1alpha1.TransitionAck
	5, // 10: fleet.v1alpha1.CapacityProvider.Get:output_type -> fleet.v1alpha1.Machine
	6, // 11: fleet.v1alpha1.CapacityProvider.List:output_type -> fleet.v1alpha1.MachineList
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fleet_v1alpha1_provider_proto_init() }
func file_fleet_v1alpha1_provider_proto_init() {
	if File_fleet_v1alpha1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1alpha1_provider_proto_rawDesc), len(file_fleet_v1alpha1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_v1alpha1_provider_proto_goTypes,
		DependencyIndexes: file_fleet_v1alpha1_provider_proto_depIdxs,
		MessageInfos:      file_fleet_v1alpha1_provider_proto_msgTypes,
	}.Build()
	File_fleet_v1alpha1_provider_proto = out.File
	file_fleet_v1alpha1_provider_proto_goTypes = nil
	file_fleet_v1alpha1_provider_proto_depIdxs = nil
}
