// Shard is the operator-initiated bidirectional stream that carries every
// piece of cluster ↔ shard traffic. The cluster operator dials the shard
// and holds a long-lived stream; no inbound listener is required on the
// cluster side. All multiplexing happens here:
//
//  • roll-ups (operator → shard, periodic, full-replacement)
//  • bootstrap blob requests/responses (shard pulls; operator answers)
//  • reclaim instructions (shard → operator) and acks
//  • node state and available-capacity updates (shard → operator)
//
// Coalescing messages (NodeStateUpdate, AvailableCapacityUpdate) carry an
// explicit `supersedes_key`. The shard's outbox is permitted to drop an
// older queued frame when a newer one with the same key arrives. The
// operator applies frames in arrival order.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: fleet/v1alpha1/shard.proto

package fleetv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shard_Session_FullMethodName = "/fleet.v1alpha1.Shard/Session"
)

// ShardClient is the client API for Shard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperatorMessage, ShardMessage], error)
}

type shardClient struct {
	cc grpc.ClientConnInterface
}

func NewShardClient(cc grpc.ClientConnInterface) ShardClient {
	return &shardClient{cc}
}

func (c *shardClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperatorMessage, ShardMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Shard_ServiceDesc.Streams[0], Shard_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperatorMessage, ShardMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shard_SessionClient = grpc.BidiStreamingClient[OperatorMessage, ShardMessage]

// ShardServer is the server API for Shard service.
// All implementations must embed UnimplementedShardServer
// for forward compatibility.
type ShardServer interface {
	Session(grpc.BidiStreamingServer[OperatorMessage, ShardMessage]) error
	mustEmbedUnimplementedShardServer()
}

// UnimplementedShardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardServer struct{}

func (UnimplementedShardServer) Session(grpc.BidiStreamingServer[OperatorMessage, ShardMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedShardServer) mustEmbedUnimplementedShardServer() {}
func (UnimplementedShardServer) testEmbeddedByValue()               {}

// UnsafeShardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardServer will
// result in compilation errors.
type UnsafeShardServer interface {
	mustEmbedUnimplementedShardServer()
}

func RegisterShardServer(s grpc.ServiceRegistrar, srv ShardServer) {
	// If the following call pancis, it indicates UnimplementedShardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shard_ServiceDesc, srv)
}

func _Shard_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShardServer).Session(&grpc.GenericServerStream[OperatorMessage, ShardMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shard_SessionServer = grpc.BidiStreamingServer[OperatorMessage, ShardMessage]

// Shard_ServiceDesc is the grpc.ServiceDesc for Shard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1alpha1.Shard",
	HandlerType: (*ShardServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Shard_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fleet/v1alpha1/shard.proto",
}
